"""Phrase banks: concept x mention form -> sentence templates.

Every list here is split train/test by index parity (even -> train, odd ->
test): templates, header frames, filler lines and the names of other people.
The words that mark negation, past time and current time are split the same
way (NEG_CUES, TIME_CUES, CURRENT_CUES); tests check that each template other
than a generic absence uses only its own split's cues, that present and
relative forms carry no negation or past-time cue, and that every current
value carries a current cue of its split.

Slots: {v} value, {dia} diastolic pressure, {year}, {Poss} the patient's
possessive pronoun (Her/His), {rel} the other person.

Finding forms (status, time) and their use:
  generic     absent, current   absence that does not name the concept (base)
  present     present, current  flip
  past        present, past     flip if the criterion counts past, else time near-miss
  absent      absent, current   named absence (negation near-miss)
  rel         present, current  other person: subject near-miss, or a flip when
                                a first-degree relative counts
  rel_past    present, past     other person, past (used only where past counts)
  delabelled  present, past     allergy label removed after testing (tier "delabelled")
Numeric forms:
  current     present, current  base, flip and numeric near-miss (one template)
  past        present, past     flip-side value in an earlier year (time near-miss)
  superseded  present, past     recent value replaced by today's (tier "superseded")
"""

FORMS = {
    "generic": ("absent", "current"),
    "present": ("present", "current"),
    "past": ("present", "past"),
    "absent": ("absent", "current"),
    "rel": ("present", "current"),
    "rel_past": ("present", "past"),
    "delabelled": ("present", "past"),
    "current": ("present", "current"),
    "superseded": ("present", "past"),
}

# Cue words, matched as whole words in lower case: negation, past time, and the
# markers that make a value or finding current.
NEG_CUES = {"train": ("denies", "no", "not"),
            "test": ("never", "negative", "ruled out", "absent", "free of", "without")}
TIME_CUES = {"train": ("resolved", "healed", "previously", "completed", "stopped",
                       "yesterday", "on admission", "removed"),
             "test": ("formerly", "outgrown", "ago", "recovered", "earlier", "last month",
                      "de-labeled", "delabeled")}
CURRENT_CUES = {"train": ("today", "this morning", "at this assessment", "on arrival"),
                "test": ("current", "currently", "now", "latest", "at this visit")}


def by_split(items, split):
    if split == "train":
        return items[0::2]
    if split == "test":
        return items[1::2]
    raise ValueError(f"split must be train or test, got {split!r}")


BANKS = {
    # ---- findings ---------------------------------------------------------
    "pen_allergy": {
        "generic": ["No known drug allergies.",
                    "Drug allergies: none known.",
                    "Allergies: none.",
                    "Reports no allergies to medicines."],
        "present": ["Allergic to penicillin (urticaria).",
                    "Penicillin allergy: anaphylaxis.",
                    "Allergies: penicillin (rash).",
                    "Known penicillin allergy with angioedema.",
                    "Reports an allergy to penicillin that causes hives.",
                    "Penicillin-allergic (facial swelling)."],
        "past": ["Penicillin allergy in childhood, resolved; tolerated amoxicillin in {year}.",
                 "Formerly allergic to penicillin; outgrown, with uneventful amoxicillin use in {year}.",
                 "Previously allergic to penicillin; tolerated a full amoxicillin course in {year}.",
                 "Had a penicillin allergy as a child that was outgrown years ago."],
        "absent": ["Denies penicillin allergy.",
                   "Tolerates penicillin without any reaction.",
                   "No penicillin allergy.",
                   "Has never been allergic to penicillin."],
        "rel": ["{Poss} {rel} is allergic to penicillin.",
                "{Poss} {rel} has a penicillin allergy.",
                "{Poss} {rel} reacts to penicillin with hives.",
                "{Poss} {rel} cannot take penicillin because of an allergy."],
        "delabelled": ["Penicillin allergy label removed in {year} after an uneventful oral challenge.",
                       "Penicillin allergy was de-labeled in {year} following a skin test.",
                       "Previously labeled allergic to penicillin; label removed in {year} after testing.",
                       "Formerly recorded as penicillin-allergic; de-labeled in {year} by an allergy clinic."],
    },
    "pregnancy": {
        "generic": ["Regular menstrual cycles.",
                    "Last menstrual period began eight days before this visit.",
                    "Uses condoms for contraception.",
                    "Menstrual cycles every 28 days."],
        "present": ["Pregnant, 12 weeks by dates.",
                    "Pregnant, confirmed by ultrasound at 9 weeks.",
                    "Positive pregnancy test today; about 7 weeks pregnant.",
                    "She is pregnant (18 weeks)."],
        "past": ["Pregnancy in {year}, completed with a term delivery.",
                 "Her only pregnancy ended in a live birth two years ago.",
                 "Previously pregnant, delivering at term in {year}.",
                 "Last pregnancy was in {year}; recovered well after the birth."],
        "absent": ["Not pregnant (urine test today).",
                   "Pregnancy test negative at this visit.",
                   "No pregnancy on today's urine test.",
                   "Pregnancy ruled out by a blood test at this visit."],
        "rel": ["{Poss} {rel} is pregnant.",
                "{Poss} {rel} is currently pregnant with twins.",
                "{Poss} {rel} is 30 weeks pregnant.",
                "{Poss} {rel} is pregnant and due next month."],
    },
    "peptic_ulcer": {
        "generic": ["No dyspepsia or melena.",
                    "Abdomen soft and non-tender.",
                    "Bowel habit normal; no abdominal pain.",
                    "Appetite good; no indigestion."],
        "present": ["Active peptic ulcer seen on endoscopy, on treatment.",
                    "Has an active duodenal ulcer.",
                    "Bleeding gastric ulcer under active treatment.",
                    "Active peptic ulcer disease."],
        "past": ["Peptic ulcer in {year}, healed on repeat endoscopy.",
                 "Duodenal ulcer years ago; recovered fully with treatment.",
                 "Previously had a gastric ulcer, healed in {year}.",
                 "Formerly treated for a peptic ulcer; endoscopy in {year} showed it had gone."],
        "absent": ["No peptic ulcer disease.",
                   "Has never had a peptic ulcer.",
                   "Denies any history of peptic ulcer.",
                   "Peptic ulcer absent on recent endoscopy."],
        "rel": ["{Poss} {rel} has an active peptic ulcer.",
                "{Poss} {rel} is being treated for a duodenal ulcer.",
                "{Poss} {rel} has a bleeding stomach ulcer.",
                "{Poss} {rel} has peptic ulcer disease."],
    },
    "clarithromycin": {
        "generic": ["No current medications.",
                    "Takes no regular medicines.",
                    "Medication list: none.",
                    "Uses no prescription or over-the-counter drugs."],
        "present": ["Takes clarithromycin 500 mg twice daily.",
                    "On clarithromycin for a chest infection, day 3 of 7.",
                    "Takes clarithromycin as part of Helicobacter pylori treatment.",
                    "Medications: clarithromycin 250 mg twice daily."],
        "past": ["Completed a course of clarithromycin in {year}.",
                 "Took clarithromycin for pneumonia years ago.",
                 "Clarithromycin course in {year}, stopped after 7 days.",
                 "Formerly took clarithromycin for a chest infection in {year}."],
        "absent": ["Not taking clarithromycin.",
                   "Has never taken clarithromycin.",
                   "No clarithromycin on the medication list.",
                   "Clarithromycin absent from the pharmacy dispensing record."],
        "rel": ["{Poss} {rel} is taking clarithromycin.",
                "{Poss} {rel} is on a course of clarithromycin.",
                "{Poss} {rel} takes clarithromycin twice daily.",
                "{Poss} {rel} currently uses clarithromycin."],
    },
    "cad": {
        "generic": ["Exercises regularly without chest pain.",
                    "Chest pain on exertion: none reported.",
                    "No exertional chest discomfort.",
                    "Climbs two flights of stairs without symptoms."],
        "present": ["Coronary artery disease with stable angina.",
                    "Has coronary artery disease, managed medically.",
                    "Coronary artery disease on ongoing treatment.",
                    "Known coronary artery disease (two-vessel disease on angiography)."],
        "past": ["Coronary artery disease treated with a stent in {year}.",
                 "Coronary artery disease years ago, with angina that went away after bypass surgery.",
                 "Previously treated for coronary artery disease (stent, {year}).",
                 "Had coronary artery disease, treated with bypass surgery in {year}; recovered well."],
        "absent": ["No history of coronary artery disease.",
                   "Has never had coronary artery disease.",
                   "Denies coronary artery disease, past or present.",
                   "Never diagnosed with coronary artery disease."],
        "rel": ["{Poss} {rel} has coronary artery disease.",
                "{Poss} {rel} has angina from coronary artery disease.",
                "{Poss} {rel} is being treated for coronary artery disease.",
                "{Poss} {rel} has known coronary artery disease."],
        "rel_past": ["{Poss} {rel} had coronary artery disease treated with a stent in {year}.",
                     "{Poss} {rel} had bypass surgery for coronary artery disease years ago."],
    },
    "vte": {
        "generic": ["No known clotting problems.",
                    "Clotting history unremarkable.",
                    "No known blood clotting disorder.",
                    "Never treated for a blood clot."],
        "present": ["On treatment for a deep vein thrombosis in the left leg.",
                    "Has an acute pulmonary embolism, diagnosed this week.",
                    "Active DVT of the right calf on anticoagulation.",
                    "Ongoing treatment for venous thrombosis of the left arm."],
        "past": ["Deep vein thrombosis after a fracture in {year}.",
                 "Pulmonary embolism years ago, treated for six months.",
                 "Previously had a DVT, in {year}.",
                 "Recovered from a pulmonary embolism in {year}."],
        "absent": ["No personal or family history of venous thromboembolism.",
                   "Has never had a DVT or pulmonary embolism, nor has any parent or sibling.",
                   "Denies any DVT or pulmonary embolism, past or present, personally or in parents, siblings or children.",
                   "Venous thromboembolism has never occurred in the patient or in any parent, sibling or child."],
        "rel": ["{Poss} {rel} has a deep vein thrombosis.",
                "{Poss} {rel} is being treated for a pulmonary embolism.",
                "{Poss} {rel} has a DVT in one leg.",
                "{Poss} {rel} is on anticoagulation for venous thrombosis."],
        "rel_past": ["{Poss} {rel} had a pulmonary embolism in {year}.",
                     "{Poss} {rel} had a DVT years ago.",
                     "{Poss} {rel} had a deep vein thrombosis in {year}.",
                     "{Poss} {rel} recovered from a pulmonary embolism in {year}."],
    },
    "confusion": {
        "generic": ["Alert and attentive.",
                    "Speech clear; follows commands.",
                    "Answers questions appropriately.",
                    "Gives a clear account of the illness."],
        "present": ["New confusion since this morning.",
                    "Disoriented to time and place, which is new for the patient.",
                    "Acutely confused, per family.",
                    "Newly disoriented and unable to give a clear history."],
        "past": ["Brief confusion during a urinary infection in {year}, resolved.",
                 "Was confused for a day after surgery years ago; recovered fully.",
                 "Previously confused during a fever in {year}.",
                 "Formerly had an episode of confusion with dehydration in {year}."],
        "absent": ["No confusion.",
                   "Confusion absent; answers questions appropriately.",
                   "Not confused or disoriented.",
                   "Without any confusion on assessment."],
        "rel": ["{Poss} {rel} has new confusion.",
                "{Poss} {rel} has become disoriented this week.",
                "{Poss} {rel} is acutely confused.",
                "{Poss} {rel} is newly disoriented."],
    },
    "stroke": {
        "generic": ["Neurological examination unremarkable.",
                    "Gait normal; no focal weakness.",
                    "Cranial nerves intact.",
                    "Power and sensation normal in all limbs."],
        "present": ["Acute ischemic stroke this week.",
                    "Has weakness of the left arm from a stroke this month.",
                    "Ongoing symptoms from a stroke this week.",
                    "Transient ischemic attack this week; carotid imaging is pending."],
        "past": ["Ischemic stroke in {year}; mild residual weakness of the left hand.",
                 "TIA years ago, with full recovery.",
                 "Previously had a stroke, in {year}.",
                 "Recovered from a stroke in {year}."],
        "absent": ["No history of stroke or TIA.",
                   "Has never had a stroke or TIA.",
                   "Denies ever having had a stroke or transient ischemic attack.",
                   "Never diagnosed with a stroke or TIA."],
        "rel": ["{Poss} {rel} is recovering from a stroke this month.",
                "{Poss} {rel} was admitted with a stroke this week.",
                "{Poss} {rel} has an acute stroke.",
                "{Poss} {rel} is in the hospital with a TIA."],
        "rel_past": ["{Poss} {rel} had a stroke in {year}.",
                     "{Poss} {rel} had a TIA years ago."],
    },
    "chf": {
        "generic": ["Jugular venous pressure not raised.",
                    "Heart sounds without a gallop.",
                    "Heart size normal on chest radiograph.",
                    "Sleeps flat on one pillow."],
        "present": ["Heart failure with reduced ejection fraction.",
                    "Has heart failure, treated with diuretics.",
                    "Chronic heart failure (NYHA class II).",
                    "Current heart failure with ankle swelling."],
        "past": ["Heart failure in {year} after viral myocarditis, resolved.",
                 "Had heart failure years ago from severe anemia; it recovered fully once the anemia was corrected.",
                 "Previously had heart failure from a thyroid problem in {year}, resolved with treatment.",
                 "Formerly had heart failure from stress cardiomyopathy; recovered fully in {year} and off all heart medicines since."],
        "absent": ["No history of heart failure.",
                   "Has never had heart failure.",
                   "Denies heart failure at any time.",
                   "Heart failure: never diagnosed."],
        "rel": ["{Poss} {rel} has heart failure.",
                "{Poss} {rel} is treated for heart failure.",
                "{Poss} {rel} lives with chronic heart failure.",
                "{Poss} {rel} has advanced heart failure."],
        "rel_past": ["{Poss} {rel} had heart failure in {year}.",
                     "{Poss} {rel} recovered from heart failure in {year}."],
    },
    "diabetes": {
        "generic": ["Fasting glucose normal on today's blood tests.",
                    "HbA1c 5.3% at a routine check.",
                    "No excessive thirst or urination.",
                    "Random glucose 92 mg/dL."],
        "present": ["Type 2 diabetes, diet-controlled.",
                    "Has type 2 diabetes on metformin.",
                    "Diabetes mellitus type 1.",
                    "Insulin-treated diabetes."],
        "past": ["Type 2 diabetes diagnosed in {year}, resolved after weight loss.",
                 "Had diabetes years ago that went into remission on a low-calorie diet.",
                 "Previously had type 2 diabetes ({year}); resolved after bariatric surgery.",
                 "Formerly diabetic; in remission since {year}."],
        "absent": ["No history of diabetes.",
                   "Has never had diabetes.",
                   "Denies diabetes, past or present.",
                   "Never diagnosed with diabetes."],
        "rel": ["{Poss} {rel} has type 2 diabetes.",
                "{Poss} {rel} is diabetic.",
                "{Poss} {rel} has diabetes treated with insulin.",
                "{Poss} {rel} lives with type 1 diabetes."],
        "rel_past": ["{Poss} {rel} had diabetes in {year}, resolved with weight loss.",
                     "{Poss} {rel} had diabetes years ago that went away after a change in diet."],
    },
    "vascular": {
        "generic": ["Peripheral pulses palpable.",
                    "Walks without calf pain.",
                    "Foot pulses easily felt.",
                    "Ankle-brachial index normal today."],
        "present": ["Peripheral artery disease with calf claudication.",
                    "Admitted with a myocardial infarction this week.",
                    "Has peripheral artery disease.",
                    "Has symptomatic peripheral artery disease of both legs."],
        "past": ["Myocardial infarction in {year}, treated with a stent.",
                 "Heart attack years ago, with full recovery.",
                 "Previously had a myocardial infarction, in {year}.",
                 "Recovered from a heart attack in {year}."],
        "absent": ["No history of myocardial infarction or peripheral artery disease.",
                   "Has never had a heart attack or peripheral artery disease.",
                   "Denies ever having had a myocardial infarction or peripheral artery disease.",
                   "Never diagnosed with a myocardial infarction or peripheral artery disease."],
        "rel": ["{Poss} {rel} has peripheral artery disease.",
                "{Poss} {rel} is in the hospital with a heart attack.",
                "{Poss} {rel} is being treated for a myocardial infarction this month.",
                "{Poss} {rel} has peripheral artery disease with leg pain."],
        "rel_past": ["{Poss} {rel} had a myocardial infarction in {year}.",
                     "{Poss} {rel} had a heart attack years ago."],
    },
    # ---- numerics: the value always follows the concept's keyword ----------
    "egfr": {
        "current": ["eGFR today: {v} mL/min/1.73 m2.",
                    "Current eGFR {v} mL/min/1.73 m2.",
                    "Renal function today: eGFR {v} mL/min/1.73 m2.",
                    "eGFR now {v} mL/min/1.73 m2.",
                    "eGFR {v} mL/min/1.73 m2 on today's labs.",
                    "Latest eGFR: {v} mL/min/1.73 m2."],
        "past": ["eGFR {v} mL/min/1.73 m2 in {year} during acute kidney injury, resolved.",
                 "In {year}, eGFR fell to {v} mL/min/1.73 m2 during sepsis and later recovered.",
                 "eGFR {v} mL/min/1.73 m2 in {year} (dehydration).",
                 "During an admission in {year}, eGFR was {v} mL/min/1.73 m2."],
        "superseded": ["eGFR was {v} mL/min/1.73 m2 yesterday, before rehydration.",
                       "Earlier this week eGFR was {v} mL/min/1.73 m2, while the patient was dehydrated.",
                       "eGFR {v} mL/min/1.73 m2 yesterday during vomiting; repeated today.",
                       "eGFR was {v} mL/min/1.73 m2 last month during a diarrheal illness."],
    },
    "platelets": {
        "current": ["Platelet count today: {v} x10^9/L.",
                    "Current platelet count {v} x10^9/L.",
                    "Platelets {v} x10^9/L on this morning's blood count.",
                    "Platelet count now {v} x10^9/L.",
                    "Complete blood count today: platelets {v} x10^9/L.",
                    "Latest platelet count {v} x10^9/L."],
        "past": ["Platelet count {v} x10^9/L in {year} during chemotherapy, resolved after treatment.",
                 "In {year}, platelets fell to {v} x10^9/L during a viral illness and later recovered.",
                 "Platelet count {v} x10^9/L in {year} (dengue fever).",
                 "During an illness in {year}, platelets were {v} x10^9/L."],
        "superseded": ["Platelet count was {v} x10^9/L on admission (clumped sample).",
                       "Earlier this week, platelets were {v} x10^9/L in a tube that had clotted.",
                       "Platelets {v} x10^9/L yesterday, in a sample since repeated.",
                       "Platelet count was {v} x10^9/L last month during an infection."],
    },
    "alt_enzyme": {
        "current": ["ALT today: {v} U/L.",
                    "Current ALT {v} U/L.",
                    "Liver tests today: ALT {v} U/L.",
                    "ALT now {v} U/L.",
                    "ALT {v} U/L on today's labs.",
                    "Latest ALT result: {v} U/L."],
        "past": ["ALT {v} U/L in {year} during hepatitis A, resolved.",
                 "In {year}, ALT rose to {v} U/L during a viral illness and later recovered.",
                 "ALT {v} U/L in {year} (drug reaction).",
                 "During an illness in {year}, ALT was {v} U/L."],
        "superseded": ["ALT was {v} U/L yesterday, before a repeat test.",
                       "Earlier this week ALT was {v} U/L while the patient had a fever.",
                       "ALT {v} U/L yesterday after strenuous exercise; repeated today.",
                       "ALT was {v} U/L last month during a viral illness."],
    },
    "bun": {
        "current": ["BUN {v} mg/dL this morning.",
                    "Blood urea nitrogen now: {v} mg/dL.",
                    "BUN at this assessment: {v} mg/dL.",
                    "Blood urea nitrogen {v} mg/dL on the current labs.",
                    "Today's BUN is {v} mg/dL.",
                    "Latest blood urea nitrogen: {v} mg/dL."],
        "past": ["BUN {v} mg/dL in {year} during gastroenteritis, resolved.",
                 "In {year}, blood urea nitrogen rose to {v} mg/dL with dehydration and later recovered.",
                 "BUN {v} mg/dL in {year} (vomiting illness).",
                 "During an admission in {year}, blood urea nitrogen was {v} mg/dL."],
        "superseded": ["BUN was {v} mg/dL yesterday, before intravenous fluids.",
                       "Earlier this week blood urea nitrogen was {v} mg/dL.",
                       "BUN {v} mg/dL yesterday at the clinic, since repeated.",
                       "Blood urea nitrogen was {v} mg/dL last month."],
    },
    "rr": {
        "current": ["Respiratory rate {v}/min this morning.",
                    "Current respiratory rate {v}/min.",
                    "Respiratory rate today: {v}/min.",
                    "Observations now: respiratory rate {v}/min.",
                    "Respiratory rate {v}/min at this assessment.",
                    "Latest respiratory rate {v}/min."],
        "past": ["Respiratory rate {v}/min during an asthma attack in {year}, resolved.",
                 "In {year}, respiratory rate reached {v}/min during a panic attack and later recovered.",
                 "Respiratory rate {v}/min in {year} (asthma exacerbation).",
                 "During an admission in {year}, respiratory rate was {v}/min."],
        "superseded": ["Respiratory rate was {v}/min yesterday evening, settled overnight.",
                       "Earlier this week respiratory rate was {v}/min during a coughing fit.",
                       "Respiratory rate {v}/min yesterday at the clinic.",
                       "Respiratory rate was {v}/min last month during an asthma flare."],
    },
    "sbp": {
        "current": ["Blood pressure {v}/{dia} mmHg this morning.",
                    "Current systolic blood pressure {v} mmHg.",
                    "Blood pressure today: {v}/{dia} mmHg.",
                    "Observations now: blood pressure {v}/{dia} mmHg.",
                    "Systolic blood pressure {v} mmHg at this assessment.",
                    "Latest blood pressure {v}/{dia} mmHg."],
        "past": ["Systolic blood pressure {v} mmHg in {year} during an acute illness, resolved.",
                 "In {year}, systolic blood pressure measured {v} mmHg at an urgent-care visit and later recovered.",
                 "Systolic blood pressure {v} mmHg in {year} (emergency department visit).",
                 "During an admission in {year}, systolic blood pressure was {v} mmHg."],
        "superseded": ["Systolic blood pressure was {v} mmHg yesterday on a home monitor.",
                       "Earlier this week systolic blood pressure was {v} mmHg.",
                       "Blood pressure {v}/{dia} mmHg yesterday at the clinic.",
                       "Systolic blood pressure was {v} mmHg last month at a pharmacy check."],
    },
    "age": {
        "current": ["Age today: {v} years.",
                    "Currently aged {v} years.",
                    "Age on arrival: {v} years.",
                    "Current age {v} years.",
                    "Age at this assessment: {v} years.",
                    "Age at this visit: {v} years."],
    },
    # ---- concepts added with the extended rule library ---------------------
    "sulfa_allergy": {
        "generic": ["No known medication allergies.",
                    "Current drug allergies: none.",
                    "Not allergic to any medicines.",
                    "Medication allergies: none at present."],
        "present": ["Allergic to sulfa antibiotics (hives).",
                    "Sulfonamide antibiotic allergy: generalized rash.",
                    "Allergies: sulfa drugs (rash).",
                    "Develops hives whenever given sulfonamide antibiotics."],
        "past": ["Sulfa antibiotic allergy in childhood, resolved; tolerated trimethoprim-sulfamethoxazole in {year}.",
                 "Formerly reacted to sulfonamide antibiotics but outgrew the allergy; took trimethoprim-sulfamethoxazole safely in {year}.",
                 "Previously allergic to sulfonamide antibiotics, since resolved; completed an uneventful trimethoprim-sulfamethoxazole course in {year}.",
                 "Had a sulfa antibiotic allergy as an infant that was outgrown long ago."],
        "absent": ["Denies any allergy to sulfa antibiotics.",
                   "Has never been allergic to sulfonamide antibiotics.",
                   "No sulfonamide antibiotic allergy.",
                   "Allergy history negative for sulfa drugs."],
        "rel": ["{Poss} {rel} is allergic to sulfa antibiotics.",
                "{Poss} {rel} has a sulfonamide antibiotic allergy.",
                "{Poss} {rel} gets hives from trimethoprim-sulfamethoxazole.",
                "{Poss} {rel} has a documented sulfa allergy."],
        "delabelled": ["Sulfa allergy label removed in {year} after an uneventful oral challenge.",
                       "Sulfonamide antibiotic allergy delabeled in {year} after allergy clinic testing.",
                       "Previously labeled allergic to sulfa drugs; the label was removed in {year} when a challenge dose was tolerated.",
                       "Formerly listed as allergic to trimethoprim-sulfamethoxazole; delabeled in {year} after a supervised test dose proved safe."],
    },
    "warfarin": {
        "generic": ["Not taking any anticoagulants.",
                    "Current anticoagulants: none.",
                    "No blood thinners on the medication list.",
                    "Anticoagulant therapy: none at present."],
        "present": ["Takes warfarin daily, with the dose adjusted to the INR.",
                    "Currently on warfarin for recurrent blood clots in the legs.",
                    "Medications: warfarin 5 mg once daily.",
                    "Anticoagulated with warfarin; INR checked monthly at the clinic."],
        "past": ["Took warfarin for six months after a leg clot in {year}; stopped when treatment was completed.",
                 "Formerly on warfarin for a blood clot; the course ended years ago.",
                 "Previously on warfarin; it was stopped in {year} and not restarted.",
                 "Finished a warfarin course in {year} and is off all anticoagulants now."],
        "absent": ["Denies taking warfarin.",
                   "Has never been prescribed warfarin.",
                   "Not on warfarin.",
                   "Warfarin is absent from the current medication list."],
        "rel": ["{Poss} {rel} takes warfarin.",
                "{Poss} {rel} is on warfarin with monthly INR checks.",
                "{Poss} {rel} takes warfarin every evening for an irregular heartbeat.",
                "{Poss} {rel} is anticoagulated with warfarin."],
    },
    "aspirin": {
        "generic": ["Takes no antiplatelet medicines.",
                    "Antiplatelet therapy: none at present.",
                    "Not on any antiplatelet medication.",
                    "Current antiplatelet drugs: none."],
        "present": ["Takes aspirin 81 mg daily.",
                    "Currently on low-dose aspirin for heart protection.",
                    "Medication list: aspirin 81 mg, taken each morning.",
                    "Uses a daily aspirin on a cardiologist's recommendation."],
        "past": ["Took low-dose aspirin until {year}, when it was stopped on medical advice.",
                 "Formerly took a daily aspirin, discontinued years ago.",
                 "Previously on aspirin 81 mg; stopped in {year} and not restarted.",
                 "Quit low-dose aspirin in {year} and has stayed off it since."],
        "absent": ["Denies any aspirin use.",
                   "Has never taken aspirin.",
                   "Not taking aspirin.",
                   "Medication history negative for aspirin."],
        "rel": ["{Poss} {rel} takes aspirin daily.",
                "{Poss} {rel} is on low-dose aspirin.",
                "{Poss} {rel} takes aspirin 81 mg every morning.",
                "{Poss} {rel} uses a daily aspirin for heart protection."],
    },
    "angioedema": {
        "generic": ["No history of swelling of the lips, tongue or face.",
                    "Face and neck without swelling on examination.",
                    "Mouth and throat look normal; airway clear.",
                    "Has never had sudden swelling of the face or throat."],
        "present": ["Has hereditary angioedema, with attacks every few months.",
                    "Recurrent angioedema, under allergy follow-up.",
                    "Idiopathic angioedema, treated with daily antihistamines.",
                    "Lives with chronic angioedema that flares several times a year."],
        "past": ["Angioedema of the lips in {year}, resolved with treatment.",
                 "An episode of angioedema years ago, with full recovery.",
                 "Previously had angioedema of the tongue in {year}, which settled within hours.",
                 "Formerly had recurrent angioedema, in remission for many years now."],
        "absent": ["No history of angioedema.",
                   "Has never had angioedema.",
                   "Denies any episode of angioedema, past or present.",
                   "Never diagnosed with angioedema."],
        "rel": ["{Poss} {rel} has recurrent angioedema.",
                "{Poss} {rel} is being treated for angioedema.",
                "{Poss} {rel} has angioedema of the lips this week.",
                "{Poss} {rel} has active angioedema of the face."],
        "rel_past": ["{Poss} {rel} had angioedema in {year}.",
                     "{Poss} {rel} had an attack of angioedema years ago.",
                     "{Poss} {rel} was treated for angioedema in {year}; it resolved.",
                     "{Poss} {rel} recovered from an episode of angioedema in {year}."],
    },
    "asthma": {
        "generic": ["Chest clear on auscultation, with no wheeze.",
                    "Lungs clear, without wheeze or prolonged expiration.",
                    "Takes no inhaled medicines.",
                    "Inhaler use: none."],
        "present": ["Has asthma and uses an albuterol inhaler for wheeze.",
                    "Asthma, on a daily inhaled steroid.",
                    "Asthmatic; wheezes on exertion and in cold air.",
                    "Persistent asthma, using a rescue inhaler most weeks."],
        "past": ["Childhood asthma, resolved by adolescence.",
                 "Asthma in the early school years, outgrown long ago.",
                 "Previously had asthma in childhood; symptom-free and off inhalers for decades.",
                 "Formerly had asthma in elementary school; well for many years without inhalers."],
        "absent": ["Denies asthma.",
                   "Has never had asthma.",
                   "No diagnosis of asthma.",
                   "Asthma ruled out on lung function testing."],
        "rel": ["{Poss} {rel} has asthma.",
                "{Poss} {rel} uses an inhaler for asthma.",
                "{Poss} {rel} is being treated for asthma.",
                "{Poss} {rel} is asthmatic."],
    },
    "mech_valve": {
        "generic": ["No valve clicks on auscultation.",
                    "Heart sounds irregular, without a metallic click.",
                    "Auscultation: irregular rhythm and no clicks.",
                    "Irregularly irregular pulse; heart sounds free of clicks."],
        "present": ["Has a mechanical aortic valve.",
                    "Mechanical mitral valve in place; metallic closing clicks audible.",
                    "Mechanical heart valve in the mitral position.",
                    "Lives with a mechanical aortic valve prosthesis."],
        "past": ["Mechanical aortic valve removed in {year} and replaced with a tissue valve.",
                 "Formerly had a mechanical mitral valve, exchanged for a bioprosthetic valve in {year}.",
                 "Previously had a mechanical mitral valve, replaced with a tissue valve after endocarditis in {year}.",
                 "Mechanical aortic valve explanted years ago for valve thrombosis; a bioprosthesis now sits in its place."],
        "absent": ["No mechanical heart valve.",
                   "Has never had a mechanical heart valve.",
                   "Does not have a mechanical valve.",
                   "Never received a mechanical heart valve."],
        "rel": ["{Poss} {rel} has a mechanical heart valve.",
                "{Poss} {rel} has an implanted mechanical aortic valve.",
                "{Poss} {rel} has a mechanical mitral valve.",
                "{Poss} {rel} attends a valve clinic for a mechanical mitral valve."],
    },
    "hit": {
        "generic": ["No known adverse reactions to heparin.",
                    "Has never had a reaction to heparin.",
                    "Heparin: no intolerance recorded.",
                    "Has had heparin before without any problem."],
        "present": ["Has heparin-induced thrombocytopenia, confirmed by antibody testing.",
                    "Heparin-induced thrombocytopenia, with heparin antibodies still positive.",
                    "Active heparin-induced thrombocytopenia with a positive functional assay.",
                    "Being treated for heparin-induced thrombocytopenia by the hematology team."],
        "past": ["Heparin-induced thrombocytopenia in {year}, resolved once heparin was stopped.",
                 "Heparin-induced thrombocytopenia after heart surgery years ago; recovered fully.",
                 "Previously had heparin-induced thrombocytopenia, in {year}; antibodies since cleared.",
                 "Formerly had heparin-induced thrombocytopenia during a hospital stay in {year}; blood counts recovered afterward."],
        "absent": ["No history of heparin-induced thrombocytopenia.",
                   "Has never had heparin-induced thrombocytopenia.",
                   "Denies ever having heparin-induced thrombocytopenia.",
                   "Never diagnosed with heparin-induced thrombocytopenia."],
        "rel": ["{Poss} {rel} has heparin-induced thrombocytopenia.",
                "{Poss} {rel} is in the hospital with heparin-induced thrombocytopenia.",
                "{Poss} {rel} is being treated for heparin-induced thrombocytopenia.",
                "{Poss} {rel} has developed heparin-induced thrombocytopenia after surgery."],
        "rel_past": ["{Poss} {rel} had heparin-induced thrombocytopenia in {year}.",
                     "{Poss} {rel} developed heparin-induced thrombocytopenia years ago.",
                     "{Poss} {rel} previously had heparin-induced thrombocytopenia after an operation.",
                     "{Poss} {rel} recovered from heparin-induced thrombocytopenia in {year}."],
    },
    "crc": {
        "generic": ["No personal history of cancer.",
                    "Has never been diagnosed with a malignancy.",
                    "Has not had cancer of any kind.",
                    "Lifetime cancer diagnoses: none."],
        "present": ["Has colon cancer and is receiving treatment from an oncologist.",
                    "Colorectal cancer under active treatment.",
                    "Bowel cancer, on treatment with an oncology team.",
                    "Lives with colon cancer and attends an oncology clinic."],
        "past": ["Colon cancer removed surgically in {year}; in remission since.",
                 "Bowel cancer cured by surgery years ago, without recurrence.",
                 "Previously had colorectal cancer, treated in {year} and in remission.",
                 "Formerly had colon cancer; recovered fully after an operation in {year}."],
        "absent": ["No personal history of colorectal cancer.",
                   "Has never had bowel cancer.",
                   "Denies ever having colon cancer.",
                   "Never diagnosed with colorectal cancer."],
        "rel": ["{Poss} {rel} has colon cancer.",
                "{Poss} {rel} is undergoing surgery for bowel cancer.",
                "{Poss} {rel} is being treated for colorectal cancer.",
                "{Poss} {rel} has advanced colorectal cancer."],
        "rel_past": ["{Poss} {rel} had colon cancer in {year}.",
                     "{Poss} {rel} was treated for bowel cancer years ago.",
                     "{Poss} {rel} had surgery for colorectal cancer in {year}.",
                     "{Poss} {rel} recovered from colon cancer after an operation in {year}."],
    },
    "bleeding": {
        "generic": ["No melena or hematemesis.",
                    "Has never needed a blood transfusion.",
                    "Hemoglobin normal on today's blood count.",
                    "Bowel habit normal, without any blood in the stool."],
        "present": ["Active major upper gastrointestinal bleed, requiring blood transfusion.",
                    "Currently has a major bleed from a duodenal ulcer, with transfusion under way.",
                    "Ongoing major bleeding from the lower bowel, receiving blood transfusion.",
                    "Major bleed from the stomach at present, with hemoglobin falling."],
        "past": ["Major gastrointestinal bleed in {year} needing transfusion, resolved with endoscopic treatment.",
                 "Major intracranial bleed after a fall years ago, with full recovery.",
                 "Previously transfused for a major bleed from a stomach ulcer, which healed in {year}.",
                 "Recovered from a major lower gastrointestinal bleed in {year} that required transfusion."],
        "absent": ["No history of major bleeding.",
                   "Has never had a major bleed.",
                   "Denies any major bleeding, past or present.",
                   "Medical records negative for major bleeding at any time."],
        "rel": ["{Poss} {rel} is hospitalized with a major gastrointestinal bleed.",
                "{Poss} {rel} is currently being transfused for a major bleed.",
                "{Poss} {rel} has an active major bleed from a stomach ulcer.",
                "{Poss} {rel} has major bleeding from the bowel at present."],
        "rel_past": ["{Poss} {rel} had a major gastrointestinal bleed in {year}.",
                     "{Poss} {rel} needed a blood transfusion for a major bleed years ago.",
                     "{Poss} {rel} previously had a major bleed from a stomach ulcer, which healed.",
                     "{Poss} {rel} recovered from a major intracranial bleed in {year}."],
    },
    "cancer": {
        "generic": ["No active malignancy.",
                    "Malignant disease: none at present.",
                    "No unexplained weight loss or new lumps.",
                    "Weight steady over the past year."],
        "present": ["Active colon cancer under oncology treatment.",
                    "Has metastatic lung cancer, receiving palliative treatment.",
                    "Non-Hodgkin lymphoma diagnosed this year, on active treatment.",
                    "Has multiple myeloma and is receiving treatment for it."],
        "past": ["Colon cancer removed surgically in {year}, in remission since.",
                 "Had thyroid cancer years ago and is now cured.",
                 "Previously treated for Hodgkin lymphoma, with treatment completed in {year}; remains in remission.",
                 "Formerly had kidney cancer, cured by surgery in {year}."],
        "absent": ["No active cancer.",
                   "Has never had cancer.",
                   "Denies any active cancer.",
                   "Cancer ruled out by recent investigations."],
        "rel": ["{Poss} {rel} has active colon cancer.",
                "{Poss} {rel} is being treated for leukemia.",
                "{Poss} {rel} has lymphoma and is on active treatment.",
                "{Poss} {rel} has lung cancer that has spread to the liver."],
    },
    "exudate": {
        "generic": ["No pus or white patches on the tonsils.",
                    "Tonsils pink and clean on inspection.",
                    "Throat mildly red; tonsils not coated.",
                    "Tonsils slightly red but clean, without pus."],
        "present": ["White exudate on both tonsils.",
                    "Tonsils swollen and coated with yellow exudate.",
                    "Patchy exudate over the right tonsil.",
                    "Tonsillar exudate visible on both sides."],
        "past": ["Tonsillar exudate during tonsillitis in {year}, resolved with antibiotics.",
                 "Had exudate on the tonsils with strep throat years ago, which cleared within days.",
                 "Previously had white exudate on the tonsils in {year}, since resolved.",
                 "Recovered fully from tonsillitis with exudate in {year}."],
        "absent": ["No tonsillar exudate.",
                   "Tonsils free of exudate.",
                   "Exudate not seen on either tonsil.",
                   "Tonsillar exudate absent on examination."],
        "rel": ["{Poss} {rel} has tonsillitis with white exudate on the tonsils.",
                "{Poss} {rel} has a sore throat with tonsillar exudate.",
                "{Poss} {rel} has strep throat, with exudate on both tonsils.",
                "{Poss} {rel} currently has a throat infection with tonsillar exudate."],
    },
    "neck_nodes": {
        "generic": ["Neck soft and nontender.",
                    "Neck palpation unremarkable.",
                    "No tender swellings in the neck.",
                    "Front of the neck without tenderness or swelling."],
        "present": ["Tender anterior cervical lymph nodes on both sides.",
                    "Anterior cervical lymph nodes enlarged and tender to touch.",
                    "Tender anterior cervical lymphadenopathy.",
                    "Tender, swollen lymph nodes in the front of the neck."],
        "past": ["Tender anterior cervical lymph nodes during tonsillitis in {year}, since resolved.",
                 "Tender anterior cervical lymph nodes with a throat infection years ago, which went down within two weeks.",
                 "Previously had tender, swollen lymph nodes at the front of the neck in {year}, since resolved.",
                 "Formerly had tender anterior cervical lymphadenopathy in {year}, with full recovery."],
        "absent": ["No tender anterior cervical lymph nodes.",
                   "Neck supple, without tender lymph nodes.",
                   "Anterior cervical lymph nodes not enlarged or tender.",
                   "Palpation of the neck negative for tender lymph nodes."],
        "rel": ["{Poss} {rel} has tender lymph nodes at the front of the neck.",
                "{Poss} {rel} has a throat infection with tender anterior cervical lymph nodes.",
                "{Poss} {rel} has tender, swollen anterior cervical lymph nodes.",
                "{Poss} {rel} currently has tender anterior cervical lymphadenopathy."],
    },
    "potassium": {
        "current": ["Serum potassium today: {v} mmol/L.",
                    "Current serum potassium {v} mmol/L.",
                    "Potassium {v} mmol/L on today's blood work.",
                    "Latest potassium result: {v} mmol/L.",
                    "Labs this morning: potassium {v} mmol/L.",
                    "Potassium at this visit is {v} mmol/L."],
        "past": ["Serum potassium {v} mmol/L in {year} during acute kidney injury, resolved.",
                 "In {year}, potassium reached {v} mmol/L with sepsis; the patient recovered fully.",
                 "Potassium {v} mmol/L in {year} while taking potassium supplements, since stopped.",
                 "Serum potassium of {v} mmol/L in {year} with severe dehydration; recovered after rehydration."],
        "superseded": ["Potassium was {v} mmol/L yesterday in a hemolyzed sample; repeated today.",
                       "Earlier this week, serum potassium measured {v} mmol/L, since rechecked.",
                       "Serum potassium {v} mmol/L yesterday on a delayed sample, before today's fresh draw.",
                       "Potassium was {v} mmol/L last month during a kidney injury that has since settled."],
    },
    "creatinine": {
        "current": ["Serum creatinine today: {v} mg/dL.",
                    "Current serum creatinine {v} mg/dL.",
                    "Creatinine {v} mg/dL on this morning's labs.",
                    "Latest creatinine result: {v} mg/dL.",
                    "Kidney function today: creatinine {v} mg/dL.",
                    "Creatinine at this visit is {v} mg/dL."],
        "past": ["Creatinine {v} mg/dL in {year} during acute kidney injury, resolved.",
                 "In {year}, serum creatinine rose to {v} mg/dL with sepsis; renal function later recovered.",
                 "Serum creatinine {v} mg/dL in {year} while taking ibuprofen, since stopped.",
                 "Creatinine peaked at {v} mg/dL in {year} in the setting of severe vomiting, returning to baseline afterward."],
        "superseded": ["Creatinine was {v} mg/dL on admission, before intravenous fluids.",
                       "Earlier this week, serum creatinine was {v} mg/dL during a vomiting illness; it has improved since.",
                       "Serum creatinine {v} mg/dL yesterday, an unexpected result that was repeated today.",
                       "Creatinine was {v} mg/dL last month after a contrast CT scan and has come down since."],
    },
    "wbc": {
        "current": ["White cell count today: {v} x10^9/L.",
                    "Current white cell count {v} x10^9/L.",
                    "WBC {v} x10^9/L on arrival.",
                    "Latest WBC is {v} x10^9/L.",
                    "Complete blood count this morning: white cell count {v} x10^9/L.",
                    "White cell count now {v} x10^9/L."],
        "past": ["White cell count {v} x10^9/L in {year} during a kidney infection, resolved on antibiotics.",
                 "In {year}, WBC reached {v} x10^9/L with appendicitis; recovered after surgery.",
                 "WBC {v} x10^9/L in {year} while on a course of prednisone, since completed.",
                 "White cell count of {v} x10^9/L with cellulitis in {year}, later back to normal."],
        "superseded": ["White cell count {v} x10^9/L yesterday at a clinic visit; repeated today.",
                       "Earlier this week, WBC was {v} x10^9/L; it has since been rechecked.",
                       "WBC was {v} x10^9/L yesterday, before today's repeat blood count.",
                       "White cell count was {v} x10^9/L last month during a urinary infection, since treated."],
    },
    "spo2": {
        "current": ["Oxygen saturation at this assessment is {v}%.",
                    "Current oxygen saturation {v}%.",
                    "Oxygen saturation {v}% on rounds today.",
                    "Latest oxygen saturation reading: {v}%.",
                    "Pulse oximetry this morning: oxygen saturation {v}%.",
                    "Vital signs now: oxygen saturation {v}%."],
        "past": ["Oxygen saturation {v}% in {year} during pneumonia, resolved on treatment.",
                 "In {year}, oxygen saturation fell to {v}% with a severe asthma attack; recovered fully.",
                 "Oxygen saturation {v}% in {year} while trekking at high altitude, resolved on descent.",
                 "Oxygen saturation of {v}% in {year} with influenza, later back to normal."],
        "superseded": ["Oxygen saturation was {v}% yesterday, before oxygen therapy was started.",
                       "Earlier this week, oxygen saturation was {v}%; it has improved since.",
                       "Oxygen saturation {v}% yesterday evening after a coughing fit, before today's readings.",
                       "Oxygen saturation was {v}% last month during a chest infection that has since cleared."],
    },
    "temperature": {
        "current": ["Temperature today: {v} C.",
                    "Current temperature {v} C.",
                    "Oral temperature this morning: {v} C.",
                    "Temperature now {v} C (tympanic).",
                    "Temperature {v} C at this assessment.",
                    "Latest temperature {v} C."],
        "past": ["Temperature {v} C in {year} during influenza, resolved within days.",
                 "In {year}, temperature reached {v} C with a kidney infection that later cleared.",
                 "Temperature {v} C in {year} during tonsillitis, which resolved with antibiotics.",
                 "Temperature peaked at {v} C with pneumonia in {year}; recovered fully."],
        "superseded": ["Temperature was {v} C yesterday evening and settled overnight.",
                       "Earlier this week temperature reached {v} C at home; it has come down since.",
                       "Temperature measured yesterday at a pharmacy: {v} C; repeated today.",
                       "Temperature was {v} C last month with a urinary infection, since treated."],
    },
    "heart_rate": {
        "current": ["Heart rate today: {v}/min.",
                    "Current heart rate {v}/min.",
                    "Heart rate {v}/min on arrival.",
                    "Heart rate now {v}/min on the monitor.",
                    "Pulse taken this morning: heart rate {v}/min.",
                    "Latest heart rate {v}/min."],
        "past": ["Heart rate {v}/min in {year} during gastroenteritis with dehydration, resolved with fluids.",
                 "In {year}, heart rate rose to {v}/min with an overactive thyroid; recovered fully on treatment.",
                 "Heart rate {v}/min in {year} during a panic attack, which resolved within the hour.",
                 "Heart rate reached {v}/min with appendicitis in {year}, later cured by surgery."],
        "superseded": ["Heart rate was {v}/min yesterday at a walk-in clinic; repeated today.",
                       "Earlier this week heart rate was {v}/min on a fitness watch; a newer reading has replaced it.",
                       "Heart rate {v}/min yesterday evening after an albuterol nebulizer, settling overnight.",
                       "Heart rate was {v}/min last month with a stomach bug, and has slowed since."],
    },
    "weight": {
        "current": ["Weight today: {v} kg.",
                    "Current weight {v} kg.",
                    "Weighs {v} kg on the scale this morning.",
                    "Latest weight {v} kg.",
                    "Weight {v} kg at this assessment.",
                    "Currently weighs {v} kg."],
        "past": ["Weight {v} kg in {year} during a bout of severe depression; regained once the depression resolved.",
                 "In {year}, weight fell to {v} kg after major bowel surgery and later recovered.",
                 "Weight {v} kg in {year} during a long hospital stay, regained within months.",
                 "While unwell with an overactive thyroid in {year}, weight was {v} kg; it later returned to normal."],
        "superseded": ["Weight was wrongly charted as {v} kg yesterday; measured on a scale today.",
                       "Earlier this week weight was entered as {v} kg by mistake; corrected since.",
                       "Weight {v} kg yesterday on a chair scale that proved faulty; reweighed today.",
                       "Weight on last month's referral letter was {v} kg, later found to be a typing error."],
    },
    "calf_swelling": {
        "current": ["Difference in calf circumference today (left minus right): {v} cm.",
                    "Current calf swelling {v} cm compared with the right leg.",
                    "Calf circumference measured this morning is {v} cm greater on the left than the right.",
                    "Latest calf circumference difference, left versus right: {v} cm.",
                    "Left calf swelling at this assessment: {v} cm more than the right.",
                    "Calf circumference now {v} cm larger on the left."],
        "past": ["Calf swelling of {v} cm in {year} during cellulitis of the leg, resolved with antibiotics.",
                 "In {year}, calf circumference differed by {v} cm between the legs from a ruptured knee cyst; it later returned to normal.",
                 "Calf swelling {v} cm in {year} from a torn calf muscle, which healed within weeks.",
                 "After a sports injury in {year}, calf circumference was {v} cm larger on the injured leg; recovered fully."],
        "superseded": ["Calf swelling of {v} cm was measured yesterday at a nonstandard level; remeasured today.",
                       "Earlier this week a rough bedside check put calf swelling at {v} cm; rechecked since.",
                       "Calf circumference was wrongly transcribed as {v} cm greater on the left yesterday; amended today.",
                       "Calf swelling of {v} cm last month from a calf strain has gone down since."],
    },
}

# Header frames; HEADER_NO_AGE is used when the rule has an age criterion.
HEADER = ["{age}-year-old {noun}.",
          "A {age}-year-old {noun}.",
          "Patient: {sex}, {age} years.",
          "{Noun}, {age} years old."]
HEADER_NO_AGE = ["Patient: {sex}.",
                 "Sex: {sex}.",
                 "{Sex} patient.",
                 "Adult {noun}."]

# Other people, interleaved so both splits mix sexes and closeness.
PERSONS = ["mother", "father", "brother", "sister", "aunt", "uncle", "husband", "wife",
           "cousin", "roommate", "partner", "friend", "grandmother", "grandfather",
           "coworker", "sister-in-law"]
PERSON_OK = {   # who can plausibly carry the concept (default: anyone)
    "pregnancy": frozenset({"sister", "wife", "cousin", "roommate", "partner", "friend",
                            "coworker", "sister-in-law"}),
}


def persons(concept, split, age=None):
    """Other people who can plausibly carry the concept, for a patient of this age:
    grandparents only under 40, no parents' generation from 65, no spouse under 18."""
    ok = set(PERSON_OK.get(concept, PERSONS))
    if age is None or age >= 40:
        ok -= {"grandmother", "grandfather"}
    if age is not None and age >= 65:
        ok -= {"mother", "father", "aunt", "uncle"}
    if age is not None and age < 18:
        ok -= {"husband", "wife"}
    return [p for p in by_split(PERSONS, split) if p in ok]


# Neutral lines: one attribute each, no medications, no medical history, no
# people, and no criterion keyword of any rule (tests enforce the last).
FILLERS = [
    "Non-smoker.",
    "Drinks alcohol occasionally.",
    "Does crossword puzzles.",
    "Height 170 cm.",
    "Sleeps seven hours a night.",
    "Enjoys board games.",
    "Vaccinations up to date.",
    "Drinks two cups of coffee a day.",
    "Eats a varied diet.",
    "Hearing normal to conversation.",
    "Wears glasses for reading.",
    "Pupils equal and reactive to light.",
    "Enjoys gardening.",
    "Speaks English and Spanish.",
    "Collects postcards.",
    "Has a pet dog.",
    "Lives in a second-floor apartment.",
    "Drives a car.",
    "Reads most evenings.",
    "Studies part-time.",
    "Keeps houseplants.",
    "Drinks plenty of water.",
    "Uses sunscreen in summer.",
    "Sees a dentist yearly.",
    "Wears a seat belt when driving.",
    "Keeps a step counter.",
    "Sings in a weekly choir.",
    "Volunteers at a library.",
    "Paints watercolors as a hobby.",
    "Prefers morning appointments.",
    "Brought a written list of questions.",
    "Uses a smartphone for reminders.",
    "Nails normal.",
    "Uses public transport.",
    "Owns a bicycle.",
    "Teeth in good repair.",
    "Enjoys cooking.",
    "Plays chess online.",
    "Listens to podcasts.",
    "Grows tomatoes in the garden.",
    "Has two cats.",
    "Plays the piano.",
    "Watches football on weekends.",
    "Writes with the right hand.",
    "Lives on a quiet street.",
    "Uses reading glasses for small print.",
]


# Noun phrases for applicability claims ("<noun> reported in the case counts for
# this patient under the rule."); numerics add "<op> <threshold> <unit>".
NOUN = {
    "pen_allergy": "a penicillin allergy", "pregnancy": "a pregnancy",
    "peptic_ulcer": "a peptic ulcer", "clarithromycin": "clarithromycin use",
    "cad": "coronary artery disease", "vte": "a venous thromboembolism",
    "confusion": "confusion", "stroke": "a stroke or TIA", "chf": "heart failure",
    "diabetes": "diabetes", "vascular": "a myocardial infarction or peripheral artery disease",
    "angioedema": "angioedema", "asthma": "asthma", "mech_valve": "a mechanical heart valve",
    "warfarin": "warfarin use", "crc": "colorectal cancer",
    "hit": "heparin-induced thrombocytopenia", "sulfa_allergy": "a sulfonamide allergy",
    "bleeding": "a major bleeding event", "aspirin": "aspirin use", "cancer": "cancer",
    "exudate": "tonsillar exudate", "neck_nodes": "cervical lymph node tenderness",
    "egfr": "an eGFR value", "platelets": "a platelet count", "alt_enzyme": "an ALT value",
    "bun": "a blood urea nitrogen value", "rr": "a respiratory rate",
    "sbp": "a systolic blood pressure", "age": "an age", "potassium": "a potassium value",
    "creatinine": "a creatinine value", "temperature": "a temperature",
    "heart_rate": "a heart rate", "wbc": "a white cell count", "spo2": "an oxygen saturation",
    "weight": "a weight", "calf_swelling": "a calf swelling",
}
UNITS = {
    "egfr": "mL/min/1.73 m2", "platelets": "x10^9/L", "alt_enzyme": "U/L", "bun": "mg/dL",
    "rr": "/min", "sbp": "mmHg", "age": "years", "potassium": "mmol/L", "creatinine": "mg/dL",
    "temperature": "C", "heart_rate": "/min", "wbc": "x10^9/L", "spo2": "%", "weight": "kg",
    "calf_swelling": "cm",
}
