"""Phrase banks: concept x mention form -> sentence templates.

Every list is laid out in blocks of 6: index % 6 in 0-3 is the train split,
4-5 the test split (templates, header frames, filler lines, person names).
The words that mark negation, past time and current time are split the same
way (NEG_CUES, TIME_CUES, CURRENT_CUES); tests check that every template other
than a generic absence uses only its own split's cues, that present and
other-person forms carry no negation or past-time cue, and that every current
value carries a current cue of its split.

Slots: {v} value, {dia} diastolic pressure (sbp only), {year}, {Poss} the
patient's possessive pronoun (Her/His), {rel} another person.

Finding forms (status, time) and their use:
  generic     absent, current   absence that does not name the concept (base)
  present     present, current  flip
  past        present, past     flip if the criterion counts past, else time near-miss
  absent      absent, current   named absence (negation near-miss)
  rel         present, current  another person: subject near-miss, or a flip by a
                                first-degree relative where the criterion counts family
  rel_past    present, past     another person, past (used only where past counts)
  delabelled  present, past     allergy label removed after testing (tier "delabelled")
Numeric forms:
  current     present, current  base, flip, numeric and boundary near-misses (one template)
  past        present, past     flip-side value in an earlier year (time near-miss)
  superseded  present, past     recent value replaced by today's (tier "superseded")
Fillers: FILLERS (neutral), FILLERS_OTHER (another person's unrelated condition),
FILLERS_LAB (an old value of an unrelated lab); the long tier mixes all three.
"""

FORMS = {
    "generic": ("absent", "current"),
    "present": ("present", "current"),
    "past": ("present", "past"),
    "absent": ("absent", "current"),
    "rel": ("present", "current"),
    "rel_past": ("present", "past"),
    "delabelled": ("present", "past"),
    "current": ("present", "current"),
    "superseded": ("present", "past"),
}

# Cue words, matched as whole words in lower case.
NEG_CUES = {"train": ("denies", "no", "not"),
            "test": ("never", "negative", "ruled out", "absent", "free of", "without")}
TIME_CUES = {"train": ("resolved", "healed", "previously", "completed", "stopped",
                       "yesterday", "on admission", "removed"),
             "test": ("formerly", "outgrown", "ago", "recovered", "earlier", "last month",
                      "de-labeled", "delabeled")}
CURRENT_CUES = {"train": ("today", "this morning", "at this assessment", "on arrival"),
                "test": ("current", "currently", "now", "latest", "at this visit")}


def split_of(i):
    return "train" if i % 6 < 4 else "test"


def ids(items, split):
    """Indices of the items in this split."""
    if split not in ("train", "test"):
        raise ValueError(f"split must be train or test, got {split!r}")
    return [i for i in range(len(items)) if split_of(i) == split]


def by_split(items, split):
    return [items[i] for i in ids(items, split)]


# Header frames; HEADER_NO_AGE is used when the rule has an age criterion.
HEADER = ["{age}-year-old {noun}.", "Patient: {sex}, {age} years.", "{Sex}, {age} years.",
          "A {age}-year-old {noun}.",
          "{Noun} of {age} years.", "{Sex} patient of {age} years."]
HEADER_NO_AGE = ["Patient: {sex}.", "Sex: {sex}.", "Adult {noun}.", "{Sex} patient.",
                 "An adult {noun}.", "{Noun}, adult."]

# Other people, in blocks of 6 (0-3 train, 4-5 test).
PERSONS = ["mother", "brother", "aunt", "husband", "father", "sister",
           "cousin", "partner", "coworker", "grandmother", "uncle", "wife",
           "neighbor", "brother-in-law", "housemate", "grandfather", "roommate", "friend"]
FIRST_DEGREE_SHOWN = {"mother", "father", "brother", "sister"}
PERSON_OK = {   # who can plausibly carry the concept (default: anyone)
    "pregnancy": frozenset({"cousin", "partner", "coworker", "neighbor", "housemate",
                            "sister", "wife", "roommate", "friend"}),
}


def persons(concept, split, age=None):
    """Other people who can plausibly carry the concept, for a patient of this age:
    grandparents only under 40, no parents' generation from 65, no spouse under 18."""
    ok = set(PERSON_OK.get(concept, PERSONS))
    if age is None or age >= 40:
        ok -= {"grandmother", "grandfather"}
    if age is not None and age >= 65:
        ok -= {"mother", "father", "aunt", "uncle"}
    if age is not None and age < 18:
        ok -= {"husband", "wife"}
    return [p for p in by_split(PERSONS, split) if p in ok]


# Concepts whose generic absence lines may deny one another (e.g. "No known drug
# allergies" and a sulfonamide allergy). The engine omits a generic line when
# another concept of its group is present in the group's cases.
OVERLAP = (
    {"pen_allergy", "sulfa_allergy", "contrast_allergy", "angioedema", "hit"},
    {"aspirin", "warfarin", "vte", "hit", "mech_valve"},
    {"clarithromycin", "methotrexate", "lithium", "aspirin", "warfarin"},
    {"bleeding", "peptic_ulcer", "crc", "hemoptysis", "hemoglobin"},
    {"cancer", "crc"},
    {"stroke", "confusion"},
    {"cad", "vascular", "chf", "hypertension"},
    {"vascular", "calf_swelling"},
    {"hypertension", "sbp", "map"},
    {"warfarin", "inr"},
    {"supp_oxygen", "spo2"},
)


# Missing-input lines for a finding whose status is unknown ({What}/{what}: the
# criterion label). Measured inputs are unknown when omitted and need no line.
MISSING = [
    "{What}: not recorded.",
    "{What}: not documented in the records available.",
    "Information on {what} was not obtained.",
    "{What}: not asked about.",
    "{What}: unknown.",
    "{What}: status unclear from the records at hand.",
]


# Neutral lines: one attribute each, no medications, no medical history, no
# people and no criterion keyword of any rule (tests enforce the last).
FILLERS = [
    "Non-smoker.",
    "Drinks alcohol occasionally.",
    "Does crossword puzzles.",
    "Height 170 cm.",
    "Sleeps seven hours a night.",
    "Enjoys board games.",
    "Vaccinations up to date.",
    "Drinks two cups of coffee a day.",
    "Eats a varied diet.",
    "Hearing normal to conversation.",
    "Photographs local wildlife.",
    "Pupils equal and reactive to light.",
    "Enjoys gardening.",
    "Speaks English and Spanish.",
    "Collects postcards.",
    "Has a pet dog.",
    "Lives in a second-floor apartment.",
    "Drives a car.",
    "Reads most evenings.",
    "Bakes bread at home.",
    "Keeps houseplants.",
    "Drinks plenty of water.",
    "Uses sunscreen in summer.",
    "Sees a dentist yearly.",
    "Wears a seat belt when driving.",
    "Keeps a step counter.",
    "Sings in a weekly choir.",
    "Volunteers at a library.",
    "Paints watercolors as a hobby.",
    "Prefers morning appointments.",
    "Feeds birds in the backyard.",
    "Uses a smartphone for reminders.",
    "Nails normal.",
    "Uses public transport.",
    "Owns a bicycle.",
    "Teeth in good repair.",
    "Enjoys cooking.",
    "Plays chess online.",
    "Listens to podcasts.",
    "Grows tomatoes in the garden.",
    "Has two cats.",
    "Plays the piano.",
    "Watches football on weekends.",
    "Writes with the right hand.",
    "Lives on a quiet street.",
    "Uses reading glasses for small print.",
    "Knits as a hobby.",
    "Prefers to be addressed by first name.",
]

# Another person's unrelated condition (subject distractors for the long tier).
FILLERS_OTHER = [
    "{Poss} {rel} wears hearing aids.",
    "{Poss} {rel} is being treated for eczema.",
    "{Poss} {rel} broke a wrist, which has healed.",
    "{Poss} {rel} is nearsighted.",
    "{Poss} {rel} lives with psoriasis.",
    "{Poss} {rel} sprained a thumb last month.",
    "{Poss} {rel} had a splinter removed from a finger.",
    "{Poss} {rel} is left-handed.",
    "{Poss} {rel} has a broken finger in a splint.",
    "{Poss} {rel} completed physical therapy for a shoulder injury.",
    "{Poss} {rel} has a lazy eye.",
    "{Poss} {rel} burned a hand on a stove years ago.",
    "{Poss} {rel} has a chipped front tooth.",
    "{Poss} {rel} has a stutter.",
    "{Poss} {rel} has a fear of heights.",
    "{Poss} {rel} previously wore dental braces.",
    "{Poss} {rel} wears contact lenses.",
    "{Poss} {rel} has recovered from a dislocated finger.",
]

# An old value of an unrelated lab (time distractors for the long tier).
FILLERS_LAB = [
    "Sodium 140 mmol/L in {year}.",
    "Serum calcium 9.4 mg/dL in {year}.",
    "Albumin 4.1 g/dL in {year} (routine blood test).",
    "Magnesium 2.0 mg/dL in {year}.",
    "In {year}, folate was 12 ng/mL.",
    "Free T4 of 1.2 ng/dL in {year}.",
    "Chloride 103 mmol/L in {year}.",
    "Bicarbonate 26 mmol/L in {year} (annual physical).",
    "Phosphate 3.6 mg/dL in {year}.",
    "Total bilirubin 0.6 mg/dL in {year}.",
    "During a checkup in {year}, total protein was 7.0 g/dL.",
    "In {year}, lipase was 30 U/L.",
    "TSH 1.6 mIU/L in {year}.",
    "Vitamin D 38 ng/mL in {year} (wellness visit).",
    "Vitamin B12 450 pg/mL in {year}.",
    "Ferritin 60 ng/mL in {year}.",
    "Zinc of 85 mcg/dL in {year}.",
    "During a checkup in {year}, free T3 was 3.2 pg/mL.",
]

BANKS = {
    "pen_allergy": {
        "generic": [
            "No known drug allergies.",
            "No beta-lactam allergy.",
            "Not allergic to any antibiotics.",
            "Denies any drug allergies.",
            "Drug allergies: none known.",
            "Reports no allergies to medicines.",
        ],
        "present": [
            "Allergic to penicillin (urticaria).",
            "Allergies: penicillin (rash).",
            "Reports an allergy to penicillin that causes hives.",
            "Penicillin triggers an allergic reaction with wheezing in this patient.",
            "Penicillin allergy: anaphylaxis.",
            "Known penicillin allergy with angioedema.",
        ],
        "past": [
            "Penicillin allergy in childhood, resolved; tolerated amoxicillin in {year}.",
            "Previously allergic to penicillin; tolerated a full amoxicillin course in {year}.",
            "An old penicillin allergy has resolved; penicillin given for a dental abscess in {year} was well tolerated.",
            "Penicillin used to cause hives, but the allergy has resolved.",
            "Outgrew a penicillin allergy by {year}.",
            "Had a penicillin allergy as a child that was outgrown years ago.",
        ],
        "absent": [
            "Denies penicillin allergy.",
            "No penicillin allergy.",
            "Does not have a penicillin allergy.",
            "When asked about penicillin, reports no allergy to it.",
            "Tolerates penicillin without any reaction.",
            "Has never been allergic to penicillin.",
        ],
        "rel": [
            "{Poss} {rel} is allergic to penicillin.",
            "{Poss} {rel} reacts to penicillin with hives.",
            "{Poss} {rel} gets an itchy rash from penicillin.",
            "{Poss} {rel} carries an allergy alert card for penicillin.",
            "{Poss} {rel} has a penicillin allergy.",
            "{Poss} {rel} cannot take penicillin because of an allergy.",
        ],
        "delabelled": [
            "Penicillin allergy label removed in {year} after an uneventful oral challenge.",
            "Previously labeled allergic to penicillin; label removed in {year} after testing.",
            "Penicillin allergy alert taken off the chart in {year} after an amoxicillin challenge was tolerated.",
            "A graded challenge in {year} showed the penicillin allergy label was wrong, so it was removed.",
            "Penicillin allergy was de-labeled in {year} following a skin test.",
            "Formerly recorded as penicillin-allergic; de-labeled in {year} by an allergy clinic.",
        ],
    },
    "sulfa_allergy": {
        "generic": [
            "No known medication allergies.",
            "Not allergic to any medicines.",
            "No known antibiotic allergies.",
            "Denies allergies to any drug or food.",
            "Current drug allergies: none.",
            "Medication allergies: none at present.",
        ],
        "present": [
            "Allergic to sulfa antibiotics (hives).",
            "Allergies: sulfa drugs (rash).",
            "Has a sulfa allergy that causes skin blistering.",
            "Sulfa antibiotics cause an itchy allergic rash in this patient.",
            "Sulfonamide antibiotic allergy: generalized rash.",
            "Develops hives whenever given sulfonamide antibiotics.",
        ],
        "past": [
            "Sulfa antibiotic allergy in childhood, resolved; tolerated trimethoprim-sulfamethoxazole in {year}.",
            "Previously allergic to sulfonamide antibiotics, since resolved; completed an uneventful trimethoprim-sulfamethoxazole course in {year}.",
            "Was allergic to sulfa drugs in the past; that allergy has resolved.",
            "Sulfa allergy resolved, as shown by a well-tolerated trimethoprim-sulfamethoxazole course in {year}.",
            "Outgrew a sulfonamide antibiotic allergy by {year}.",
            "Had a sulfa antibiotic allergy as an infant that was outgrown long ago.",
        ],
        "absent": [
            "Denies any allergy to sulfa antibiotics.",
            "No sulfonamide antibiotic allergy.",
            "Does not have a sulfa allergy.",
            "No allergy to trimethoprim-sulfamethoxazole or other sulfa drugs.",
            "Has never been allergic to sulfonamide antibiotics.",
            "Allergy history negative for sulfa drugs.",
        ],
        "rel": [
            "{Poss} {rel} is allergic to sulfa antibiotics.",
            "{Poss} {rel} gets hives from trimethoprim-sulfamethoxazole.",
            "{Poss} {rel} reacts to sulfa antibiotics with a rash.",
            "{Poss} {rel} wears a medical alert bracelet for a sulfa allergy.",
            "{Poss} {rel} has a sulfonamide antibiotic allergy.",
            "{Poss} {rel} has a documented sulfa allergy.",
        ],
        "delabelled": [
            "Sulfa allergy label removed in {year} after an uneventful oral challenge.",
            "Previously labeled allergic to sulfa drugs; the label was removed in {year} when a challenge dose was tolerated.",
            "Sulfa drugs were cleared from the allergy list in {year} after a graded trimethoprim-sulfamethoxazole challenge.",
            "An oral challenge in {year} disproved the sulfa allergy, and the label was removed.",
            "Sulfonamide antibiotic allergy delabeled in {year} after allergy clinic testing.",
            "Formerly listed as allergic to trimethoprim-sulfamethoxazole; delabeled in {year} after a supervised test dose proved safe.",
        ],
    },
    "pregnancy": {
        "generic": [
            "Regular menstrual cycles.",
            "Uses condoms for contraception.",
            "Had a normal period last week.",
            "Menstruating normally this week.",
            "Last menstrual period began eight days before this visit.",
            "Menstrual cycles every 28 days.",
        ],
        "present": [
            "Pregnant, 12 weeks by dates.",
            "Positive pregnancy test today; about 7 weeks pregnant.",
            "Is 31 weeks pregnant, with normal fetal movements.",
            "In the second trimester of a planned pregnancy.",
            "Pregnant, confirmed by ultrasound at 9 weeks.",
            "She is pregnant (18 weeks).",
        ],
        "past": [
            "Pregnancy in {year}, completed with a term delivery.",
            "Previously pregnant, delivering at term in {year}.",
            "Cesarean delivery in {year} at the end of a healthy pregnancy.",
            "Early pregnancy loss in {year}.",
            "Her only pregnancy ended in a live birth two years ago.",
            "Last pregnancy was in {year}; recovered well after the birth.",
        ],
        "absent": [
            "Not pregnant (urine test today).",
            "No pregnancy on today's urine test.",
            "Denies any possibility of pregnancy.",
            "Not pregnant; menstruating at this assessment.",
            "Pregnancy test negative at this visit.",
            "Pregnancy ruled out by a blood test at this visit.",
        ],
        "rel": [
            "{Poss} {rel} is pregnant.",
            "{Poss} {rel} is 30 weeks pregnant.",
            "{Poss} {rel} is in early pregnancy.",
            "{Poss} {rel} has an ongoing pregnancy at 20 weeks.",
            "{Poss} {rel} is currently pregnant with twins.",
            "{Poss} {rel} is pregnant and due next month.",
        ],
    },
    "peptic_ulcer": {
        "generic": [
            "No dyspepsia or melena.",
            "Bowel habit normal; no abdominal pain.",
            "No epigastric pain or heartburn.",
            "No black or bloody stools.",
            "Abdomen soft and non-tender.",
            "Appetite good; no indigestion.",
        ],
        "present": [
            "Active peptic ulcer seen on endoscopy, on treatment.",
            "Bleeding gastric ulcer under active treatment.",
            "Taking omeprazole for a gastric ulcer diagnosed at endoscopy this week.",
            "A stomach ulcer is causing burning pain after meals.",
            "Has an active duodenal ulcer.",
            "Active peptic ulcer disease.",
        ],
        "past": [
            "Peptic ulcer in {year}, healed on repeat endoscopy.",
            "Previously had a gastric ulcer, healed in {year}.",
            "Gastric ulcer healed after eight weeks of omeprazole.",
            "Treatment for Helicobacter pylori in {year} resolved a stomach ulcer.",
            "Duodenal ulcer years ago; recovered fully with treatment.",
            "Formerly treated for a peptic ulcer; endoscopy in {year} showed it had gone.",
        ],
        "absent": [
            "No peptic ulcer disease.",
            "Denies any history of peptic ulcer.",
            "No peptic ulcer, either active or healed.",
            "No ulcer of the stomach or duodenum at any time.",
            "Has never had a peptic ulcer.",
            "Medical record negative for peptic ulcer, current or past.",
        ],
        "rel": [
            "{Poss} {rel} has an active peptic ulcer.",
            "{Poss} {rel} has a bleeding stomach ulcer.",
            "{Poss} {rel} takes omeprazole for an active gastric ulcer.",
            "{Poss} {rel} was found to have a stomach ulcer this week.",
            "{Poss} {rel} is being treated for a duodenal ulcer.",
            "{Poss} {rel} has peptic ulcer disease.",
        ],
        "rel_past": [
            "{Poss} {rel} had a peptic ulcer that healed in {year}.",
            "{Poss} {rel} was treated for a stomach ulcer in {year}.",
            "{Poss} {rel} previously took omeprazole for a gastric ulcer.",
            "{Poss} {rel} had a duodenal ulcer, which resolved with treatment.",
            "{Poss} {rel} recovered from a stomach ulcer years ago.",
            "{Poss} {rel} formerly had peptic ulcer disease.",
        ],
    },
    "clarithromycin": {
        "generic": [
            "No macrolide antibiotics on the medication list.",
            "Antibiotics: none.",
            "Not taking any antibiotics.",
            "No antibiotics or antifungals in use.",
            "Current antibiotic therapy: none.",
            "Has no antibiotic course under way.",
        ],
        "present": [
            "Takes clarithromycin 500 mg twice daily.",
            "Takes clarithromycin as part of Helicobacter pylori treatment.",
            "Started clarithromycin this morning for sinusitis.",
            "Clarithromycin, prescribed last week for whooping cough, is being taken as directed.",
            "On clarithromycin for a chest infection, day 3 of 7.",
            "Currently taking clarithromycin for an ear infection.",
        ],
        "past": [
            "Completed a course of clarithromycin in {year}.",
            "Clarithromycin course in {year}, stopped after 7 days.",
            "Clarithromycin was stopped when a sinus infection cleared.",
            "Had a 14-day clarithromycin course for Helicobacter pylori in {year}, completed as planned.",
            "Took clarithromycin for pneumonia years ago.",
            "Formerly took clarithromycin for a chest infection in {year}.",
        ],
        "absent": [
            "Not taking clarithromycin.",
            "No clarithromycin on the medication list.",
            "Denies taking clarithromycin.",
            "No antibiotics are being taken, including clarithromycin.",
            "Has never taken clarithromycin.",
            "Clarithromycin absent from the pharmacy dispensing record.",
        ],
        "rel": [
            "{Poss} {rel} is taking clarithromycin.",
            "{Poss} {rel} takes clarithromycin twice daily.",
            "{Poss} {rel} has a sinus infection being treated with clarithromycin.",
            "{Poss} {rel} is prescribed clarithromycin for Helicobacter pylori.",
            "{Poss} {rel} is on a course of clarithromycin.",
            "{Poss} {rel} currently uses clarithromycin.",
        ],
    },
    "warfarin": {
        "generic": [
            "Not taking any anticoagulants.",
            "No vitamin K antagonist on the medication list.",
            "Not taking a vitamin K antagonist.",
            "No INR monitoring in place.",
            "Current anticoagulants: none.",
            "Anticoagulant therapy: none at present.",
        ],
        "present": [
            "Takes warfarin daily, with the dose adjusted to the INR.",
            "Medications: warfarin 5 mg once daily.",
            "Takes warfarin for atrial fibrillation.",
            "On long-term warfarin, with an INR of 2.6 this morning.",
            "Currently on warfarin, prescribed by the cardiology clinic.",
            "Anticoagulated with warfarin; INR checked monthly at the clinic.",
        ],
        "past": [
            "Took warfarin for six months in {year}; stopped when treatment was completed.",
            "Previously on warfarin; it was stopped in {year} and not restarted.",
            "Warfarin was stopped in {year}, four weeks after a successful cardioversion.",
            "Warfarin, taken for six weeks after leg fracture surgery, has been stopped.",
            "Came off warfarin years ago after a heart rhythm problem settled.",
            "Finished a warfarin course in {year} and is now off warfarin.",
        ],
        "absent": [
            "Denies taking warfarin.",
            "Not on warfarin.",
            "Does not take warfarin or any other vitamin K antagonist.",
            "Not taking warfarin, according to the patient.",
            "Has never been prescribed warfarin.",
            "Warfarin is absent from the current medication list.",
        ],
        "rel": [
            "{Poss} {rel} takes warfarin.",
            "{Poss} {rel} takes warfarin every evening for an irregular heartbeat.",
            "{Poss} {rel} relies on daily warfarin tablets.",
            "{Poss} {rel} is prescribed warfarin after a heart valve replacement.",
            "{Poss} {rel} is on warfarin with monthly INR checks.",
            "{Poss} {rel} is anticoagulated with warfarin.",
        ],
    },
    "cad": {
        "generic": [
            "Exercises regularly without chest pain.",
            "No exertional chest discomfort.",
            "Resting ECG shows no ischemic changes.",
            "Takes no medicines for angina.",
            "Chest pain on exertion: none reported.",
            "Climbs two flights of stairs without symptoms.",
        ],
        "present": [
            "Coronary artery disease with stable angina.",
            "Coronary artery disease on ongoing treatment.",
            "Coronary artery disease, with angina when walking uphill.",
            "Coronary artery disease, followed in cardiology clinic every six months.",
            "Has coronary artery disease, managed medically.",
            "Known coronary artery disease (two-vessel disease on angiography).",
        ],
        "past": [
            "Coronary artery disease treated with a stent in {year}.",
            "Previously treated for coronary artery disease (stent, {year}).",
            "Angioplasty for coronary artery disease in {year}, after which all symptoms resolved.",
            "Coronary artery disease was treated with a stent, and cardiology follow-up was completed in {year} with no remaining symptoms.",
            "Coronary artery disease years ago, with angina that went away after bypass surgery.",
            "Had coronary artery disease, treated with bypass surgery in {year}; recovered well.",
        ],
        "absent": [
            "No history of coronary artery disease.",
            "Denies coronary artery disease, past or present.",
            "No coronary artery disease at any time.",
            "Medical records show no coronary artery disease, past or present.",
            "Has never had coronary artery disease.",
            "Never diagnosed with coronary artery disease.",
        ],
        "rel": [
            "{Poss} {rel} has coronary artery disease.",
            "{Poss} {rel} is being treated for coronary artery disease.",
            "{Poss} {rel} takes a daily statin for coronary artery disease.",
            "{Poss} {rel} carries a nitroglycerin spray for coronary artery disease.",
            "{Poss} {rel} has angina from coronary artery disease.",
            "{Poss} {rel} has known coronary artery disease.",
        ],
        "rel_past": [
            "{Poss} {rel} had coronary artery disease treated with a stent in {year}.",
            "{Poss} {rel} previously had coronary artery disease, treated with angioplasty.",
            "{Poss} {rel} completed cardiac rehabilitation for coronary artery disease in {year}.",
            "{Poss} {rel} had coronary artery disease found on a stress test in {year}.",
            "{Poss} {rel} had bypass surgery for coronary artery disease years ago.",
            "{Poss} {rel} was formerly under the care of a cardiologist for coronary artery disease.",
        ],
    },
    "vte": {
        "generic": [
            "Not on any blood thinners.",
            "No known blood clotting disorder.",
            "No inherited clotting condition such as factor V Leiden.",
            "Takes no anticoagulant medicines.",
            "Coagulation tests normal on recent bloodwork.",
            "Varicose veins: none seen.",
        ],
        "present": [
            "On treatment for a deep vein thrombosis in the left leg.",
            "Active DVT of the right calf on anticoagulation.",
            "CT pulmonary angiogram today shows a pulmonary embolism.",
            "Has a deep vein thrombosis and takes apixaban twice daily.",
            "Has an acute pulmonary embolism, diagnosed this week.",
            "Ongoing treatment for venous thrombosis of the left arm.",
        ],
        "past": [
            "Deep vein thrombosis after a fracture in {year}.",
            "Previously had a DVT, in {year}.",
            "Anticoagulation for a pulmonary embolism was completed in {year}, and the clot resolved.",
            "Deep vein thrombosis following knee surgery in {year}; resolved with treatment.",
            "Pulmonary embolism years ago, treated for six months.",
            "Recovered from a pulmonary embolism in {year}.",
        ],
        "absent": [
            "No personal or family history of venous thromboembolism.",
            "Denies any DVT or pulmonary embolism, past or present, personally or in parents, siblings or children.",
            "No venous thromboembolism at any time, personally or among first-degree relatives.",
            "Medical records show no venous thromboembolism, and none is reported in first-degree relatives.",
            "Has never had a DVT or pulmonary embolism, nor has any parent or sibling.",
            "Venous thromboembolism has never occurred in the patient or in any parent, sibling or child.",
        ],
        "rel": [
            "{Poss} {rel} has a deep vein thrombosis.",
            "{Poss} {rel} has a DVT in one leg.",
            "{Poss} {rel} was admitted this morning with a pulmonary embolism.",
            "{Poss} {rel} has a DVT confirmed on ultrasound today.",
            "{Poss} {rel} is being treated for a pulmonary embolism.",
            "{Poss} {rel} is on anticoagulation for venous thrombosis.",
        ],
        "rel_past": [
            "{Poss} {rel} had a pulmonary embolism in {year}.",
            "{Poss} {rel} had a deep vein thrombosis in {year}.",
            "{Poss} {rel} previously took blood thinners for a deep vein thrombosis.",
            "{Poss} {rel} completed a course of anticoagulation in {year} after a pulmonary embolism.",
            "{Poss} {rel} had a DVT years ago.",
            "{Poss} {rel} recovered from a pulmonary embolism in {year}.",
        ],
    },
    "stroke": {
        "generic": [
            "Neurological examination unremarkable.",
            "Cranial nerves intact.",
            "Speech fluent and face symmetric.",
            "Visual fields full to confrontation.",
            "Gait normal; no focal weakness.",
            "Power and sensation normal in all limbs.",
        ],
        "present": [
            "Acute ischemic stroke this week.",
            "Ongoing symptoms from a stroke this week.",
            "Recent stroke, with slurred speech that persists today.",
            "Brain MRI today shows a new ischemic stroke.",
            "Has weakness of the left arm from a stroke this month.",
            "Transient ischemic attack this week; carotid imaging is pending.",
        ],
        "past": [
            "Ischemic stroke in {year}; mild residual weakness of the left hand.",
            "Previously had a stroke, in {year}.",
            "Previously had a transient ischemic attack; the arm numbness resolved within an hour.",
            "Minor stroke in {year} that caused slurred speech, which resolved completely.",
            "TIA years ago, with full recovery.",
            "Recovered from a stroke in {year}.",
        ],
        "absent": [
            "No history of stroke or TIA.",
            "Denies ever having had a stroke or transient ischemic attack.",
            "No stroke or TIA at any time.",
            "Medical records show no stroke or TIA at any point.",
            "Has never had a stroke or TIA.",
            "Never diagnosed with a stroke or TIA.",
        ],
        "rel": [
            "{Poss} {rel} is recovering from a stroke this month.",
            "{Poss} {rel} has an acute stroke.",
            "{Poss} {rel} has a new stroke that affects speech.",
            "{Poss} {rel} had a TIA this morning.",
            "{Poss} {rel} was admitted with a stroke this week.",
            "{Poss} {rel} is in the hospital with a TIA.",
        ],
        "rel_past": [
            "{Poss} {rel} had a stroke in {year}.",
            "{Poss} {rel} was previously treated for a TIA, and the symptoms resolved within a day.",
            "{Poss} {rel} completed stroke rehabilitation in {year}.",
            "{Poss} {rel} had a minor stroke in {year}, and the weakness resolved.",
            "{Poss} {rel} had a TIA years ago.",
            "{Poss} {rel} recovered fully from a stroke years ago.",
        ],
    },
    "chf": {
        "generic": [
            "Jugular venous pressure not raised.",
            "Heart size normal on chest radiograph.",
            "Recent echocardiogram normal.",
            "Takes no diuretics.",
            "Heart sounds without a gallop.",
            "Sleeps flat on one pillow.",
        ],
        "present": [
            "Heart failure with reduced ejection fraction.",
            "Chronic heart failure (NYHA class II).",
            "Breathless on mild exertion because of heart failure.",
            "Heart failure, under regular review in a cardiology clinic.",
            "Has heart failure, treated with diuretics.",
            "Current heart failure with ankle swelling.",
        ],
        "past": [
            "Heart failure in {year} after viral myocarditis, resolved.",
            "Previously had heart failure from a thyroid problem in {year}, resolved with treatment.",
            "Heart failure during sepsis in {year}, resolved as the infection cleared.",
            "Previously treated for heart failure, which resolved; heart function is normal on follow-up.",
            "Had heart failure years ago from severe anemia; it recovered fully once the anemia was corrected.",
            "Formerly had heart failure from stress cardiomyopathy; recovered fully in {year} and off all heart medicines since.",
        ],
        "absent": [
            "No history of heart failure.",
            "Denies heart failure at any time.",
            "No heart failure, past or present.",
            "Not affected by heart failure at any point in life.",
            "Has never had heart failure.",
            "Heart failure: never diagnosed.",
        ],
        "rel": [
            "{Poss} {rel} has heart failure.",
            "{Poss} {rel} lives with chronic heart failure.",
            "{Poss} {rel} attends a heart failure clinic.",
            "{Poss} {rel} was admitted this morning with heart failure.",
            "{Poss} {rel} is treated for heart failure.",
            "{Poss} {rel} has advanced heart failure.",
        ],
        "rel_past": [
            "{Poss} {rel} had heart failure in {year}.",
            "{Poss} {rel} previously took diuretics for heart failure.",
            "{Poss} {rel} had heart failure from a viral infection in {year}; it resolved.",
            "{Poss} {rel} stopped heart failure medicines in {year} once heart function returned to normal.",
            "{Poss} {rel} recovered from heart failure in {year}.",
            "{Poss} {rel} had heart failure long ago and made a full recovery.",
        ],
    },
    "diabetes": {
        "generic": [
            "Fasting glucose normal on today's blood tests.",
            "No excessive thirst or urination.",
            "Urine dipstick shows no sugar.",
            "Takes no medicines to lower blood sugar.",
            "HbA1c 5.3% at a routine check.",
            "Random glucose 92 mg/dL.",
        ],
        "present": [
            "Type 2 diabetes, diet-controlled.",
            "Diabetes mellitus type 1.",
            "Type 2 diabetes, with an HbA1c of 7.9% today.",
            "Diabetic; tests blood sugar at home twice a day.",
            "Has type 2 diabetes on metformin.",
            "Insulin-treated diabetes.",
        ],
        "past": [
            "Type 2 diabetes diagnosed in {year}, resolved after weight loss.",
            "Previously had type 2 diabetes ({year}); resolved after bariatric surgery.",
            "Steroid-induced diabetes in {year}, resolved once the steroids were stopped.",
            "Previously took metformin for type 2 diabetes; it was stopped when the diabetes resolved.",
            "Had diabetes years ago that went into remission on a low-calorie diet.",
            "Formerly diabetic; in remission since {year}.",
        ],
        "absent": [
            "No history of diabetes.",
            "Denies diabetes, past or present.",
            "No diabetes at any time.",
            "No diabetes; blood sugar has always been normal.",
            "Has never had diabetes.",
            "Never diagnosed with diabetes.",
        ],
        "rel": [
            "{Poss} {rel} has type 2 diabetes.",
            "{Poss} {rel} has diabetes treated with insulin.",
            "{Poss} {rel} takes metformin for diabetes.",
            "{Poss} {rel} has diabetes and wears a glucose monitor.",
            "{Poss} {rel} is diabetic.",
            "{Poss} {rel} lives with type 1 diabetes.",
        ],
        "rel_past": [
            "{Poss} {rel} had diabetes in {year}, resolved with weight loss.",
            "{Poss} {rel} previously took tablets for type 2 diabetes.",
            "{Poss} {rel} had steroid-induced diabetes in {year} that resolved when the steroids were stopped.",
            "{Poss} {rel} stopped diabetes treatment in {year} after the diabetes resolved.",
            "{Poss} {rel} had diabetes years ago that went away after a change in diet.",
            "{Poss} {rel} was diabetic until bariatric surgery several years ago.",
        ],
    },
    "vascular": {
        "generic": [
            "Peripheral pulses palpable.",
            "Foot pulses easily felt.",
            "Troponin within the normal range.",
            "Toes warm, with brisk capillary refill.",
            "Walks without calf pain.",
            "Ankle-brachial index normal today.",
        ],
        "present": [
            "Peripheral artery disease with calf claudication.",
            "Has peripheral artery disease.",
            "Myocardial infarction confirmed by troponin and ECG today.",
            "Peripheral artery disease, on cilostazol for pain on walking.",
            "Admitted with a myocardial infarction this week.",
            "Has symptomatic peripheral artery disease of both legs.",
        ],
        "past": [
            "Myocardial infarction in {year}, treated with a stent.",
            "Previously had a myocardial infarction, in {year}.",
            "Myocardial infarction in {year}; completed cardiac rehabilitation and has had no symptoms since.",
            "Peripheral artery disease in {year}, with leg pain that resolved after an artery stent.",
            "Heart attack years ago, with full recovery.",
            "Recovered from a heart attack in {year}.",
        ],
        "absent": [
            "No history of myocardial infarction or peripheral artery disease.",
            "Denies ever having had a myocardial infarction or peripheral artery disease.",
            "No myocardial infarction or peripheral artery disease at any time.",
            "Medical records show no myocardial infarction or peripheral artery disease, past or present.",
            "Has never had a heart attack or peripheral artery disease.",
            "Never diagnosed with a myocardial infarction or peripheral artery disease.",
        ],
        "rel": [
            "{Poss} {rel} has peripheral artery disease.",
            "{Poss} {rel} is being treated for a myocardial infarction this month.",
            "{Poss} {rel} had a myocardial infarction this morning.",
            "{Poss} {rel} takes cilostazol for peripheral artery disease.",
            "{Poss} {rel} is in the hospital with a heart attack.",
            "{Poss} {rel} has peripheral artery disease with leg pain.",
        ],
        "rel_past": [
            "{Poss} {rel} had a myocardial infarction in {year}.",
            "{Poss} {rel} previously underwent a stent procedure for a myocardial infarction.",
            "{Poss} {rel} completed cardiac rehabilitation after a myocardial infarction in {year}.",
            "{Poss} {rel} had peripheral artery disease in {year}, resolved after leg artery surgery.",
            "{Poss} {rel} had a heart attack years ago.",
            "{Poss} {rel} recovered from a heart attack earlier in life.",
        ],
    },
    "confusion": {
        "generic": [
            "Alert and attentive.",
            "Answers questions appropriately.",
            "Oriented to person, place and time.",
            "Memory and concentration normal on bedside testing.",
            "Speech clear; follows commands.",
            "Gives a clear account of the illness.",
        ],
        "present": [
            "New confusion since this morning.",
            "Acutely confused, per family.",
            "Confused on arrival, a sudden change from baseline.",
            "Acute confusional state at this assessment.",
            "Disoriented to time and place, which is new for the patient.",
            "Newly disoriented and unable to give a clear history.",
        ],
        "past": [
            "Brief confusion during a urinary infection in {year}, resolved.",
            "Previously confused during a fever in {year}.",
            "In {year}, became confused during a chest infection; the confusion resolved with antibiotics.",
            "Disorientation in {year} from a sleeping pill, which cleared once the pill was stopped.",
            "Was confused for a day after surgery years ago; recovered fully.",
            "Formerly had an episode of confusion with dehydration in {year}.",
        ],
        "absent": [
            "No confusion.",
            "Not confused or disoriented.",
            "No sign of confusion on arrival.",
            "No confusion, according to the nursing staff.",
            "Confusion absent; answers questions appropriately.",
            "Without any confusion on assessment.",
        ],
        "rel": [
            "{Poss} {rel} has new confusion.",
            "{Poss} {rel} is acutely confused.",
            "{Poss} {rel} has been confused since this morning.",
            "{Poss} {rel} has an acute confusional state.",
            "{Poss} {rel} has become disoriented this week.",
            "{Poss} {rel} is newly disoriented.",
        ],
    },
    "angioedema": {
        "generic": [
            "Lips and tongue normal in size at this assessment.",
            "Mouth and throat look normal; airway clear.",
            "No puffiness around the eyes or lips.",
            "Speaks and swallows normally, with no hoarseness.",
            "Face and neck without swelling on examination.",
            "Free of facial or oropharyngeal edema.",
        ],
        "present": [
            "Has hereditary angioedema, with attacks every few months.",
            "Idiopathic angioedema, treated with daily antihistamines.",
            "Angioedema of the lips this morning, still swollen at this assessment.",
            "Acquired angioedema, still causing attacks of swelling.",
            "Recurrent angioedema, under allergy follow-up.",
            "Lives with chronic angioedema that flares several times a year.",
        ],
        "past": [
            "Angioedema of the lips in {year}, resolved with treatment.",
            "Previously had angioedema of the tongue in {year}, which settled within hours.",
            "Angioedema after a wasp sting in {year}, which resolved within a day.",
            "Angioedema of the face in {year} that cleared after an injection of epinephrine.",
            "An episode of angioedema years ago, with full recovery.",
            "Formerly had recurrent angioedema, in remission for many years now.",
        ],
        "absent": [
            "No history of angioedema.",
            "Denies any episode of angioedema, past or present.",
            "No angioedema at any time.",
            "No angioedema in the past, and none at present.",
            "Has never had angioedema.",
            "Never diagnosed with angioedema.",
        ],
        "rel": [
            "{Poss} {rel} has recurrent angioedema.",
            "{Poss} {rel} has angioedema of the lips this week.",
            "{Poss} {rel} has swelling of the tongue from angioedema today.",
            "{Poss} {rel} has angioedema with frequent attacks.",
            "{Poss} {rel} is being treated for angioedema.",
            "{Poss} {rel} has active angioedema of the face.",
        ],
        "rel_past": [
            "{Poss} {rel} had angioedema in {year}.",
            "{Poss} {rel} was treated for angioedema in {year}; it resolved.",
            "{Poss} {rel} needed emergency care for angioedema in {year}.",
            "{Poss} {rel} previously had angioedema, which resolved.",
            "{Poss} {rel} had an attack of angioedema years ago.",
            "{Poss} {rel} recovered from an episode of angioedema in {year}.",
        ],
    },
    "asthma": {
        "generic": [
            "Chest clear on auscultation, with no wheeze.",
            "Takes no inhaled medicines.",
            "Good air entry on both sides of the chest.",
            "No night cough or chest tightness.",
            "Lungs clear, without wheeze or prolonged expiration.",
            "Inhaler use: none.",
        ],
        "present": [
            "Has asthma and uses an albuterol inhaler for wheeze.",
            "Asthmatic; wheezes on exertion and in cold air.",
            "Has asthma and wakes at night with wheeze.",
            "Asthma attack this month needing nebulizers; still wheezy at this assessment.",
            "Asthma, on a daily inhaled steroid.",
            "Persistent asthma, using a rescue inhaler most weeks.",
        ],
        "past": [
            "Childhood asthma, resolved by adolescence.",
            "Previously had asthma in childhood; symptom-free and off inhalers for decades.",
            "Occupational asthma in {year}, which resolved completely after a change of job.",
            "Asthma that began after a chest infection in {year} and resolved within a year.",
            "Asthma in the early school years, outgrown long ago.",
            "Formerly had asthma in elementary school; well for many years without inhalers.",
        ],
        "absent": [
            "Denies asthma.",
            "No diagnosis of asthma.",
            "Not asthmatic.",
            "No asthma or other airway disease.",
            "Has never had asthma.",
            "Asthma ruled out on lung function testing.",
        ],
        "rel": [
            "{Poss} {rel} has asthma.",
            "{Poss} {rel} is being treated for asthma.",
            "{Poss} {rel} has severe asthma.",
            "{Poss} {rel} has an asthma attack today.",
            "{Poss} {rel} uses an inhaler for asthma.",
            "{Poss} {rel} is asthmatic.",
        ],
    },
    "mech_valve": {
        "generic": [
            "No valve clicks on auscultation.",
            "Auscultation: irregular rhythm and no clicks.",
            "Not on anticoagulation at present.",
            "No ticking sound audible from the chest.",
            "Heart sounds irregular, without a metallic click.",
            "Irregularly irregular pulse; heart sounds free of clicks.",
        ],
        "present": [
            "Has a mechanical aortic valve.",
            "Mechanical heart valve in the mitral position.",
            "Mechanical aortic valve, functioning normally on echocardiography today.",
            "Carries a mechanical mitral valve, fitted for rheumatic heart disease.",
            "Mechanical mitral valve in place; metallic closing clicks audible.",
            "Lives with a mechanical aortic valve prosthesis.",
        ],
        "past": [
            "Mechanical aortic valve removed in {year} and replaced with a tissue valve.",
            "Previously had a mechanical mitral valve, replaced with a tissue valve after endocarditis in {year}.",
            "A mechanical aortic valve fitted in childhood was removed in {year} and replaced with a donor valve.",
            "In {year}, surgeons took out the patient's mechanical mitral valve and sewed in a pig-tissue valve.",
            "Formerly had a mechanical mitral valve, exchanged for a bioprosthetic valve in {year}.",
            "Mechanical aortic valve explanted years ago for valve thrombosis; a bioprosthesis now sits in its place.",
        ],
        "absent": [
            "No mechanical heart valve.",
            "Does not have a mechanical valve.",
            "No mechanical valve seen on echocardiography.",
            "Denies any mechanical heart valve.",
            "Has never had a mechanical heart valve.",
            "Never received a mechanical heart valve.",
        ],
        "rel": [
            "{Poss} {rel} has a mechanical heart valve.",
            "{Poss} {rel} has a mechanical mitral valve.",
            "{Poss} {rel} has a mechanical valve in the aortic position.",
            "{Poss} {rel} has a mechanical heart valve and needs regular clotting tests.",
            "{Poss} {rel} has an implanted mechanical aortic valve.",
            "{Poss} {rel} attends a valve clinic for a mechanical mitral valve.",
        ],
    },
    "hit": {
        "generic": [
            "No heparin given so far during this admission.",
            "No heparin products on the medication chart today.",
            "Not on any blood thinner at present.",
            "Heparin has not been started.",
            "Heparin exposure within the past 100 days: none.",
            "Last received heparin more than a year ago.",
        ],
        "present": [
            "Has heparin-induced thrombocytopenia, confirmed by antibody testing.",
            "Active heparin-induced thrombocytopenia with a positive functional assay.",
            "Heparin-induced thrombocytopenia diagnosed this week; all heparin is being avoided.",
            "On an argatroban infusion this morning for heparin-induced thrombocytopenia.",
            "Heparin-induced thrombocytopenia, with heparin antibodies still positive.",
            "Being treated for heparin-induced thrombocytopenia by the hematology team.",
        ],
        "past": [
            "Heparin-induced thrombocytopenia in {year}, resolved once heparin was stopped.",
            "Previously had heparin-induced thrombocytopenia, in {year}; antibodies since cleared.",
            "Heparin-induced thrombocytopenia in {year}, treated with argatroban and resolved within two weeks.",
            "Heparin-induced thrombocytopenia in {year} that resolved, with heparin avoided ever since.",
            "Heparin-induced thrombocytopenia after heart surgery years ago; recovered fully.",
            "Formerly had heparin-induced thrombocytopenia during a hospital stay in {year}; blood counts recovered afterward.",
        ],
        "absent": [
            "No history of heparin-induced thrombocytopenia.",
            "Denies ever having heparin-induced thrombocytopenia.",
            "No heparin-induced thrombocytopenia at any time.",
            "Heparin-induced thrombocytopenia: no episodes, past or present.",
            "Has never had heparin-induced thrombocytopenia.",
            "Never diagnosed with heparin-induced thrombocytopenia.",
        ],
        "rel": [
            "{Poss} {rel} has heparin-induced thrombocytopenia.",
            "{Poss} {rel} is being treated for heparin-induced thrombocytopenia.",
            "{Poss} {rel} has active heparin-induced thrombocytopenia.",
            "{Poss} {rel} was diagnosed with heparin-induced thrombocytopenia this week.",
            "{Poss} {rel} is in the hospital with heparin-induced thrombocytopenia.",
            "{Poss} {rel} has developed heparin-induced thrombocytopenia after surgery.",
        ],
        "rel_past": [
            "{Poss} {rel} had heparin-induced thrombocytopenia in {year}.",
            "{Poss} {rel} previously had heparin-induced thrombocytopenia after an operation.",
            "{Poss} {rel} needed treatment for heparin-induced thrombocytopenia in {year}.",
            "{Poss} {rel} had heparin-induced thrombocytopenia that resolved after heparin was stopped.",
            "{Poss} {rel} developed heparin-induced thrombocytopenia years ago.",
            "{Poss} {rel} recovered from heparin-induced thrombocytopenia in {year}.",
        ],
    },
    "crc": {
        "generic": [
            "No abdominal pain or blood in the stool.",
            "Abdomen soft, with no masses on examination.",
            "Weight stable and appetite good.",
            "Bowel habit regular.",
            "Rectal exam unremarkable.",
            "Hemoglobin within the normal range on recent blood tests.",
        ],
        "present": [
            "Has colon cancer and is receiving treatment from an oncologist.",
            "Bowel cancer, on treatment with an oncology team.",
            "Colorectal cancer diagnosed this month, awaiting surgery.",
            "Bowel cancer, midway through a course of chemotherapy.",
            "Colorectal cancer under active treatment.",
            "Lives with colon cancer and attends an oncology clinic.",
        ],
        "past": [
            "Colon cancer removed surgically in {year}; in remission since.",
            "Previously had colorectal cancer, treated in {year} and in remission.",
            "Colorectal cancer in {year}, treated with chemotherapy and radiation; scans clear since.",
            "Bowel cancer in {year}; all treatment completed and the patient was declared cancer-free.",
            "Bowel cancer cured by surgery years ago, without recurrence.",
            "Formerly had colon cancer; recovered fully after an operation in {year}.",
        ],
        "absent": [
            "No personal history of colorectal cancer.",
            "Denies ever having colon cancer.",
            "No bowel cancer at any time.",
            "No colon cancer, past or present.",
            "Has never had bowel cancer.",
            "Never diagnosed with colorectal cancer.",
        ],
        "rel": [
            "{Poss} {rel} has colon cancer.",
            "{Poss} {rel} is being treated for colorectal cancer.",
            "{Poss} {rel} was diagnosed with colon cancer this month.",
            "{Poss} {rel} has bowel cancer and starts chemotherapy this week.",
            "{Poss} {rel} is undergoing surgery for bowel cancer.",
            "{Poss} {rel} has advanced colorectal cancer.",
        ],
        "rel_past": [
            "{Poss} {rel} had colon cancer in {year}.",
            "{Poss} {rel} had surgery for colorectal cancer in {year}.",
            "{Poss} {rel} had part of the colon removed for bowel cancer in {year}.",
            "{Poss} {rel} completed radiation for colorectal cancer in {year}.",
            "{Poss} {rel} was treated for bowel cancer years ago.",
            "{Poss} {rel} recovered from colon cancer after an operation in {year}.",
        ],
    },
    "bleeding": {
        "generic": [
            "No melena or hematemesis.",
            "Hemoglobin normal on today's blood count.",
            "No hematuria or hemoptysis.",
            "Conjunctivae pink, with no pallor.",
            "Examination shows no signs of blood loss.",
            "Bowel habit normal, without any blood in the stool.",
        ],
        "present": [
            "Active major upper gastrointestinal bleed, requiring blood transfusion.",
            "Ongoing major bleeding from the lower bowel, receiving blood transfusion.",
            "Major retroperitoneal bleed seen on a CT scan this morning, needing urgent treatment.",
            "Vomiting large amounts of blood today from a major bleed in the esophagus.",
            "Currently has a major bleed from a duodenal ulcer, with transfusion under way.",
            "Major bleed from the stomach at present, with hemoglobin falling.",
        ],
        "past": [
            "Major gastrointestinal bleed in {year} needing transfusion, resolved with endoscopic treatment.",
            "Previously transfused for a major bleed from a stomach ulcer, which healed in {year}.",
            "Major bleed from a ruptured spleen in {year}, which stopped after emergency surgery.",
            "Major postoperative bleed from a knee wound in {year}, resolved with a repeat procedure.",
            "Major intracranial bleed after a fall years ago, with full recovery.",
            "Recovered from a major lower gastrointestinal bleed in {year} that required transfusion.",
        ],
        "absent": [
            "No history of major bleeding.",
            "Denies any major bleeding, past or present.",
            "Reports no major bleeding episodes, recent or remote.",
            "Bleeding history: no major bleeds.",
            "Has never had a major bleed.",
            "Medical records negative for major bleeding at any time.",
        ],
        "rel": [
            "{Poss} {rel} is hospitalized with a major gastrointestinal bleed.",
            "{Poss} {rel} has an active major bleed from a stomach ulcer.",
            "{Poss} {rel} is in intensive care today with a major brain bleed.",
            "{Poss} {rel} is in the emergency room with a major bleed from a deep cut.",
            "{Poss} {rel} is currently being transfused for a major bleed.",
            "{Poss} {rel} has major bleeding from the bowel at present.",
        ],
        "rel_past": [
            "{Poss} {rel} had a major gastrointestinal bleed in {year}.",
            "{Poss} {rel} previously had a major bleed from a stomach ulcer, which healed.",
            "{Poss} {rel} had a major bleed during an operation in {year}, which the surgeons controlled.",
            "{Poss} {rel} had a major bleed after a car crash; the bleeding stopped with treatment.",
            "{Poss} {rel} needed a blood transfusion for a major bleed years ago.",
            "{Poss} {rel} recovered from a major intracranial bleed in {year}.",
        ],
    },
    "cancer": {
        "generic": [
            "No active malignancy.",
            "No unexplained weight loss or new lumps.",
            "No evidence of active neoplasia.",
            "Not undergoing chemotherapy or radiotherapy.",
            "Malignant disease: none at present.",
            "Weight steady over the past year.",
        ],
        "present": [
            "Active colon cancer under oncology treatment.",
            "Non-Hodgkin lymphoma diagnosed this year, on active treatment.",
            "Takes oral targeted therapy for active chronic myeloid leukemia.",
            "Gastric carcinoma on chemotherapy ahead of planned surgery.",
            "Has metastatic lung cancer, receiving palliative treatment.",
            "Has melanoma skin cancer and is receiving treatment for it.",
        ],
        "past": [
            "Colon cancer removed surgically in {year}, in remission since.",
            "Previously treated for Hodgkin lymphoma, with treatment completed in {year}; remains in remission.",
            "Bladder cancer treated in {year}, with all follow-up checks clear.",
            "Completed chemotherapy for acute leukemia in {year}; still in remission.",
            "Had thyroid cancer years ago and is now cured.",
            "Formerly had kidney cancer, cured by surgery in {year}.",
        ],
        "absent": [
            "No history of cancer of any kind.",
            "Denies any cancer, past or present.",
            "No cancer, whether active or in remission.",
            "No leukemia, lymphoma or other cancer at any time.",
            "Has never had cancer.",
            "Free of cancer throughout life.",
        ],
        "rel": [
            "{Poss} {rel} has active colon cancer.",
            "{Poss} {rel} has lymphoma and is on active treatment.",
            "{Poss} {rel} has pancreatic cancer and began chemotherapy this week.",
            "{Poss} {rel} is hospitalized with advanced stomach cancer.",
            "{Poss} {rel} is being treated for leukemia.",
            "{Poss} {rel} has lung cancer that has spread to the liver.",
        ],
    },
    "exudate": {
        "generic": [
            "No pus or white patches on the tonsils.",
            "Throat mildly red; tonsils not coated.",
            "No membrane, film or spots seen over the tonsils.",
            "Nothing coating either tonsil.",
            "Tonsils pink and clean on inspection.",
            "Tonsils slightly red but clean, without pus.",
        ],
        "present": [
            "White exudate on both tonsils.",
            "Patchy exudate over the right tonsil.",
            "Creamy exudate in the tonsillar crypts today.",
            "Spots of exudate on the left tonsil.",
            "Tonsils swollen and coated with yellow exudate.",
            "Tonsillar exudate visible on both sides.",
        ],
        "past": [
            "Tonsillar exudate during tonsillitis in {year}, resolved with antibiotics.",
            "Previously had white exudate on the tonsils in {year}, since resolved.",
            "Mononucleosis in {year} caused tonsillar exudate that has since resolved.",
            "In {year}, exudate coated both tonsils and then resolved after a course of antibiotics.",
            "Had exudate on the tonsils with strep throat years ago, which cleared within days.",
            "Recovered fully from tonsillitis with exudate in {year}.",
        ],
        "absent": [
            "No tonsillar exudate.",
            "Exudate not seen on either tonsil.",
            "No exudate today, despite red and enlarged tonsils.",
            "There is no exudate over the tonsils this morning.",
            "Tonsils free of exudate.",
            "Tonsillar exudate absent on examination.",
        ],
        "rel": [
            "{Poss} {rel} has tonsillitis with white exudate on the tonsils.",
            "{Poss} {rel} has strep throat, with exudate on both tonsils.",
            "{Poss} {rel} is home sick, with thick exudate over both tonsils.",
            "{Poss} {rel}'s tonsils are coated with exudate this morning.",
            "{Poss} {rel} has a sore throat with tonsillar exudate.",
            "{Poss} {rel} currently has a throat infection with tonsillar exudate.",
        ],
    },
    "neck_nodes": {
        "generic": [
            "Neck soft and nontender.",
            "No tender swellings in the neck.",
            "No neck masses.",
            "Neck glands cannot be felt.",
            "Neck palpation unremarkable.",
            "Front of the neck without tenderness or swelling.",
        ],
        "present": [
            "Tender anterior cervical lymph nodes on both sides.",
            "Tender anterior cervical lymphadenopathy.",
            "The anterior cervical lymph nodes are tender today, more so on the right.",
            "A single tender anterior cervical lymph node on the left.",
            "Anterior cervical lymph nodes enlarged and tender to touch.",
            "Tender, swollen lymph nodes in the front of the neck.",
        ],
        "past": [
            "Tender anterior cervical lymph nodes during tonsillitis in {year}, since resolved.",
            "Previously had tender, swollen lymph nodes at the front of the neck in {year}, since resolved.",
            "During mononucleosis in {year}, the anterior cervical lymph nodes were tender; this resolved with rest.",
            "Pharyngitis in {year} with tender anterior cervical lymph nodes, both since resolved.",
            "Tender anterior cervical lymph nodes with a throat infection years ago, which went down within two weeks.",
            "Formerly had tender anterior cervical lymphadenopathy in {year}, with full recovery.",
        ],
        "absent": [
            "No tender anterior cervical lymph nodes.",
            "Anterior cervical lymph nodes not enlarged or tender.",
            "No tender anterior cervical lymphadenopathy today.",
            "The anterior cervical lymph nodes are small and not tender.",
            "Neck supple, without tender lymph nodes.",
            "Palpation of the neck negative for tender lymph nodes.",
        ],
        "rel": [
            "{Poss} {rel} has tender lymph nodes at the front of the neck.",
            "{Poss} {rel} has tender, swollen anterior cervical lymph nodes.",
            "{Poss} {rel}'s anterior cervical lymph nodes are tender this morning.",
            "{Poss} {rel} is seeing a doctor today about tender anterior cervical lymph nodes.",
            "{Poss} {rel} has a throat infection with tender anterior cervical lymph nodes.",
            "{Poss} {rel} currently has tender anterior cervical lymphadenopathy.",
        ],
    },
    "aspirin": {
        "generic": [
            "Takes no antiplatelet medicines.",
            "Not on any antiplatelet medication.",
            "No platelet-inhibiting drugs on the medication list.",
            "Takes no daily pill to stop platelets from clumping.",
            "Antiplatelet therapy: none at present.",
            "Current antiplatelet drugs: none.",
        ],
        "present": [
            "Takes aspirin 81 mg daily.",
            "Medication list: aspirin 81 mg, taken each morning.",
            "Takes one enteric-coated aspirin with breakfast every day.",
            "Active medications today include aspirin 81 mg once daily.",
            "Currently on low-dose aspirin for heart protection.",
            "Uses a daily aspirin on a cardiologist's recommendation.",
        ],
        "past": [
            "Took low-dose aspirin until {year}, when it was stopped on medical advice.",
            "Previously on aspirin 81 mg; stopped in {year} and not restarted.",
            "Aspirin was stopped at a medication review in {year}.",
            "Completed a six-week course of aspirin after ankle surgery in {year}.",
            "Formerly took a daily aspirin, discontinued years ago.",
            "Quit low-dose aspirin in {year} and has stayed off it since.",
        ],
        "absent": [
            "Denies any aspirin use.",
            "Not taking aspirin.",
            "Does not take aspirin or any product containing it.",
            "Reports no aspirin use, prescribed or over the counter.",
            "Has never taken aspirin.",
            "Medication history negative for aspirin.",
        ],
        "rel": [
            "{Poss} {rel} takes aspirin daily.",
            "{Poss} {rel} takes aspirin 81 mg every morning.",
            "{Poss} {rel} has taken aspirin every day for several years and still does.",
            "{Poss} {rel} keeps aspirin in a weekly pill organizer and takes it every evening.",
            "{Poss} {rel} is on low-dose aspirin.",
            "{Poss} {rel} uses a daily aspirin for heart protection.",
        ],
    },
    "egfr": {
        "current": [
            "eGFR today: {v} mL/min/1.73 m2.",
            "Renal function today: eGFR {v} mL/min/1.73 m2.",
            "eGFR {v} mL/min/1.73 m2 on today's labs.",
            "This morning's blood test shows an eGFR of {v} mL/min/1.73 m2.",
            "Current eGFR {v} mL/min/1.73 m2.",
            "eGFR now {v} mL/min/1.73 m2.",
        ],
        "past": [
            "eGFR {v} mL/min/1.73 m2 in {year} during acute kidney injury, resolved.",
            "eGFR {v} mL/min/1.73 m2 in {year} (dehydration).",
            "An eGFR of {v} mL/min/1.73 m2 was recorded in {year} with a severe kidney infection; kidney function returned to baseline after antibiotics.",
            "eGFR {v} mL/min/1.73 m2 in {year} after contrast dye for a CT scan; the kidney injury resolved within weeks.",
            "In {year}, eGFR fell to {v} mL/min/1.73 m2 during sepsis and later recovered.",
            "During an admission in {year}, eGFR was {v} mL/min/1.73 m2.",
        ],
        "superseded": [
            "eGFR was {v} mL/min/1.73 m2 yesterday, before rehydration.",
            "eGFR {v} mL/min/1.73 m2 yesterday during vomiting; repeated today.",
            "Yesterday's eGFR of {v} mL/min/1.73 m2 has been superseded by today's repeat.",
            "eGFR {v} mL/min/1.73 m2 on a sample drawn yesterday; today's result replaces it.",
            "Earlier this week eGFR was {v} mL/min/1.73 m2, while the patient was dehydrated.",
            "eGFR was {v} mL/min/1.73 m2 last month during a diarrheal illness.",
        ],
    },
    "platelets": {
        "current": [
            "Platelet count today: {v} x10^9/L.",
            "Platelets {v} x10^9/L on this morning's blood count.",
            "Complete blood count today: platelets {v} x10^9/L.",
            "Platelet count at this assessment: {v} x10^9/L.",
            "Current platelet count {v} x10^9/L.",
            "Platelet count now {v} x10^9/L.",
        ],
        "past": [
            "Platelet count {v} x10^9/L in {year} with severe sepsis, resolved after treatment.",
            "Platelet count {v} x10^9/L in {year} (dengue fever).",
            "A platelet count of {v} x10^9/L was recorded in {year} with malaria; the count returned to normal after treatment.",
            "Platelet count {v} x10^9/L in {year} from a tick-borne infection, back to normal once the infection resolved.",
            "In {year}, platelets fell to {v} x10^9/L during a viral illness and later recovered.",
            "During an illness in {year}, platelets were {v} x10^9/L.",
        ],
        "superseded": [
            "Platelet count was {v} x10^9/L yesterday (clumped sample).",
            "Platelets {v} x10^9/L yesterday, in a sample since repeated.",
            "A platelet count of {v} x10^9/L reported yesterday was superseded by today's repeat count.",
            "Platelets measured {v} x10^9/L on a sample drawn yesterday; today's recount replaced that result.",
            "Earlier this week, platelets were {v} x10^9/L in a tube that had clotted.",
            "Platelet count was {v} x10^9/L last month during an infection.",
        ],
    },
    "alt_enzyme": {
        "current": [
            "ALT today: {v} U/L.",
            "Liver tests today: ALT {v} U/L.",
            "ALT {v} U/L on today's labs.",
            "ALT on blood drawn this morning: {v} U/L.",
            "Current ALT {v} U/L.",
            "ALT now {v} U/L.",
        ],
        "past": [
            "ALT {v} U/L in {year} during hepatitis A, resolved.",
            "ALT {v} U/L in {year} (drug reaction).",
            "An ALT of {v} U/L was recorded in {year} with a liver abscess; liver tests returned to normal after treatment.",
            "ALT {v} U/L in {year} while a gallstone blocked the bile duct; it normalized after the stone was removed.",
            "In {year}, ALT rose to {v} U/L during a viral illness and later recovered.",
            "During an illness in {year}, ALT was {v} U/L.",
        ],
        "superseded": [
            "ALT was {v} U/L yesterday, before a repeat test.",
            "ALT {v} U/L yesterday, an unexpected result that was repeated today.",
            "Yesterday's ALT of {v} U/L was rechecked, and today's result replaces it.",
            "ALT {v} U/L on yesterday's screening labs, replaced by today's repeat result.",
            "Earlier this week ALT was {v} U/L while the patient had a fever.",
            "ALT was {v} U/L last month during a viral illness.",
        ],
    },
    "bun": {
        "current": [
            "BUN {v} mg/dL this morning.",
            "BUN at this assessment: {v} mg/dL.",
            "Today's BUN is {v} mg/dL.",
            "BUN on today's chemistry panel: {v} mg/dL.",
            "Blood urea nitrogen now: {v} mg/dL.",
            "Blood urea nitrogen {v} mg/dL on the current labs.",
        ],
        "past": [
            "BUN {v} mg/dL in {year} during gastroenteritis, resolved.",
            "BUN {v} mg/dL in {year} (vomiting illness).",
            "BUN {v} mg/dL in {year} after a marathon in hot weather, back to normal within days.",
            "BUN measured {v} mg/dL in {year} on a high-dose prednisone course; it normalized once the course was completed.",
            "In {year}, blood urea nitrogen rose to {v} mg/dL with dehydration and later recovered.",
            "During an admission in {year}, blood urea nitrogen was {v} mg/dL.",
        ],
        "superseded": [
            "BUN was {v} mg/dL yesterday, before intravenous fluids.",
            "BUN {v} mg/dL yesterday, since repeated.",
            "BUN {v} mg/dL on yesterday's sample; today's chemistry panel supersedes it.",
            "A BUN of {v} mg/dL on blood work drawn yesterday was superseded by today's repeat.",
            "Earlier this week blood urea nitrogen was {v} mg/dL.",
            "Blood urea nitrogen was {v} mg/dL last month.",
        ],
    },
    "rr": {
        "current": [
            "Respiratory rate {v}/min this morning.",
            "Respiratory rate today: {v}/min.",
            "Respiratory rate {v}/min at this assessment.",
            "Respiratory rate, counted over a full minute today, is {v}/min.",
            "Current respiratory rate {v}/min.",
            "Observations now: respiratory rate {v}/min.",
        ],
        "past": [
            "Respiratory rate {v}/min during an asthma attack in {year}, resolved.",
            "Respiratory rate {v}/min in {year} (asthma exacerbation).",
            "Respiratory rate {v}/min in {year} with painful rib fractures, settling once the ribs had healed.",
            "A respiratory rate of {v}/min was recorded in {year} on a high-altitude trek; breathing returned to normal after descent.",
            "In {year}, respiratory rate reached {v}/min during a panic attack and later recovered.",
            "During an admission in {year}, respiratory rate was {v}/min.",
        ],
        "superseded": [
            "Respiratory rate was {v}/min yesterday evening, settled overnight.",
            "Respiratory rate {v}/min yesterday, rechecked this morning.",
            "Yesterday's respiratory rate of {v}/min has been superseded by today's count.",
            "Respiratory rate {v}/min when counted yesterday; today's count replaces it.",
            "Earlier this week respiratory rate was {v}/min during a coughing fit.",
            "Respiratory rate was {v}/min last month during an asthma flare.",
        ],
    },
    "sbp": {
        "current": [
            "Blood pressure {v}/{dia} mmHg this morning.",
            "Blood pressure today: {v}/{dia} mmHg.",
            "Systolic blood pressure {v} mmHg at this assessment.",
            "Manual cuff blood pressure today: {v}/{dia} mmHg.",
            "Current systolic blood pressure {v} mmHg.",
            "Observations now: blood pressure {v}/{dia} mmHg.",
        ],
        "past": [
            "Systolic blood pressure {v} mmHg in {year} during an acute illness, resolved.",
            "Systolic blood pressure {v} mmHg in {year} (emergency department visit).",
            "BP {v}/{dia} mmHg in {year} after knee surgery, back to normal before discharge.",
            "Systolic pressure {v} mmHg in {year} after a car accident, normal again within days.",
            "In {year}, systolic blood pressure measured {v} mmHg at an urgent-care visit and later recovered.",
            "During an admission in {year}, systolic blood pressure was {v} mmHg.",
        ],
        "superseded": [
            "Systolic blood pressure was {v} mmHg yesterday, before a repeat measurement.",
            "Blood pressure {v}/{dia} mmHg yesterday, rechecked this morning.",
            "Yesterday's BP of {v}/{dia} mmHg came from a faulty automated cuff; today's manual reading supersedes it.",
            "Systolic pressure {v} mmHg when measured yesterday; today's reading replaces it.",
            "Earlier this week systolic blood pressure was {v} mmHg.",
            "Systolic blood pressure was {v} mmHg last month at a pharmacy check.",
        ],
    },
    "age": {
        "current": [
            "Age today: {v} years.",
            "Age on arrival: {v} years.",
            "Age at this assessment: {v} years.",
            "Age {v} years, calculated today from the date of birth.",
            "Currently aged {v} years.",
            "Current age {v} years.",
        ],
    },
    "potassium": {
        "current": [
            "Serum potassium today: {v} mmol/L.",
            "Potassium {v} mmol/L on today's blood work.",
            "Labs this morning: potassium {v} mmol/L.",
            "Potassium measured at this assessment is {v} mmol/L.",
            "Current serum potassium {v} mmol/L.",
            "Latest potassium result: {v} mmol/L.",
        ],
        "past": [
            "Serum potassium {v} mmol/L in {year} during acute kidney injury, resolved.",
            "Potassium {v} mmol/L in {year} while taking potassium supplements, since stopped.",
            "Potassium {v} mmol/L in {year} during a trimethoprim course; it came back down when the course was completed.",
            "Serum potassium {v} mmol/L in {year} from a crush injury of the leg, resolved before hospital discharge.",
            "In {year}, potassium reached {v} mmol/L with sepsis; the patient recovered fully.",
            "Serum potassium of {v} mmol/L in {year} with severe dehydration; recovered after rehydration.",
        ],
        "superseded": [
            "Potassium was {v} mmol/L yesterday in a hemolyzed sample; repeated today.",
            "Serum potassium {v} mmol/L yesterday on a delayed sample, before today's fresh draw.",
            "Potassium {v} mmol/L yesterday on a sample taken after prolonged fist clenching; today's repeat sample replaces it.",
            "Potassium was {v} mmol/L two days before this assessment while on potassium supplements, which have been stopped; today's value supersedes it.",
            "Earlier this week, serum potassium measured {v} mmol/L, since rechecked.",
            "Potassium was {v} mmol/L last month during a kidney injury that has since settled.",
        ],
    },
    "creatinine": {
        "current": [
            "Serum creatinine today: {v} mg/dL.",
            "Creatinine {v} mg/dL on this morning's labs.",
            "Kidney function today: creatinine {v} mg/dL.",
            "Blood panel at this assessment: creatinine {v} mg/dL.",
            "Current serum creatinine {v} mg/dL.",
            "Latest creatinine result: {v} mg/dL.",
        ],
        "past": [
            "Creatinine {v} mg/dL in {year} during acute kidney injury, resolved.",
            "Serum creatinine {v} mg/dL in {year} from muscle breakdown during a severe viral illness, since resolved.",
            "Serum creatinine {v} mg/dL in {year} during a kidney infection, normal again once the infection resolved.",
            "Creatinine {v} mg/dL in {year} on a gentamicin course, which was stopped; kidney tests normalized within weeks.",
            "In {year}, serum creatinine rose to {v} mg/dL with sepsis; renal function later recovered.",
            "Creatinine peaked at {v} mg/dL in {year} in the setting of severe vomiting, returning to baseline afterward.",
        ],
        "superseded": [
            "Creatinine was {v} mg/dL yesterday in a result later withdrawn by the laboratory; today's value replaces it.",
            "Serum creatinine {v} mg/dL yesterday, an unexpected result that was repeated today.",
            "Creatinine was {v} mg/dL two days before this assessment on an analyzer that was stopped for a calibration fault; today's value replaces it.",
            "Creatinine of {v} mg/dL yesterday was distorted by assay interference; today's laboratory level supersedes it.",
            "Earlier this week, serum creatinine was {v} mg/dL during a vomiting illness; it has improved since.",
            "Creatinine was {v} mg/dL last month after a contrast CT scan and has come down since.",
        ],
    },
    "wbc": {
        "current": [
            "White cell count today: {v} x10^9/L.",
            "WBC {v} x10^9/L on today's sample.",
            "Complete blood count this morning: white cell count {v} x10^9/L.",
            "WBC on the blood count drawn at this assessment: {v} x10^9/L.",
            "Current white cell count {v} x10^9/L.",
            "Latest WBC is {v} x10^9/L.",
        ],
        "past": [
            "White cell count {v} x10^9/L in {year} during a kidney infection, resolved on antibiotics.",
            "WBC {v} x10^9/L in {year} while on a course of prednisone, since completed.",
            "WBC {v} x10^9/L in {year} with a dental abscess; resolved once the abscess was drained.",
            "White cell count {v} x10^9/L in {year} during a bout of food poisoning that resolved within days.",
            "In {year}, WBC reached {v} x10^9/L with appendicitis; recovered after surgery.",
            "White cell count of {v} x10^9/L with cellulitis in {year}, later back to normal.",
        ],
        "superseded": [
            "White cell count {v} x10^9/L yesterday, an outlying result; repeated today.",
            "WBC was {v} x10^9/L yesterday, before today's repeat blood count.",
            "WBC of {v} x10^9/L was reported yesterday on a sample the laboratory flagged as unreliable; today's count replaces it.",
            "White cell count previously {v} x10^9/L on a blood test two days before this assessment; today's count supersedes it.",
            "Earlier this week, WBC was {v} x10^9/L; it has since been rechecked.",
            "White cell count was {v} x10^9/L last month during a urinary infection, since treated.",
        ],
    },
    "spo2": {
        "current": [
            "Oxygen saturation at this assessment is {v}%.",
            "Oxygen saturation {v}% at rest today.",
            "Pulse oximetry this morning: oxygen saturation {v}%.",
            "Oxygen saturation by finger probe today: {v}%.",
            "Current oxygen saturation {v}%.",
            "Latest oxygen saturation reading: {v}%.",
        ],
        "past": [
            "Oxygen saturation {v}% in {year} during pneumonia, resolved on treatment.",
            "Oxygen saturation {v}% in {year} while trekking at high altitude, resolved on descent.",
            "Oxygen saturation {v}% in {year} from a collapsed lung, which healed with chest drain treatment.",
            "Oxygen saturation {v}% in {year} during an allergic reaction to a bee sting, resolved within hours of treatment.",
            "In {year}, oxygen saturation fell to {v}% with a severe asthma attack; recovered fully.",
            "Oxygen saturation of {v}% in {year} with influenza, later back to normal.",
        ],
        "superseded": [
            "Oxygen saturation was {v}% yesterday during a brief choking episode on food; today's reading replaces it.",
            "Oxygen saturation {v}% yesterday evening after a coughing fit, before today's readings.",
            "Oxygen saturation read {v}% yesterday while the probe was slipping off a moving hand; today's steady reading replaces it.",
            "Oxygen saturation of {v}% yesterday came from a cold finger with a weak signal; today's measurement on a warmed hand replaces it.",
            "Earlier this week, oxygen saturation was {v}%; it has improved since.",
            "Oxygen saturation was {v}% last month during a chest infection that has since cleared.",
        ],
    },
    "temperature": {
        "current": [
            "Temperature today: {v} C.",
            "Oral temperature this morning: {v} C.",
            "Temperature {v} C at this assessment.",
            "Temperature checked with a digital thermometer today: {v} C.",
            "Current temperature {v} C.",
            "Temperature now {v} C (tympanic).",
        ],
        "past": [
            "Temperature {v} C in {year} during influenza, resolved within days.",
            "Temperature {v} C in {year} during tonsillitis, which resolved with antibiotics.",
            "Temperature {v} C in {year} during a bout of gastroenteritis that resolved within a week.",
            "Temperature {v} C in {year} during a middle ear infection, resolved once a course of antibiotics was completed.",
            "In {year}, temperature reached {v} C with a kidney infection that later cleared.",
            "Temperature peaked at {v} C with pneumonia in {year}; recovered fully.",
        ],
        "superseded": [
            "Temperature was {v} C yesterday evening and settled overnight.",
            "Temperature measured yesterday with a faulty thermometer: {v} C; repeated today.",
            "Temperature was {v} C yesterday afternoon during a short-lived fever that resolved with rest; today's reading replaces it.",
            "Temperature {v} C yesterday on a forehead strip thermometer; today's oral reading supersedes it.",
            "Earlier this week temperature reached {v} C at home; it has come down since.",
            "Temperature was {v} C last month with a urinary infection, since treated.",
        ],
    },
    "heart_rate": {
        "current": [
            "Heart rate today: {v}/min.",
            "Heart rate {v}/min at rest this morning.",
            "Pulse taken this morning: heart rate {v}/min.",
            "Heart rate counted over a full minute at this assessment: {v}/min.",
            "Current heart rate {v}/min.",
            "Heart rate now {v}/min on the monitor.",
        ],
        "past": [
            "Heart rate {v}/min in {year} during gastroenteritis with dehydration, resolved with fluids.",
            "Heart rate {v}/min in {year} during a panic attack, which resolved within the hour.",
            "Heart rate {v}/min in {year} from kidney stone pain, resolved once the stone passed.",
            "Heart rate {v}/min in {year} after several energy drinks, resolved within hours.",
            "In {year}, heart rate rose to {v}/min with an overactive thyroid; recovered fully on treatment.",
            "Heart rate reached {v}/min with appendicitis in {year}, later cured by surgery.",
        ],
        "superseded": [
            "Heart rate was {v}/min yesterday on a pulse reading distorted by movement; repeated today.",
            "Heart rate {v}/min yesterday evening during a bout of anxiety, settling overnight.",
            "Heart rate was {v}/min during a coughing fit yesterday; counted again at rest today.",
            "Heart rate previously {v}/min yesterday on an ECG trace spoiled by electrical interference; today's count supersedes it.",
            "Earlier this week heart rate was {v}/min on a fitness watch; a newer reading has replaced it.",
            "Heart rate was {v}/min last month with a stomach bug, and has slowed since.",
        ],
    },
    "weight": {
        "current": [
            "Weight today: {v} kg.",
            "Weighs {v} kg on the scale this morning.",
            "Weight {v} kg at this assessment.",
            "Weight checked today on a calibrated scale: {v} kg.",
            "Current weight {v} kg.",
            "Latest weight {v} kg.",
        ],
        "past": [
            "Weight {v} kg in {year} during a bout of severe depression; regained once the depression resolved.",
            "Weight {v} kg in {year} during a long hospital stay, regained within months.",
            "Weight {v} kg in {year} from tuberculosis, regained once treatment was completed.",
            "Weight {v} kg in {year} during a Crohn's disease flare; the weight was regained once the flare resolved.",
            "In {year}, weight fell to {v} kg after major bowel surgery and later recovered.",
            "While unwell with an overactive thyroid in {year}, weight was {v} kg; it later returned to normal.",
        ],
        "superseded": [
            "Weight was wrongly charted as {v} kg yesterday; measured on a scale today.",
            "Weight {v} kg yesterday on a chair scale that proved faulty; reweighed today.",
            "A placeholder weight of {v} kg was charted yesterday before the patient could be weighed; today's scale reading replaces it.",
            "Weight of {v} kg yesterday came from a scale with a failing battery; today's reading after a battery change replaces it.",
            "Earlier this week, weight read {v} kg because the scale had been zeroed with a load on it; the latest weighing corrects it.",
            "Weight on last month's referral letter was {v} kg, later found to be a typing error.",
        ],
    },
    "calf_swelling": {
        "current": [
            "Difference in calf circumference today, side to side: {v} cm.",
            "Calf circumference measured this morning is {v} cm greater on one side.",
            "Calf swelling at this assessment: {v} cm more than the opposite calf.",
            "Tape measurement today shows a calf circumference gap of {v} cm.",
            "Current calf swelling {v} cm compared with the other leg.",
            "Calf swelling now amounts to {v} cm of extra girth in the larger calf.",
        ],
        "past": [
            "Calf swelling of {v} cm in {year} during cellulitis of the leg, resolved with antibiotics.",
            "Calf swelling {v} cm in {year} from a torn calf muscle, which healed within weeks.",
            "Calf swelling {v} cm in {year} from an ankle fracture, resolved as the fracture healed.",
            "A large insect-bite reaction in {year} caused calf swelling of {v} cm, which resolved within days.",
            "In {year}, calf circumference differed by {v} cm between the legs from a ruptured knee cyst; it later returned to normal.",
            "After a sports injury in {year}, calf circumference was {v} cm larger on the injured leg; recovered fully.",
        ],
        "superseded": [
            "Calf swelling of {v} cm was measured yesterday at a nonstandard level; remeasured today.",
            "Calf circumference was wrongly transcribed as {v} cm greater on one side yesterday; amended today.",
            "Calf swelling of {v} cm was recorded yesterday with a stretched cloth tape; today's measurement with a new tape replaces it.",
            "Calf swelling previously recorded as {v} cm by a different examiner the evening before this assessment; today's measurement supersedes it.",
            "Earlier this week a rough bedside check put calf swelling at {v} cm; rechecked since.",
            "Calf swelling of {v} cm last month from a calf strain has gone down since.",
        ],
    },
}
