"""docs/ANALYSIS_B_S2.md from result files (STAGE2_TASKS_B B2, B3, B4 and the diversity carry-over). Every number is
read from results_git/<run>/summary_<set>.json; a missing file prints 'not run'.
  python scripts/analysis_b_s2.py > docs/ANALYSIS_B_S2.md"""
import glob, json, os, statistics
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RG = f"{ROOT}/results_git"
KINDS = ("numeric", "boundary", "subject", "negation", "time", "window", "class")
SETS = ("rule_v2/dev", "rule_v2/test_L2", "rule_v1/test_L2", "cls_v1/test", "xr_v1/test")
SYS = {"verdict x blocks": "B-V2-verdict-blocks-s{k}", "verdict x triplets": "B-V2-verdict-triplets-s{k}",
       "reader x triplets (own bit)": "B-V2-reader-triplets-s{k}"}
COMP = {v: "B-S2-{set}-ledger_rm_g-" + v + "-s{k}" for v in ("gate", "gate_struct", "reader_bit")}


def summ(run, set_name):
    p = f"{RG}/{run}/summary_{set_name.replace('/', '~')}.json"
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def val(s, key="TA", sub="all"):
    if s is None:
        return None
    if "all" not in s:                      # xr_v1: crossed accuracy
        return ((s.get("xr") or {}).get("conclusion") or {}).get("XA") if sub == "all" else None
    return (s.get(sub) or {}).get(key)


def cell(vals):
    v = [x for x in vals if x is not None]
    if not v:
        return "not run"
    return f"{statistics.mean(v):.1f}" + (f" +- {statistics.stdev(v):.1f}" if len(v) > 1 else "") + f" ({len(v)})"


def row(name, pattern, set_name, subs):
    runs = [pattern.format(k=k, set=set_name.replace("/", ".")) for k in range(5)]
    return f"| {name} | " + " | ".join(cell([val(summ(r, set_name), sub=s) for r in runs]) for s in subs) + " |"


def main():
    print("# Stage 2, role B: analyses\n")
    print("Generated by scripts/analysis_b_s2.py from results_git. Cells: mean +- s.d. over the seeds that are finished "
          "(number of seeds). TA = triplet accuracy; xr_v1 = crossed accuracy (XA). Ledger-RM-G = the stage-2 reader "
          "with the gate, the case-visible judge where a check is not computable, and the verdict-only fallback "
          "(scripts/assemble_rmg.py); gate_struct takes the constraints from the reference structure; reader_bit is the "
          "reader's own bit with the fallback for malformed records.\n")
    print("## 1. Systems trained on rule_v2, by set\n")
    print("| system | " + " | ".join(SETS) + " |\n|---|" + "---|" * len(SETS))
    for name, pat in SYS.items():
        print(f"| {name} | " + " | ".join(cell([val(summ(pat.format(k=k), s)) for k in range(5)]) for s in SETS) + " |")
    for v, pat in COMP.items():
        print(f"| Ledger-RM-G, {v} | " + " | ".join(
            cell([val(summ(pat.format(k=k, set=s.replace('/', '.')), s)) for k in range(5)]) for s in SETS) + " |")
    print("| reader x blocks, seed 0 | " + " | ".join(cell([val(summ("B-V2-reader-blocks-s0", s))]) for s in SETS) + " |")
    print("\n## 2. rule_v2/test_L2 by near-miss kind (TA)\n")
    subs = [f"nm_kind={k}" for k in KINDS]
    print("| system | " + " | ".join(KINDS) + " |\n|---|" + "---|" * len(KINDS))
    for name, pat in SYS.items():
        print(row(name, pat, "rule_v2/test_L2", subs))
    for v, pat in COMP.items():
        print(row(f"Ledger-RM-G, {v}", pat, "rule_v2/test_L2", subs))
    print("\n## 3. Leave one near-miss kind out (rule_v2/test_L2, triplets of the held-out kind, seed 0; with / without the kind in training)\n")
    print("| held-out kind | verdict with | verdict without | reader with | reader without |\n|---|---|---|---|---|")
    for k in ("window", "class"):
        g = lambda run: cell([val(summ(run, "rule_v2/test_L2"), sub=f"nm_kind={k}")])
        print(f"| {k} | {g('B-V2-verdict-triplets-s0')} | {g(f'B-V2-verdict-lo_{k}-s0')} | {g('B-V2-reader-triplets-s0')} | {g(f'B-V2-reader-lo_{k}-s0')} |")
    print("\n## 4. Validation of Ledger-RM-G on development sets (B3.2), per seed\n")
    print("| seed | rule_v2/dev composite | rule_v2/dev reader | rule_v1/dev composite | rule_v1/dev stage-1 ledger x triplets |\n|---|---|---|---|---|")
    cols = [[], [], [], []]
    for k in range(5):
        v = [val(summ(COMP["gate"].format(k=k, set="rule_v2.dev"), "rule_v2/dev")), val(summ(f"B-V2-reader-triplets-s{k}", "rule_v2/dev")),
             val(summ(COMP["gate"].format(k=k, set="rule_v1.dev"), "rule_v1/dev")), val(summ(f"B-F-ledger2-triplets-s{k}", "rule_v1/dev"))]
        for c, x in zip(cols, v):
            c.append(x)
        print(f"| {k} | " + " | ".join("not run" if x is None else f"{x:.2f}" for x in v) + " |")
    print("| mean | " + " | ".join(cell(c) for c in cols) + " |")
    print("\n## 5. Routes of the composite (share of items, seed 0)\n")
    print("| set | gate | reader_bit | judge_case | fallback_malformed | fallback_none |\n|---|---|---|---|---|---|")
    for s in ("rule_v2/dev",) + SETS[1:]:
        e = (summ(COMP["gate"].format(k=0, set=s.replace("/", ".")), s) or {}).get("eval")
        if e:
            n = sum(e["routes"].values())
            print(f"| {s} | " + " | ".join(f"{100 * e['routes'].get(r, 0) / n:.1f}" for r in
                                        ("gate", "reader_bit", "judge_case", "fallback_malformed", "fallback_none")) + " |")
    print("\n## 6. Gate on gold records of development sets (scripts/gate_dev.py)\n")
    print("| set | units | parser coverage | parser = struct | gate (struct) = program | gate (parsed) = program | linking top-1 | top-10 |\n|---|---|---|---|---|---|---|---|")
    for p in sorted(glob.glob(f"{RG}/B-S2-gate-dev/summary_*.json")):
        if "@" in p:
            continue
        s = json.load(open(p))
        f = lambda k: "-" if s.get(k) is None else f"{s[k]}"
        print(f"| {s['set']} | {s['units']} | {f('parser_coverage')} | {f('parser_precision_vs_struct')} | {f('gate_struct_agreement')} | "
              f"{f('agreement_on_parsed')} | {f('link_top1')} | {f('link_top10')} |")
    print("\n## 7. Adaptation arms (development figures: rule_v1/dev and mcv_v1/dev criterion claims; tests are C's)\n")
    print("| arm | rule_v1/dev TA | mcv_v1/dev TA | Rev | Hold |\n|---|---|---|---|---|")
    for arm in ("blocks", "triplets"):
        runs = [f"B-MIX-{arm}-s{k}" for k in range(3)]
        m = [((summ(r, "mcv_v1/dev") or {}).get("step") or {}).get("criterion") or {} for r in runs]
        print(f"| mix_{arm} | {cell([val(summ(r, 'rule_v1/dev')) for r in runs])} | " + " | ".join(cell([x.get(k) for x in m]) for k in ("TA", "Rev", "Hold")) + " |")
    print("\n## 8. Diversity curve (stage 1 carry-over; ledger on rule_v1, seed 0, rule_v1/test_L2 TA)\n")
    print("| corpus | TA | Rev | Hold |\n|---|---|---|---|")
    for d in sorted(glob.glob(f"{RG}/B-DIV-*-s0"), key=lambda x: (os.path.basename(x).split("-")[2], int(os.path.basename(x).split("-")[3]))):
        s = summ(os.path.basename(d), "rule_v1/test_L2")
        if s:
            print(f"| {os.path.basename(d)[6:-3]} | " + " | ".join(f"{s['all'][k]:.1f}" for k in ("TA", "Rev", "Hold")) + " |")


if __name__ == "__main__":
    main()
