"""Audit files and author sheets of the stage-2 sets, from their manifests and frozen records.

  python scripts/audit_stage2.py      # docs/DATA_AUDIT_mcv_v1.md, docs/DATA_AUDIT_kb_v1.md, audit/s2/*.csv|md

Sheets for H-S2-3: 100 edited MedCalc notes (audit/s2/mcv_edits_sheet.csv, with the notes in
audit/s2/mcv_edits_cases.md) and 20 rendered DDXPlus criteria (audit/s2/kb_criteria_sheet.md and .csv).
"""
import csv
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from selrm import kb_criterion as K  # noqa: E402
from selrm import mcv  # noqa: E402

SEED = 20261008


def h(*x):
    return hashlib.sha256("/".join(map(str, x)).encode()).hexdigest()


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    return "\n".join(out + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def load(path):
    return [json.loads(x) for x in open(path, encoding="utf-8")]


def mcv_audit():
    m = json.loads((ROOT / "data/mcv_v1/MANIFEST.json").read_text(encoding="utf-8"))
    acc = json.loads((ROOT / "results/A-MCV-ACCEPT/summary.json").read_text(encoding="utf-8"))
    specs = mcv.load_scores()
    P = m["portions"]
    L = ["# Data audit: mcv_v1 (MedCalc-V)", "",
         f"Generated by `python scripts/audit_stage2.py` from `data/mcv_v1/MANIFEST.json` (set created {m['created']}) and "
         "`results/A-MCV-ACCEPT/summary.json`. Every number below is read from those files.", "",
         "## Source", f"MedCalc-Bench Verified, {m['source']['repo']}, tag {m['source']['tag']}, commit `{m['source']['commit']}`, "
         f"{m['source']['licence']}. sha256 of both CSV files as pinned in STAGE2_SPEC. The repository's calculator code was not "
         "downloaded, read or executed; score specifications were written from the score text and worked explanations of the instances.", "",
         "## Acceptance of the score specifications",
         f"A score is accepted iff the sum of its item points over the released entity dictionary equals the answer on every "
         f"rule-based test and training row. Accepted: {acc['n_accepted']} of {acc['n_scores']}; test rows covered {acc['test_rows_covered']} "
         f"(human-written {acc['test_human_covered']}); training rows {acc['train_rows_covered']}.", "",
         table(["id", "score", "items", "test rows", "human-written", "training rows", "mismatches"],
               [[c, r["name"], len(specs[int(c)].items), r["test_rows"], r["test_human"], r["train_rows"],
                 r["test_mismatch"] + r["train_mismatch"]] for c, r in sorted(acc["scores"].items(), key=lambda x: int(x[0]))]), "",
         "### Conventions taken from the instance text", ""]
    for cid, s in sorted(specs.items()):
        for c in s.conventions:
            L.append(f"- {s.name}: {c}")
    L += ["", "Conventions that rest on few rows are listed in `docs/DECISIONS_A.md` (8 Oct): APACHE II rounding of the mean "
          "arterial pressure (one row), its +2 for creatinine 1.5 to <2.0 without renal failure (8 rows), its 0 for a history flag "
          "without a surgery type (one row); SOFA's hypotension gate; Caprini's surgery type 'major'.", "",
          "## Portions", table(["portion", "records", "groups", "notes", "human-written groups", "model-written groups", "sha256"],
                               [[p, c["records"], c["groups"], c["notes"], c["by_note_type"].get("human", 0), c["by_note_type"].get("model", 0),
                                 c["sha256"][:16]] for p, c in P.items()]), "",
          "Groups by stratum (criteria_test): " + ", ".join(f"{k} {v}" for k, v in P["criteria_test"]["by_stratum"].items())
          + f". Items that score points: {P['criteria_test']['items_with_points']} of {P['criteria_test']['groups']}.", "",
          "Edits (edits_test) by type: " + ", ".join(f"{k} {v}" for k, v in P["edits_test"]["by_edit_type"].items())
          + "; by near-miss kind: " + ", ".join(f"{k} {v}" for k, v in P["edits_test"]["by_nm_kind"].items()) + ".", "",
          "### Groups by score", table(["score"] + list(P), [[f"c{c}"] + [P[p]["by_score"].get(f"c{c}", 0) for p in P] for c in m["scores_accepted"]]), "",
          "## Training notes", f"Dropped: {m['training_note_drops']}. Development notes (20% by note id): {m['dev_notes']}. "
          f"Scores held out of both adaptation corpora (seed {m['seed']}): {m['scores_held_out_of_adaptation']}.", "",
          "## Items skipped, by reason", ""]
    for part, sk in m["skips"].items():
        for kind, d in sk.items():
            L.append(f"- {part}, {kind}: " + "; ".join(f"{k}: {v}" for k, v in d.items()))
    f = m["fidelity"]
    L += ["", "## Fidelity filter", f"Extractors: {', '.join(f['extractors'])}; parameters {f['params']}. An edit triplet is kept only if both "
          "extractors read the edited value (value edits) or the inserted finding with its subject, status and time, and find nothing "
          "about it in the untouched note (sentence edits).",
          f"Test: kept {f['test']['kept']} of {f['test']['triplets']} (retention {f['test']['retention']}). "
          f"Dev: kept {f['dev']['kept']} of {f['dev']['triplets']} (retention {f['dev']['retention']}). Adaptation corpora: {f['adaptation']}. "
          f"Rejected triplets: {m['rejected_edits']['triplets']} in `{m['rejected_edits']['file']}`; every read is in `{f['verdicts']}`. "
          "These are model checks; the authors' reading of 100 edited notes is `audit/s2/mcv_edits_sheet.csv`.", "",
          "## Shortcut validation (test portions)",
          table(["scorer"] + sorted({k for v in m["shortcut_validation"].values() for k in v}),
                [[n] + [v.get(k, "") for k in sorted({k for v in m["shortcut_validation"].values() for k in v})]
                 for n, v in m["shortcut_validation"].items()]), "",
          "## Limits", "- " + m["note"],
          "- Value edits change one number; other statements of the note that depend on it (a second laboratory value, a described "
          "appearance) are not changed. The lexicon of words for values and the fidelity filter remove some such notes, not all.",
          "- Sentence edits come mostly from a few scores, because the notes of the other scores mention every item (table above).",
          "- A scorer that reads values but ignores subject, status and time solves every value edit; selectivity is tested by the "
          "sentence edits only."]
    (ROOT / "docs/DATA_AUDIT_mcv_v1.md").write_text("\n".join(L) + "\n", encoding="utf-8")


def mcv_sheet(n=100):
    recs = [r for r in load(ROOT / "data/mcv_v1/edits_test/records.jsonl") if r["claim_role"] == "s"]
    by = {}
    for r in recs:
        by.setdefault(r["tid"], {})[r["case_kind"]] = r
    strata = {}
    for tid, g in by.items():
        strata.setdefault((g["base"]["edit_type"], g["base"]["nm_kind"]), []).append(tid)
    for v in strata.values():
        v.sort(key=lambda t: h(SEED, "sheet", t))
    pick, i = [], 0
    while len(pick) < n:                                  # round-robin over (edit type, near-miss kind)
        for k in sorted(strata):
            if i < len(strata[k]) and len(pick) < n:
                pick.append((strata[k][i], "flip" if (len(pick) % 2 == 0) else "near"))
        i += 1
    d = ROOT / "audit/s2"
    d.mkdir(parents=True, exist_ok=True)
    md = ["# Edited MedCalc notes for the authors (H-S2-3)", "",
          "For each case: read the score definition, the original note and the edited note. Answer in `mcv_edits_sheet.csv`:",
          "q1 is the marked edit the only change (yes/no); q2 does the edited note state the edited fact (yes/no); "
          "q3 is the stated number of points right for the edited note under the score text (yes/no/unsure). Do not look up the score elsewhere.", ""]
    rows = []
    for k, (tid, ck) in enumerate(pick, 1):
        g = by[tid]
        r, b = g[ck], g["base"]
        m = r["meta"]
        what = (f"value of {m['input']} changed from {m['value']['base']} to {m['value'][ck]}" if r["edit_type"] == "value"
                else f"sentence inserted: \"{m['inserted'][ck]}\"")
        md += [f"## Case {k}", f"Edit: {what}", "", f"Item: {r['condition']}. Stated: this item scores {m['points']} point(s) for the edited note.", "",
               "**Score definition**", "", "```", r["rule_text"], "```", "", "**Original note**", "", b["case_text"], "", "**Edited note**", "", r["case_text"], ""]
        rows.append([k, tid, ck, r["edit_type"], r["nm_kind"], r["note_type"], r["condition"], m["points"], "", "", "", ""])
    (d / "mcv_edits_cases.md").write_text("\n".join(md), encoding="utf-8")
    with open(d / "mcv_edits_sheet.csv", "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["case", "tid", "case_kind", "edit_type", "near_miss_kind", "note_type", "item", "stated_points", "q1_only_change",
                    "q2_states_fact", "q3_points_right", "comment"])
        w.writerows(rows)


def kb_audit_and_sheet(n=20):
    m = json.loads((ROOT / "data/kb_v1/MANIFEST.json").read_text(encoding="utf-8"))
    sup = json.loads((ROOT / "data/kb_v1/SUPPORT.json").read_text(encoding="utf-8"))
    s, P = m["support_check"], m["portions"]
    low = sorted(sup["by_pair"], key=lambda r: r["share_decided_for_gold"])[:15]
    L = ["# Data audit: kb_v1 (criterion from the DDXPlus lists)", "",
         f"Generated by `python scripts/audit_stage2.py` from `data/kb_v1/MANIFEST.json` (created {m['created']}) and `data/kb_v1/SUPPORT.json`.", "",
         "## Source", f"{m['source']['source']}, {m['source']['licence']}. sha256: " + "; ".join(f"`{k}` {v[:16]}" for k, v in m["files_sha256"].items()) + ".",
         "49 conditions, 223 findings, 888 links (tests/test_kb_criterion.py checks the counts of the spec).", "",
         "## Criterion text", "`selrm.kb_criterion.render(A, B)`: the two names in alphabetical order; findings listed for the first only, "
         "the second only and both, by question text; then: *" + m["procedure"] + "* The text is the same for (A, B) and (B, A) and "
         "does not depend on a case or a label.", "",
         "## Support check (validation patients)",
         table(["quantity", "value"], [[k.replace("_", " "), v] for k, v in s.items()]), "",
         "The 15 label pairs with the lowest share decided for the gold diagnosis:",
         table(["gold", "trap", "MedEinst pairs", "patients", "own", "other", "undecided", "share own"],
               [[r["gold"], r["trap"], r["medeinst_pairs"], r["patients"], r["own"], r["other"], r["undecided"], r["share_decided_for_gold"]] for r in low]), "",
         "## Portions", table(["portion", "records", "groups", "patients", "pairs with triplets", "negation", "subject", "sha256"],
                              [[p, c["records"], c["groups"], c["patients"], f"{c['pairs_with_triplets']} of {c['pairs']}", c["by_nm_kind"].get("negation", 0),
                                c["by_nm_kind"].get("subject", 0), c["sha256"][:16]] for p, c in P.items()]), "",
         "Flips by the scope of the added question (test): " + ", ".join(f"{k} {v}" for k, v in P["triplets_test"]["flip_scope"].items()) + ".", "",
         "## Shortcut validation"]
    for p, v in m["shortcut_validation"].items():
        L += [f"{p}: " + "; ".join(f"{k} TA {x['all']['TA']} (Rev {x['all']['Rev']}, Hold {x['all']['Hold']})" for k, x in v.items()) + "."]
    L += ["", "## Limits", "- " + m["note"],
          "- DDXPlus patients are generated from the same knowledge base, so no unedited patient shows a finding outside the list of "
          "the own diagnosis; the support check measures the lists against their own generator, not against clinical practice.",
          "- By its authors' description the knowledge base guided the construction of MedEinst's trap cases; handing the lists to a "
          "model changes what that benchmark measures (Appendix E)."]
    (ROOT / "docs/DATA_AUDIT_kb_v1.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    pairs = json.loads((ROOT / "data/kb_v1/medeinst_pairs.json").read_text(encoding="utf-8"))["pairs"]
    pick = sorted(pairs, key=lambda p: h(SEED, "kb-sheet", p[0], p[1]))[:n]
    d = ROOT / "audit/s2"
    d.mkdir(parents=True, exist_ok=True)
    md = ["# Rendered DDXPlus criteria for the authors (H-S2-3)", "",
          "For each pair: q1 does the text name no diagnosis as the answer (yes/no); q2 are the three lists plausible as lists of "
          "findings for these diagnoses (yes/no/unsure); q3 is the procedure sentence the only decision rule in the text (yes/no). "
          "Answer in `kb_criteria_sheet.csv`.", ""]
    with open(d / "kb_criteria_sheet.csv", "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["case", "diagnosis_1", "diagnosis_2", "text_sha256", "q1_no_answer_named", "q2_lists_plausible", "q3_only_rule", "comment"])
        for k, (a, b, _) in enumerate(pick, 1):
            x, y = sorted((a, b))
            md += [f"## Case {k}: {x} / {y}", "", "```", K.render(a, b), "```", ""]
            w.writerow([k, x, y, K.text_sha(a, b), "", "", "", ""])
    (d / "kb_criteria_sheet.md").write_text("\n".join(md), encoding="utf-8")


if __name__ == "__main__":
    mcv_audit()
    mcv_sheet()
    kb_audit_and_sheet()
    print("written: docs/DATA_AUDIT_mcv_v1.md, docs/DATA_AUDIT_kb_v1.md, audit/s2/")
