"""Audit of rule_v2 (STAGE2_TASKS_A, A5): docs/DATA_AUDIT_rule_v2.md and results/A-AUDIT-V2/summary.json.

  python scripts/audit_rule_v2.py

Checks: target-claim violations and shortcut validation (from the manifests); template and cue disjointness
of the stage-2 engine; case lines shared between the rule_v2 training corpora and every frozen test set on disk.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from selrm import engine2 as E  # noqa: E402
from selrm import phrases as P  # noqa: E402
from selrm import rules_grammar as RG  # noqa: E402
from selrm.mcv import edits as ME  # noqa: E402

SETS = ("dev", "test_L2", "train_blocks", "train_triplets", "train_triplets_lo_window", "train_triplets_lo_class")
TESTS = ("rule_v2/test_L2", "rule_v2/dev", "cls_v1/test", "cls_v1/dev", "rule_v1/test_L2", "xr_v1/test", "xp_v1/test")
KINDS = ("numeric", "boundary", "subject", "negation", "time", "window", "class")


def banks():
    out = {"visit": E.VISIT, **{f"event/{k}": v for k, v in E.EVENT_T.items()}, **{f"numeric/{k}": v for k, v in E.NUM_T.items()}}
    for d, b in E.CLASS_T.items():
        out.update({f"class/{d}/{k}": v for k, v in b.items()})
    return out


def cue_check():
    """Train-split templates of the stage-2 engine carry no rule_v1 test cue; test-split ones no training cue."""
    cues = {s: set(P.NEG_CUES[s]) | set(P.TIME_CUES[s]) for s in ("train", "test")}
    bad = []
    for name, bank in banks().items():
        for i, t in enumerate(bank):
            other = "test" if P.split_of(i) == "train" else "train"
            hit = [c for c in cues[other] if re.search(rf"\b{re.escape(c)}\b", t.lower())]
            if hit:
                bad.append(f"{name}[{i}] ({P.split_of(i)}): {hit}")
    shared = sorted({t for b in banks().values() for t in b} & set(ME.TEMPLATES.values()))
    return bad, shared


def lines(path):
    out = set()
    for ln in open(path, encoding="utf-8"):
        out.update(json.loads(ln)["case_text"].split("\n")[1:])       # without the header line
    return out


def table(head, rows):
    return "\n".join(["| " + " | ".join(head) + " |", "|" + "---|" * len(head)] + ["| " + " | ".join(map(str, r)) + " |" for r in rows])


def main():
    reg = json.loads((ROOT / "data/REGISTRY.json").read_text(encoding="utf-8"))
    man = {s: json.loads((ROOT / f"data/rule_v2/{s}/MANIFEST.json").read_text(encoding="utf-8")) for s in SETS}
    bad, shared_tpl = cue_check()
    from selrm.library import LIBRARY
    settings = {s[3] for s in RG.SCENARIOS} | {r.setting for r in LIBRARY}      # the first line of a case is its rule's setting
    train = lines(ROOT / "data/rule_v2/train_triplets/records.jsonl") | lines(ROOT / "data/rule_v2/train_blocks/records.jsonl")
    overlap = {}
    for name in TESTS:
        p = ROOT / "data" / reg[name]["path"]
        if not p.exists():
            overlap[name] = None
            continue
        both = (train & lines(p)) - settings
        dated = {x for x in both if re.search(r"\b20\d\d\b", x)}
        overlap[name] = {"shared_lines_outside_settings": len(both), "of_which_with_a_date_or_year": len(dated), "examples": sorted(both)[:5]}
    keep = ("records", "groups", "rules", "by_nm_kind", "by_part", "case_share", "target_claim_violations", "rejects", "sha256")
    out = {"run_id": "A-AUDIT-V2", "sets": {s: {k: m[k] for k in keep} for s, m in man.items()},
           "shortcut_validation": {s: man[s]["shortcut_validation"] for s in ("dev", "test_L2")},
           "cue_violations": bad, "templates_shared_with_mcv_v1": shared_tpl, "line_overlap_train_vs_frozen_tests": overlap,
           "held_out_v2_classes": man["test_L2"]["v2_part"]["held_out_for_test_L2"]}
    d = ROOT / "results/A-AUDIT-V2"
    d.mkdir(parents=True, exist_ok=True)
    (d / "summary.json").write_text(json.dumps(out, indent=1, sort_keys=True), encoding="utf-8")
    (d / "DONE").write_text("", encoding="utf-8")
    v2p = man["dev"]["v2_part"]
    L = ["# Data audit: rule_v2", "",
         "Generated by `python scripts/audit_rule_v2.py` from the manifests of `data/rule_v2/*` and the frozen records; numbers are in "
         "`results/A-AUDIT-V2/summary.json`.", "", "## Sets",
         table(["set", "records", "groups", "rules", "v1 part", "v2 part", "label violations", "rejected / proposed (v1; v2)"],
               [[s, m["records"], m["groups"], m["rules"], m["by_part"].get("v1", 0), m["by_part"].get("v2", 0), m["target_claim_violations"],
                 f"{m['rejects']['v1']['rejected']} / {m['rejects']['v1']['proposed']}; {m['rejects']['v2']['rejected']} / {m['rejects']['v2']['proposed']}"]
                for s, m in man.items()]), "", "Groups by near-miss kind:",
         table(["set"] + list(KINDS), [[s] + [m["by_nm_kind"].get(k, 0) for k in KINDS] for s, m in man.items()]), "",
         "Cases by kind (share): " + "; ".join(f"{s}: " + ", ".join(f"{k} {v}" for k, v in sorted(m["case_share"].items())) for s, m in man.items()) + ".", "",
         "## Two parts", "- v1 part: " + man["dev"]["v1_part"] + ".",
         f"- v2 part: engine `selrm/engine2.py`; signature classes {', '.join(v2p['signature_classes'])}; held out for test_L2: "
         f"{', '.join(out['held_out_v2_classes'])}; {v2p['rules_per_class']} rules per class; class conditions over the training classes of onto_v1 only.", "",
         "## Target-claim check",
         "Every label of every record is re-executed from the stored state with the rule program (missing twins: both claims 0). Violations: "
         + ", ".join(f"{s} {m['target_claim_violations']}" for s, m in man.items()) + ".", "", "## Shortcut validation"]
    for s in ("dev", "test_L2"):
        v = man[s]["shortcut_validation"]
        L += [f"{s}: " + "; ".join(f"{k} TA {x['all']['TA']} (Rev {x['all']['Rev']}, Hold {x['all']['Hold']})" for k, x in v.items()) + ". "
              "Concept named, TA by near-miss kind: " + ", ".join(f"{k.split('=')[1]} {x['TA']}" for k, x in v["concept_named"].items() if "=" in k) + "."]
    L += ["", "## Templates and cues",
          f"Stage-2 engine templates whose split carries a cue of the other split: {len(bad)}" + (": " + "; ".join(bad) if bad else "") + ".",
          f"Templates shared with the mcv_v1 sentence templates: {len(shared_tpl)}.",
          "Case lines (header excluded, scenario settings excluded) shared between the rule_v2 training corpora and frozen test sets:",
          table(["test set", "shared lines", "of which dated", "examples"],
                [[k, "records not on disk" if v is None else v["shared_lines_outside_settings"], "" if v is None else v["of_which_with_a_date_or_year"],
                  "" if v is None else "; ".join(v["examples"])[:160]] for k, v in overlap.items()]), "", "## Limits",
          "- Window and class conditions come with simple notes: the base case never mentions the target concept, and flip and near-miss add one line.",
          "- Class membership is relative to the onto_v1 closure tables; rule_v2 uses the training classes only, cls_v1 the dev and test classes.",
          "- The v1 part reuses rule_v1's rules (fold 1) with new cases; rule_v2/test_L2 and rule_v1/test_L2 share those rules and no case."]
    (ROOT / "docs/DATA_AUDIT_rule_v2.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(json.dumps({"cue_violations": bad, "shared_templates": shared_tpl}, indent=1))
    for k, v in overlap.items():
        print(k, None if v is None else (v["shared_lines_outside_settings"], v["of_which_with_a_date_or_year"], v["examples"]))


if __name__ == "__main__":
    main()
