"""What the trained policies write, from their saved evaluation outputs (STAGE2_TASKS_D D5.3).

  python scripts/policy_analysis.py

Reads results_git/D-RL-<reward>-s<k>/eval_step{0,<final>}.jsonl (one line per held-out case: case_kind, gold,
answer, correct, text; the verdict is the rule program's) and writes
  results_git/D-RL-analysis/summary.json   per run and step: right / wrong / no answer by case kind, the
      correctness pattern of each triplet (base, flip, near), share of errors that are failures to hold (wrong
      on base or near) or to reverse (wrong on flip), length and number of written steps;
  audit/policy_outputs_<run>.md             50 final outputs of the Med-PRM-reward runs, random.Random(20261008).
No model is called.
"""
import collections
import glob
import json
import os
import random
import re
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RG = os.path.join(ROOT, "results_git")
SEED, N_SAMPLE = 20261008, 50


def load(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def group(tid):
    return tid  # eval rows of one triplet share the tid; case_kind tells them apart


def profile(rows):
    kinds = collections.defaultdict(collections.Counter)
    for r in rows:
        kinds[r["case_kind"]]["none" if r["answer"] is None else "right" if r["correct"] else "wrong"] += 1
    trip = collections.defaultdict(dict)
    for r in rows:
        trip[group(r["tid"])][r["case_kind"]] = bool(r["correct"])
    pat = collections.Counter("".join("+" if t.get(k) else "-" for k in ("base", "flip", "near"))
                              for t in trip.values() if len(t) == 3)
    err = [r for r in rows if not r["correct"]]
    hold = sum(r["case_kind"] in ("base", "near") for r in err)
    steps = [len(re.findall(r"(?m)^\s*\d+[.)]", r["text"])) for r in rows]
    return {"n_cases": len(rows), "n_triplets": sum(pat.values()),
            "by_kind": {k: dict(v) for k, v in sorted(kinds.items())},
            # pattern = correct (+) or not (-) on base, flip, near; '-+-' answers the flip's claim throughout
            "triplet_patterns": dict(pat.most_common()),
            "share_always_flip_claim": 100.0 * pat["-+-"] / max(1, sum(pat.values())),
            "share_always_base_claim": 100.0 * pat["+-+"] / max(1, sum(pat.values())),
            "errors": len(err),
            "errors_fail_to_hold_share": 100.0 * hold / len(err) if err else None,
            "errors_fail_to_reverse_share": 100.0 * (len(err) - hold) / len(err) if err else None,
            "no_answer_share": 100.0 * sum(r["answer"] is None for r in rows) / len(rows),
            "median_chars": statistics.median(len(r["text"]) for r in rows),
            "median_steps": statistics.median(steps), "one_step_share": 100.0 * sum(s <= 1 for s in steps) / len(rows)}


def main():
    out = {"run_id": "D-RL-analysis", "source": "eval_step*.jsonl of each run", "sample_seed": SEED, "runs": {}}
    for d in sorted(glob.glob(os.path.join(RG, "D-RL-*-s[0-9]"))):
        run = os.path.basename(d)
        steps = sorted(int(re.search(r"eval_step(\d+)", f).group(1)) for f in glob.glob(os.path.join(d, "eval_step*.jsonl")))
        if len(steps) < 2:
            continue
        final = load(os.path.join(d, f"eval_step{steps[-1]}.jsonl"))
        out["runs"][run] = {"start": profile(load(os.path.join(d, "eval_step0.jsonl"))),
                            "final_step": steps[-1], "final": profile(final)}
        if run.startswith("D-RL-stepcheck"):
            pick = random.Random(SEED).sample(sorted(final, key=lambda r: (r["tid"], r["case_kind"])), N_SAMPLE)
            lines = [f"# {N_SAMPLE} outputs of the policy trained against Med-PRM ({run}, step {steps[-1]})", "",
                     f"Sampled with random.Random({SEED}) from the {len(final)} held-out evaluation cases "
                     "(generated by scripts/policy_analysis.py; do not edit).", ""]
            for r in pick:
                lines += [f"## {r['tid']} / {r['case_kind']}: gold {r['gold']}, answered {r['answer']} "
                          f"({'right' if r['correct'] else 'wrong'})", "", "```", r["text"].strip(), "```", ""]
            open(os.path.join(ROOT, "audit", f"policy_outputs_{run}.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    od = os.path.join(RG, "D-RL-analysis")
    os.makedirs(od, exist_ok=True)
    json.dump(out, open(os.path.join(od, "summary.json"), "w", encoding="utf-8", newline="\n"), indent=1)
    open(os.path.join(od, "DONE"), "w").close()
    for run, v in out["runs"].items():
        f = v["final"]
        print(f"{run:28s} hold-errors {f['errors_fail_to_hold_share'] or 0:5.1f}%  always-flip {f['share_always_flip_claim']:5.1f}%  "
              f"always-base {f['share_always_base_claim']:5.1f}%  no answer {f['no_answer_share']:4.1f}%  one step {f['one_step_share']:5.1f}%  "
              f"chars {f['median_chars']:.0f}  {f['triplet_patterns']}")


if __name__ == "__main__":
    main()
