"""Role-B reports generated only from results_git/<run_id>/ files (no typed numbers).
  python scripts/report_b.py smoke   > docs/SMOKE_B_C0.md    # provisional, never tabled
  python scripts/report_b.py timing  > docs/TIMING_B_T0.md
"""
import csv, json, math, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from selrm.metrics import decisions, paired_diff

RG = f"{ROOT}/results_git"
FMTS = ("verdict", "rationale", "summary2", "value2", "ledger2")
NL = "\n"
SMOKE_SETS = {"smoke_v2/test_heldout_rules": "held-out rules migraine_cad, contra_vte, vte_platelets; held-out template 2",
              "smoke_v2/dev_seen_rules": "training rules, held-out template 2 (300 triplets)"}


def load(rid, name):
    p = f"{RG}/{rid}/{name}"
    return json.load(open(p)) if os.path.exists(p) else None


def smoke():
    runs = {c: f"B-C0-smoke-verdict-{c}-s0" for c in ("blocks", "triplets")}
    print("# B-C0 smoke comparison: verdict x blocks vs verdict x triplets (PROVISIONAL, never reported)" + NL)
    print("Generated by scripts/report_b.py from results_git/<run_id>/ summaries and scores. Smoke data "
          "(selrm/smoke.py: 11 pilot rules, short notes, no hard tiers) validates the pipeline only; these "
          "numbers never enter a table." + NL)
    metas = {c: load(r, "meta.json") for c, r in runs.items()}
    if not all(metas.values()):
        print("not run: " + ", ".join(r for c, r in runs.items() if not metas[c]))
        return
    for c, r in runs.items():
        m = metas[c]
        print(f"- {r}: {m['train']['steps']} steps (1 epoch, {m['train']['examples']} examples), train loss "
              f"{m['train']['train_loss']:.4f}, {m['gpu'].split(',')[0]}, GPU util mean {m.get('gpu_util_mean')}%, "
              f"wall {m['wall_seconds'] / 60:.1f} min")
    for set_name, what in SMOKE_SETS.items():
        sname = set_name.replace("/", "~")
        S = {c: load(r, f"summary_{sname}.json") for c, r in runs.items()}
        print(f"{NL}## {set_name} ({what}){NL}")
        if not all(S.values()):
            print("not run")
            continue
        keys = ["all"] + sorted(k for k in S["blocks"] if k.startswith("nm_kind="))
        print("| group | corpus | n | Rev | Hold | TA | PresHold | BaseAcc | Tie |")
        print("|---|---|---|---|---|---|---|---|---|")
        for k in keys:
            for c in runs:
                v = S[c].get(k)
                if v:
                    print(f"| {k} | {c} | {v['n']} | {v['Rev']:.1f} | {v['Hold']:.1f} | {v['TA']:.1f} | "
                          f"{v.get('PresHold', float('nan')):.1f} | {v['BaseAcc']:.1f} | {v['Tie']:.1f} |")
        print()
        for c in runs:
            print(f"- {c}: TA 95% CI (bootstrap over rules) {S[c].get('CI95', {}).get('TA')}")
        recs = [json.loads(l) for l in open(f"{ROOT}/data/{set_name}.jsonl")]
        T = {}
        for c, r in runs.items():
            u = {}
            for line in open(f"{RG}/{r}/scores_{sname}.jsonl"):
                row = json.loads(line)
                u[row["iid"]] = row["u"]
            T[c] = decisions(recs, [u[x["iid"]] for x in recs])
        print(f"{NL}Paired difference triplets - blocks (same triplets, bootstrap over rules):{NL}")
        for m in ("TA", "Rev", "Hold"):
            d, lo, hi = paired_diff(T["triplets"], T["blocks"], m)
            print(f"- {m}: {d:+.1f} [{lo:+.1f}, {hi:+.1f}]")
        st = {c: S[c].get("step", {}).get("criterion") for c in runs}
        if all(st.values()):
            print(NL + "Criterion-claim step metrics: " + "; ".join(
                f"{c} TA {st[c]['TA']:.1f} Rev {st[c]['Rev']:.1f} Hold {st[c]['Hold']:.1f}" for c in runs))


def phase_util(rid):
    """Mean GPU utilisation during training and during evaluation, split at the run.log line
    'trained ...' (gpu_util.csv and run.log both carry UTC timestamps)."""
    log, util = f"{RG}/{rid}/run.log", f"{RG}/{rid}/gpu_util.csv"
    if not (os.path.exists(log) and os.path.exists(util)):
        return None, None
    cut = next((l.split()[0] for l in open(log) if " trained " in l), None)
    rows = [(r["time"], float(r["utilization.gpu"])) for r in csv.DictReader(open(util))]
    mean = lambda v: round(sum(v) / len(v), 1) if v else None
    return mean([u for t, u in rows if cut and t <= cut]), mean([u for t, u in rows if cut and t > cut])


def timing():
    print("# B-T0 timing per format (200 training steps on smoke_v2/train_triplets + eval on "
          "smoke_v2/test_heldout_rules)" + NL)
    print("Generated by scripts/report_b.py from results_git/B-T0-*/meta.json, gpu_util.csv and run.log." + NL)
    cols = ["format", "GPU", "per-device x accum", "s/step", "tok/s", "peak GB", "GPU util mean", "p10",
            "5-min windows <40%", "util train / eval", "eval s", "gen tokens", "est h (60k ex, 1 epoch, train only)"]
    print("| " + " | ".join(cols) + " |")
    print("|" + "---|" * len(cols))
    extra = sorted(d for d in os.listdir(RG) if d.startswith("B-T0b-")) if os.path.isdir(RG) else []
    for rid in [f"B-T0-{f}" for f in FMTS] + extra:
        f = rid[len("B-T0-"):] if rid.startswith("B-T0-") else rid
        m = load(rid, "meta.json")
        if not m:
            print(f"| {f} | not run |" + " |" * (len(cols) - 2))
            continue
        t = m["train"]
        steps60k = math.ceil(60000 / t["hp"]["batch"])
        tr, ev = phase_util(rid)
        print(f"| {f} | {m['gpu'].split(',')[0]} | {m['per_device_batch']} x {m['grad_accum']} | {t['s_per_step']} | "
              f"{t['tokens_per_s']} | {t['peak_mem_gb']} | {m.get('gpu_util_mean')} | {m.get('gpu_util_p10')} | "
              f"{m.get('gpu_windows_below40')} | {tr} / {ev} | {m['eval_seconds']} | {m.get('eval_generated_tokens')} | "
              f"{t['s_per_step'] * steps60k / 3600:.2f} |")


CORPORA = ("natural", "balanced", "blocks", "triplets")
LADDER = ("dev", "test_L0", "test_L1", "test_L2", "test_L3alt", "test_L3inv", "test_hard")
DATA = os.environ.get("SELRM_DATA", f"{ROOT}/scratch/rv1_local")   # A's layout: REGISTRY.json + rule_v1/<set>/records.jsonl


def records(name):
    reg = json.load(open(f"{DATA}/REGISTRY.json"))
    return [json.loads(l) for l in open(f"{DATA}/{reg[name]['path']}", encoding="utf-8")]


def mr(rid, test="rule_v1/missing", dev="rule_v1/dev_missing", fr=0.05):
    """Missing-input rejection (draft Sec. 4): share of missing cases whose two conclusion claims both
    score below the threshold that rejects fr of the supported (label 1) base/flip conclusion claims
    of the dev set. -> (MR %, n missing cases, threshold) or None."""
    paths = [f"{RG}/{rid}/scores_{s.replace('/', '~')}.jsonl" for s in (dev, test)]
    if not all(os.path.exists(p) for p in paths):
        return None
    ud, ut = ({r["iid"]: r["u"] for r in map(json.loads, open(p))} for p in paths)
    sup = sorted(ud[r["iid"]] for r in records(dev)
                 if r["claim_type"] == "conclusion" and r["case_kind"] != "missing" and r["label"] == 1)
    tau = sup[int(fr * len(sup))]
    both = {}
    for r in records(test):
        if r["claim_type"] == "conclusion" and r["case_kind"] == "missing":
            both.setdefault(r["tid"], []).append(ut[r["iid"]] < tau)
    vals = [all(v) for v in both.values() if len(v) == 2]
    return round(100.0 * sum(vals) / max(1, len(vals)), 1), len(vals), round(tau, 3)


def factorial(seed="0"):
    """One seed of the factorial on rule_v1 (provisional until all seeds are in)."""
    print(f"# B-F factorial on rule_v1, seed {seed} (PROVISIONAL: one seed; Table 3 reports 5)" + NL)
    print("Generated by scripts/report_b.py from results_git/B-F-*/ summaries (no typed numbers). "
          "\"not run\" = no DONE result in results_git yet." + NL)
    S = {(f, c): load(f"B-F-{f}-{c}-s{seed}", "summary_rule_v1~test_L2.json") for f in FMTS for c in CORPORA}
    print("## Triplet accuracy on rule_v1/test_L2 (95% CI, bootstrap over rules)" + NL)
    print("| format | " + " | ".join(CORPORA) + " |")
    print("|---|" + "---|" * len(CORPORA))
    for f in FMTS:
        cells = []
        for c in CORPORA:
            s = S[(f, c)]
            if not s or not s.get("all"):
                cells.append("not run")
                continue
            lo, hi = s.get("CI95", {}).get("TA", [float("nan")] * 2)
            cells.append(f"{s['all']['TA']:.1f} [{lo:.1f}, {hi:.1f}]")
        print(f"| {f} | " + " | ".join(cells) + " |")
    kinds = sorted({k.split("=", 1)[1] for s in S.values() if s for k in s if k.startswith("nm_kind=")})
    print(NL + "## rule_v1/test_L2 detail (MR on rule_v1/missing at 5% false rejection on dev_missing; "
          "TA by near-miss kind at the right)" + NL)
    print("| run | n | Rev | Hold | TA | PresHold | BaseAcc | Tie | MR | " + " | ".join(kinds) + " |")
    print("|---|" + "---|" * (8 + len(kinds)))
    for (f, c), s in S.items():
        if s and s.get("all"):
            a, m = s["all"], mr(f"B-F-{f}-{c}-s{seed}")
            print(f"| {f} x {c} | {a['n']} | {a['Rev']:.1f} | {a['Hold']:.1f} | {a['TA']:.1f} | "
                  f"{a.get('PresHold', float('nan')):.1f} | {a['BaseAcc']:.1f} | {a['Tie']:.1f} | "
                  f"{m[0] if m else '-'} | " +
                  " | ".join(f"{s[f'nm_kind={k}']['TA']:.1f}" if f"nm_kind={k}" in s else "-" for k in kinds) + " |")
    print(NL + "## Triplet accuracy on every ladder set" + NL)
    print("| run | " + " | ".join(LADDER) + " |")
    print("|---|" + "---|" * len(LADDER))
    for f in FMTS:
        for c in CORPORA:
            rid = f"B-F-{f}-{c}-s{seed}"
            if not os.path.exists(f"{RG}/{rid}/DONE"):
                continue
            row = []
            for st in LADDER:
                s = load(rid, f"summary_rule_v1~{st}.json")
                row.append(f"{s['all']['TA']:.1f}" if s and s.get("all") else "-")
            print(f"| {f} x {c} | " + " | ".join(row) + " |")
    print(NL + "Run facts (meta.json):" + NL)
    for f in FMTS:
        for c in CORPORA:
            m = load(f"B-F-{f}-{c}-s{seed}", "meta.json")
            if m:
                ev = load(f"B-F-{f}-{c}-s{seed}", "summary_rule_v1~test_L2.json") or {}
                print(f"- B-F-{f}-{c}-s{seed}: {m['train'].get('steps')} steps, train loss {m['train'].get('train_loss')}, "
                      f"{m['gpu'].split(',')[0]}, GPU util mean {m.get('gpu_util_mean')}%, {m.get('gpu_hours')} GPU-h; "
                      f"test_L2 malformed rate {ev.get('eval', {}).get('malformed_rate', '-')}")


def finished_rule_runs():
    """[(run_id, meta, {set: eval seconds})] for every finished rule_v1 training run in results_git."""
    out = []
    for d in sorted(os.listdir(RG)):
        m = load(d, "meta.json")
        if not (m and os.path.exists(f"{RG}/{d}/DONE") and str(m.get("corpus", "")).startswith("rule_v1")
                and m.get("train", {}).get("train_seconds")):
            continue
        per = {}
        for s in m["eval_sets"]:
            summ = load(d, f"summary_{s.replace('/', '~')}.json")
            per[s.split("/", 1)[1]] = (summ or {}).get("eval", {}).get("seconds")
        out.append((d, m, per))
    return out


def timesplit():
    """GPU-hours on training and on evaluation per finished rule_v1 run (meta.json), and evaluation seconds per
    set (summary_<set>.json eval.seconds). A resumed run reports its last attempt."""
    runs = finished_rule_runs()
    sets = sorted({s for _, _, per in runs for s in per})
    print("| run | GPU | train GPU-h | eval GPU-h | other GPU-h | total GPU-h | " + " | ".join(f"eval s {s}" for s in sets) + " |")
    print("|---|---|---|---|---|---|" + "---|" * len(sets))
    for rid, m, per in runs:
        tr, ev, wall = m["train"]["train_seconds"], m["eval_seconds"], m["wall_seconds"]
        print(f"| {rid} | {m['gpu'].split(',')[0]} | {tr / 3600:.2f} | {ev / 3600:.2f} | {(wall - tr - ev) / 3600:.2f} | "
              f"{wall / 3600:.2f} | " + " | ".join(f"{per[s]:.0f}" if per.get(s) is not None else "-" for s in sets) + " |")


# Projection model. Evaluation kind of each format: runs of one kind cost the same per evaluated record.
EVAL_KIND = {"verdict": "verdict", "verdict_bt": "verdict", "rationale": "rationale", "genprm": "genprm",
             "summary2": "summary2", "value2": "value2", "ledger2": "ledger2", "ledger2_dec": "ledger2",
             "dec_judge": "ledger2", "bit_reader": "ledger2", "ledger2_verify": "ledger2"}
SXM = "NVIDIA A100-SXM4-80GB"     # reference card: every rate is measured on it, capacity is converted to it


def kubectl_sh(cmd):
    import subprocess
    return subprocess.run(["kubectl", "-n", "ecepxie", "exec", "selrm-b-sync", "--", "sh", "-c", cmd],
                          capture_output=True, text=True).stdout


def pvc_runs():
    """{run_id: {owner, gpu, tok_s, sets {set: s}, done, claimed (unix), heartbeat (unix)}} for every run directory on
    the PVC (running or finished), plus the cluster time. GPU of a running run: its pod's node label."""
    import subprocess
    out = kubectl_sh(
        "cd /pvc/selrm/results && for d in */; do r=${d%/}; case $r in aborted-*) continue;; esac; "
        "echo \"RUN $r $(cut -d' ' -f1 $d/CLAIMED_B 2>/dev/null) $(stat -c %Y $d/CLAIMED_B 2>/dev/null || echo 0) "
        "$(stat -c %Y $d/HEARTBEAT 2>/dev/null || echo 0) $(test -f $d/DONE && echo 1 || echo 0)\"; "
        "grep -o '\"gpu\": \"[^,\"]*' $d/meta.json 2>/dev/null | head -1 | sed 's/^/GPU /'; "
        "grep -ho 'trained [0-9]* steps in [0-9.]* min, [0-9.]* tok/s' $d/run.log 2>/dev/null | tail -1 | sed 's/^/TRN /'; "
        "for s in $d/summary_*.json; do [ -f $s ] && echo \"SUM $(basename $s) "
        "$(tr -d '\\n ' < $s | grep -o '\"seconds\":[0-9.]*' | tail -1 | cut -d: -f2)\"; done; done; echo NOW $(date +%s)")
    runs, cur, now = {}, None, 0
    for line in out.splitlines():
        p = line.split()
        if not p:
            continue
        if p[0] == "RUN":
            owner = p[2] if len(p) == 6 else None
            claimed, hb, done = (int(x) for x in p[-3:])
            cur = runs[p[1]] = {"owner": owner, "gpu": None, "tok_s": None, "sets": {}, "done": done == 1,
                                "claimed": claimed, "heartbeat": hb}
        elif p[0] == "GPU" and cur is not None:
            cur["gpu"] = line.split('"gpu": "', 1)[1]
        elif p[0] == "TRN" and cur is not None:
            cur["tok_s"] = float(p[-2])
        elif p[0] == "SUM" and cur is not None and len(p) == 3 and p[2]:
            name = p[1][len("summary_"):-len(".json")].replace("~", "/")
            if not name.endswith(("/swap", "/edit")) and "~swap" not in p[1] and "~edit" not in p[1]:
                cur["sets"][name] = float(p[2])
        elif p[0] == "NOW":
            now = int(p[1])
    model = pod_models()                      # running runs: the GPU model of the claiming pod (Thanos DCGM label)
    for r in runs.values():
        if r["gpu"] is None and r["owner"] in model:
            r["gpu"] = model[r["owner"]]
    return runs, now


def thanos(expr):
    import urllib.parse, urllib.request
    return json.load(urllib.request.urlopen("https://thanos.nrp-nautilus.io/api/v1/query?" + urllib.parse.urlencode(
        {"query": expr}), timeout=60))["data"]["result"]


def pod_models():
    """{pod: GPU model name} for B's runner pods seen in the last day (namespace users cannot read nodes)."""
    res = thanos('last_over_time(DCGM_FI_DEV_GPU_UTIL{namespace="ecepxie",pod=~"selrm-b-run.*"}[1d])')
    return {r["metric"]["pod"]: r["metric"].get("modelName") for r in res}


def tokens_by_key():
    """{(tokenizer tag, train key): (tokens, completion tokens)} from the pre-tokenised sets on the PVC."""
    out = kubectl_sh("cd /pvc/selrm/tok && for f in */train/*/stats.json; do echo \"$f $(tr -d '\\n ' < $f | "
                     "grep -o '\"tokens\":[0-9]*\\|\"completion_tokens\":[0-9]*' | tr '\\n' ' ')\"; done")
    tok = {}
    for line in out.splitlines():
        p = line.split()
        if len(p) >= 3:
            vals = dict(x.strip('"').split('":') for x in p[1:] if '":' in x)
            parts = p[0].split("/")
            tok[(parts[0], parts[2])] = (int(vals.get("tokens", 0)), int(vals.get("completion_tokens", 0)))
    return tok


def gpus_by_model(hours=6):
    """{GPU model: mean count held by B's runner pods over the last hours (steps without any count as 0)}."""
    q = thanos
    sel = 'DCGM_FI_DEV_GPU_UTIL{namespace="ecepxie",pod=~"selrm-b-run.*"}'
    models = [r["metric"].get("modelName") for r in q(f"count by (modelName) (count_over_time({sel}[{hours}h]))")]
    out = {}
    for m in models:
        e = f'(count({sel[:-1]},modelName="{m}"}}) or vector(0))'
        res = q(f"avg_over_time({e}[{hours}h:5m])")
        out[m] = float(res[0]["value"][1]) if res else 0.0
    return out


def projection(freeze="2026-10-07T23:59:00Z"):
    """GPU-hours of the revised queue (queued + running + rows not yet queued), in A100-SXM4-80GB hours, against what
    B's runners deliver until the run freeze at the GPUs held over the last 6 hours (per GPU model, converted with
    measured speeds)."""
    import csv, datetime, glob, re
    import make_queue_b as Q
    reg = json.load(open(f"{ROOT}/scratch/registry_rule_v1.json"))
    nrec = {n: v["n_records"] for n, v in reg.items()}
    runs, now_ts = pvc_runs()
    tok = tokens_by_key()
    queued = {}
    for f in sorted(glob.glob(f"{ROOT}/configs/queues/**/*.json", recursive=True)):
        if not re.search(r"b_(smoke|t0b|val\d*)\.json$", f):
            for r in json.load(open(f))["runs"]:
                queued.setdefault(r["run_id"], r)
    fmt_of = {rid: r["format"] for rid, r in queued.items()}
    rule_runs = {rid for rid, r in queued.items() if any(s.startswith("rule_v1") for s in r["eval_sets"])}
    for d in os.listdir(RG):
        m = load(d, "meta.json")
        if m:
            fmt_of.setdefault(d, m.get("format"))
            if any(str(s).startswith("rule_v1") for s in m.get("eval_sets", [])):
                rule_runs.add(d)
    mean = lambda v: sum(v) / len(v) if v else None
    # rates on the reference card
    tps, spr, speed_obs = {}, {}, {}
    for rid, r in runs.items():
        f = fmt_of.get(rid)
        if not f or rid not in rule_runs:          # smoke runs (B-C0, B-T0) have other lengths
            continue
        k = EVAL_KIND.get(f, "ledger2")
        if rid.startswith(("C-TF", "B-AE")) or queued.get(rid, {}).get("train") is False:
            k = "verdict" if rid.startswith(("C-TF", "B-AE-oracle", "B-AE-field")) else k
        if r["tok_s"] and r["gpu"]:
            (tps.setdefault(f, []) if r["gpu"] == SXM else speed_obs.setdefault((r["gpu"], f), [])).append(r["tok_s"])
        if r["gpu"] == SXM:
            for s, sec in r["sets"].items():
                if s in nrec and nrec[s]:
                    spr.setdefault(k, []).append(sec / nrec[s])
    tps = {f: mean(v) for f, v in tps.items()}
    tps_all = mean(list(tps.values()))
    spr = {k: mean(v) for k, v in spr.items()}
    per_fmt = {(g, f): mean(vs) / tps[f] for (g, f), vs in speed_obs.items() if f in tps}
    speed = {g: mean([s for (gg, _), s in per_fmt.items() if gg == g]) for g in {g for g, _ in per_fmt}}
    t0 = {f: load(f"B-T0-{f}", "meta.json")["eval_seconds"] for f in FMTS}
    rel = {"summary2": t0["summary2"] / t0["ledger2"], "value2": t0["value2"] / t0["ledger2"],
           "rationale": t0["rationale"] / t0["ledger2"]}
    comp ={k: v[1] for (tag, k), v in tok.items() if tag == "unsloth--Qwen3.5-9B"}
    g_comp = [v for k, v in comp.items() if k.startswith("genprm__rule_v1~train_triplets__")]
    r_comp = [v for k, v in comp.items() if k.startswith("rationale__rule_v1~train_triplets__")]
    gen_ratio = g_comp[0] / r_comp[0] if g_comp and r_comp else None

    def kind_spr(k):
        if k in spr:
            return spr[k], "measured"
        if k == "genprm":
            base, how = kind_spr("rationale")
            return base * gen_ratio, f"rationale x {gen_ratio:.2f} ({how})"
        return spr["ledger2"] * rel[k], f"ledger2 x B-T0 {rel[k]:.2f}"

    notes = {}

    def eval_seconds(r):
        f = r["format"]
        k = EVAL_KIND.get(f, "ledger2")
        if r["run_id"].startswith(("C-TF", "B-AE-oracle", "B-AE-field")) or r.get("kind") == "concept":
            k = "verdict"
        v, how = kind_spr(k)
        notes[k] = how
        return sum(v * nrec.get(s, nrec["rule_v1/dev"]) for s in r["eval_sets"])

    def train_seconds(r):
        if r.get("train") is False or r.get("kind") == "concept":
            return 0.0
        tag = r.get("base_model", "unsloth/Qwen3.5-9B").replace("/", "--")
        pre = f"{r['format']}__{r['corpus'].replace('/', '~')}__n{r.get('n_examples') or 'all'}"
        hits = [v[0] for (t, k), v in tok.items() if t == tag and k.startswith(pre)]
        if not hits:
            hits = [v[0] for (t, k), v in tok.items() if t == "unsloth--Qwen3.5-9B" and k.startswith(
                f"{r['format']}__rule_v1~train_triplets__n60000")] or [13.1e6]
        return hits[0] / (tps.get(r["format"]) or tps_all)

    other = mean([m["wall_seconds"] - m["train"]["train_seconds"] - m["eval_seconds"]
                  for _, m, _ in finished_rule_runs() if m["gpu"].startswith(SXM)]) or 0.0
    rows = []
    for rid, r in queued.items():
        st = runs.get(rid)
        if st and st["done"]:
            continue
        est = (train_seconds(r) + eval_seconds(r) + other) / 3600
        state = "queued"
        if st and st["owner"] and now_ts - st["heartbeat"] < 900:
            state, est = "running", max(0.0, est - (now_ts - st["claimed"]) / 3600 * speed.get(st["gpu"], 1.0))
        rows.append((r["priority"], rid, state, est))
    extra = {}
    for gen in (lambda: Q.factorial({1, 2, 3, 4}, f"{ROOT}/scratch/registry_rule_v1.json", "rule_v1"),
                lambda: Q.transfer({0, 1, 2, 3, 4}, f"{ROOT}/scratch/registry_rule_v1.json", "rule_v1"),
                lambda: Q.backbones({0, 1, 2}, None, "rule_v1"),
                lambda: Q.extras({0, 1, 2}, f"{ROOT}/scratch/registry_rule_v1.json", "rule_v1")):
        for s in gen():
            extra.setdefault(s["run_id"], s)
    for r in csv.DictReader(open(f"{ROOT}/docs/RUN_MATRIX_B.csv", encoding="utf-8")):
        rid = r["run_id"]
        if rid in queued or r["status"] in ("done", "dropped") or r["runtime"] != "GPU" or (runs.get(rid) or {}).get("done"):
            continue
        seed = int(r["seed"]) if r["seed"].isdigit() else 0
        spec = extra.get(rid) or {"run_id": rid, "format": "ledger2", "corpus": "rule_v1/train_triplets",
                                  "n_examples": 60000, "train": r["kind"] != "eval",
                                  "eval_sets": [f"rule_v1/{s}" for s in (Q.TRANSFER if rid.startswith("B-TR") else Q.REDUCED)]}
        blocked = rid not in extra
        est = (train_seconds(spec) + eval_seconds(spec) + other) / 3600
        rows.append((Q.priority(rid, seed, r["priority"]), rid, "blocked" if blocked else "not queued", est))
    now = datetime.datetime.now(datetime.timezone.utc)
    left = (datetime.datetime.fromisoformat(freeze.replace("Z", "+00:00")) - now).total_seconds() / 3600
    held = gpus_by_model()
    cap_raw = sum(held.values()) * left
    cap = sum(c * speed.get(g, 1.0) for g, c in held.items()) * left
    print(f"Generated {now:%Y-%m-%d %H:%M} UTC by scripts/report_b.py projection. Hours are A100-SXM4-80GB hours: "
          "training = pre-tokenised tokens / tokens per second of the format, evaluation = seconds per evaluated record "
          "of the run's evaluation kind x records of each set, both measured on A100-SXM4-80GB runs of rule_v1 (finished "
          "or running; PVC run logs and summaries). Training tokens/s: " + ", ".join(f"{f} {v:.0f}" for f, v in sorted(tps.items())) +
          "; evaluation kinds: " + ", ".join(f"{k} {h}" for k, h in sorted(notes.items())) + "." + NL)
    print("Measured speed of other cards (training tokens/s relative to A100-SXM4-80GB, same format): " +
          (", ".join(f"{g} {s:.2f}" for g, s in sorted(speed.items())) or "none yet") + "; unmeasured cards count as 1.00." + NL)
    print(f"Capacity until {freeze} (UTC; the plan gives no time zone): {left:.1f} h x GPUs held by B's runners over the "
          "last 6 h (mean, steps without a GPU count as 0): " + ", ".join(f"{g} {c:.2f}" for g, c in sorted(held.items())) +
          f" = {cap_raw:.0f} GPU-h, {cap:.0f} A100-SXM4-80GB hours." + NL)
    print("| priority | group | runs | A100-80GB h | cumulative | fits |")
    print("|---|---|---|---|---|---|")
    groups = {}
    for p, rid, state, est in sorted(rows):
        g = re.sub(r"-s\d+$", "", rid)
        g = "B-F" if rid.startswith("B-F-") else "-".join(g.split("-")[:2])
        groups.setdefault((p, g, state), []).append(est)
    cum = 0.0
    for (p, g, state), v in sorted(groups.items()):
        cum += sum(v)
        print(f"| {p} | {g} ({state}) | {len(v)} | {sum(v):.1f} | {cum:.1f} | {'yes' if cum <= cap else 'no'} |")
    print(NL + f"Total {cum:.1f} A100-80GB hours for {len(rows)} runs (blocked rows wait for other roles' data); "
          f"capacity {cap:.0f} A100-80GB hours. Cut order if it does not fit (plan): B-DIV seeds 1-2, then B-DIV seed 0.")


if __name__ == "__main__":
    sys.stdout.reconfigure(newline="\n")          # reports are committed: LF on Windows too
    {"smoke": smoke, "timing": timing, "factorial": factorial, "timesplit": timesplit,
     "projection": projection}[sys.argv[1]](*sys.argv[2:])
