"""Role-B reports generated only from results_git/<run_id>/ files (no typed numbers).
  python scripts/report_b.py smoke   > docs/SMOKE_B_C0.md    # provisional, never tabled
  python scripts/report_b.py timing  > docs/TIMING_B_T0.md
"""
import csv, json, math, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from selrm.metrics import decisions, paired_diff

RG = f"{ROOT}/results_git"
FMTS = ("verdict", "rationale", "summary2", "value2", "ledger2")
NL = "\n"
SMOKE_SETS = {"smoke_v2/test_heldout_rules": "held-out rules migraine_cad, contra_vte, vte_platelets; held-out template 2",
              "smoke_v2/dev_seen_rules": "training rules, held-out template 2 (300 triplets)"}


def load(rid, name):
    p = f"{RG}/{rid}/{name}"
    return json.load(open(p)) if os.path.exists(p) else None


def smoke():
    runs = {c: f"B-C0-smoke-verdict-{c}-s0" for c in ("blocks", "triplets")}
    print("# B-C0 smoke comparison: verdict x blocks vs verdict x triplets (PROVISIONAL, never reported)" + NL)
    print("Generated by scripts/report_b.py from results_git/<run_id>/ summaries and scores. Smoke data "
          "(selrm/smoke.py: 11 pilot rules, short notes, no hard tiers) validates the pipeline only; these "
          "numbers never enter a table." + NL)
    metas = {c: load(r, "meta.json") for c, r in runs.items()}
    if not all(metas.values()):
        print("not run: " + ", ".join(r for c, r in runs.items() if not metas[c]))
        return
    for c, r in runs.items():
        m = metas[c]
        print(f"- {r}: {m['train']['steps']} steps (1 epoch, {m['train']['examples']} examples), train loss "
              f"{m['train']['train_loss']:.4f}, {m['gpu'].split(',')[0]}, GPU util mean {m.get('gpu_util_mean')}%, "
              f"wall {m['wall_seconds'] / 60:.1f} min")
    for set_name, what in SMOKE_SETS.items():
        sname = set_name.replace("/", "~")
        S = {c: load(r, f"summary_{sname}.json") for c, r in runs.items()}
        print(f"{NL}## {set_name} ({what}){NL}")
        if not all(S.values()):
            print("not run")
            continue
        keys = ["all"] + sorted(k for k in S["blocks"] if k.startswith("nm_kind="))
        print("| group | corpus | n | Rev | Hold | TA | PresHold | BaseAcc | Tie |")
        print("|---|---|---|---|---|---|---|---|---|")
        for k in keys:
            for c in runs:
                v = S[c].get(k)
                if v:
                    print(f"| {k} | {c} | {v['n']} | {v['Rev']:.1f} | {v['Hold']:.1f} | {v['TA']:.1f} | "
                          f"{v.get('PresHold', float('nan')):.1f} | {v['BaseAcc']:.1f} | {v['Tie']:.1f} |")
        print()
        for c in runs:
            print(f"- {c}: TA 95% CI (bootstrap over rules) {S[c].get('CI95', {}).get('TA')}")
        recs = [json.loads(l) for l in open(f"{ROOT}/data/{set_name}.jsonl")]
        T = {}
        for c, r in runs.items():
            u = {}
            for line in open(f"{RG}/{r}/scores_{sname}.jsonl"):
                row = json.loads(line)
                u[row["iid"]] = row["u"]
            T[c] = decisions(recs, [u[x["iid"]] for x in recs])
        print(f"{NL}Paired difference triplets - blocks (same triplets, bootstrap over rules):{NL}")
        for m in ("TA", "Rev", "Hold"):
            d, lo, hi = paired_diff(T["triplets"], T["blocks"], m)
            print(f"- {m}: {d:+.1f} [{lo:+.1f}, {hi:+.1f}]")
        st = {c: S[c].get("step", {}).get("criterion") for c in runs}
        if all(st.values()):
            print(NL + "Criterion-claim step metrics: " + "; ".join(
                f"{c} TA {st[c]['TA']:.1f} Rev {st[c]['Rev']:.1f} Hold {st[c]['Hold']:.1f}" for c in runs))


def phase_util(rid):
    """Mean GPU utilisation during training and during evaluation, split at the run.log line
    'trained ...' (gpu_util.csv and run.log both carry UTC timestamps)."""
    log, util = f"{RG}/{rid}/run.log", f"{RG}/{rid}/gpu_util.csv"
    if not (os.path.exists(log) and os.path.exists(util)):
        return None, None
    cut = next((l.split()[0] for l in open(log) if " trained " in l), None)
    rows = [(r["time"], float(r["utilization.gpu"])) for r in csv.DictReader(open(util))]
    mean = lambda v: round(sum(v) / len(v), 1) if v else None
    return mean([u for t, u in rows if cut and t <= cut]), mean([u for t, u in rows if cut and t > cut])


def timing():
    print("# B-T0 timing per format (200 training steps on smoke_v2/train_triplets + eval on "
          "smoke_v2/test_heldout_rules)" + NL)
    print("Generated by scripts/report_b.py from results_git/B-T0-*/meta.json, gpu_util.csv and run.log." + NL)
    cols = ["format", "GPU", "per-device x accum", "s/step", "tok/s", "peak GB", "GPU util mean", "p10",
            "5-min windows <40%", "util train / eval", "eval s", "gen tokens", "est h (60k ex, 1 epoch, train only)"]
    print("| " + " | ".join(cols) + " |")
    print("|" + "---|" * len(cols))
    extra = sorted(d for d in os.listdir(RG) if d.startswith("B-T0b-")) if os.path.isdir(RG) else []
    for rid in [f"B-T0-{f}" for f in FMTS] + extra:
        f = rid[len("B-T0-"):] if rid.startswith("B-T0-") else rid
        m = load(rid, "meta.json")
        if not m:
            print(f"| {f} | not run |" + " |" * (len(cols) - 2))
            continue
        t = m["train"]
        steps60k = math.ceil(60000 / t["hp"]["batch"])
        tr, ev = phase_util(rid)
        print(f"| {f} | {m['gpu'].split(',')[0]} | {m['per_device_batch']} x {m['grad_accum']} | {t['s_per_step']} | "
              f"{t['tokens_per_s']} | {t['peak_mem_gb']} | {m.get('gpu_util_mean')} | {m.get('gpu_util_p10')} | "
              f"{m.get('gpu_windows_below40')} | {tr} / {ev} | {m['eval_seconds']} | {m.get('eval_generated_tokens')} | "
              f"{t['s_per_step'] * steps60k / 3600:.2f} |")


CORPORA = ("natural", "balanced", "blocks", "triplets")
LADDER = ("dev", "test_L0", "test_L1", "test_L2", "test_L3alt", "test_L3inv", "test_hard")
DATA = os.environ.get("SELRM_DATA", f"{ROOT}/scratch/rv1_local")   # A's layout: REGISTRY.json + rule_v1/<set>/records.jsonl


def records(name):
    reg = json.load(open(f"{DATA}/REGISTRY.json"))
    return [json.loads(l) for l in open(f"{DATA}/{reg[name]['path']}", encoding="utf-8")]


def mr(rid, test="rule_v1/missing", dev="rule_v1/dev_missing", fr=0.05):
    """Missing-input rejection (draft Sec. 4): share of missing cases whose two conclusion claims both
    score below the threshold that rejects fr of the supported (label 1) base/flip conclusion claims
    of the dev set. -> (MR %, n missing cases, threshold) or None."""
    paths = [f"{RG}/{rid}/scores_{s.replace('/', '~')}.jsonl" for s in (dev, test)]
    if not all(os.path.exists(p) for p in paths):
        return None
    ud, ut = ({r["iid"]: r["u"] for r in map(json.loads, open(p))} for p in paths)
    sup = sorted(ud[r["iid"]] for r in records(dev)
                 if r["claim_type"] == "conclusion" and r["case_kind"] != "missing" and r["label"] == 1)
    tau = sup[int(fr * len(sup))]
    both = {}
    for r in records(test):
        if r["claim_type"] == "conclusion" and r["case_kind"] == "missing":
            both.setdefault(r["tid"], []).append(ut[r["iid"]] < tau)
    vals = [all(v) for v in both.values() if len(v) == 2]
    return round(100.0 * sum(vals) / max(1, len(vals)), 1), len(vals), round(tau, 3)


def factorial(seed="0"):
    """One seed of the factorial on rule_v1 (provisional until all seeds are in)."""
    print(f"# B-F factorial on rule_v1, seed {seed} (PROVISIONAL: one seed; Table 3 reports 5)" + NL)
    print("Generated by scripts/report_b.py from results_git/B-F-*/ summaries (no typed numbers). "
          "\"not run\" = no DONE result in results_git yet." + NL)
    S = {(f, c): load(f"B-F-{f}-{c}-s{seed}", "summary_rule_v1~test_L2.json") for f in FMTS for c in CORPORA}
    print("## Triplet accuracy on rule_v1/test_L2 (95% CI, bootstrap over rules)" + NL)
    print("| format | " + " | ".join(CORPORA) + " |")
    print("|---|" + "---|" * len(CORPORA))
    for f in FMTS:
        cells = []
        for c in CORPORA:
            s = S[(f, c)]
            if not s or not s.get("all"):
                cells.append("not run")
                continue
            lo, hi = s.get("CI95", {}).get("TA", [float("nan")] * 2)
            cells.append(f"{s['all']['TA']:.1f} [{lo:.1f}, {hi:.1f}]")
        print(f"| {f} | " + " | ".join(cells) + " |")
    kinds = sorted({k.split("=", 1)[1] for s in S.values() if s for k in s if k.startswith("nm_kind=")})
    print(NL + "## rule_v1/test_L2 detail (MR on rule_v1/missing at 5% false rejection on dev_missing; "
          "TA by near-miss kind at the right)" + NL)
    print("| run | n | Rev | Hold | TA | PresHold | BaseAcc | Tie | MR | " + " | ".join(kinds) + " |")
    print("|---|" + "---|" * (8 + len(kinds)))
    for (f, c), s in S.items():
        if s and s.get("all"):
            a, m = s["all"], mr(f"B-F-{f}-{c}-s{seed}")
            print(f"| {f} x {c} | {a['n']} | {a['Rev']:.1f} | {a['Hold']:.1f} | {a['TA']:.1f} | "
                  f"{a.get('PresHold', float('nan')):.1f} | {a['BaseAcc']:.1f} | {a['Tie']:.1f} | "
                  f"{m[0] if m else '-'} | " +
                  " | ".join(f"{s[f'nm_kind={k}']['TA']:.1f}" if f"nm_kind={k}" in s else "-" for k in kinds) + " |")
    print(NL + "## Triplet accuracy on every ladder set" + NL)
    print("| run | " + " | ".join(LADDER) + " |")
    print("|---|" + "---|" * len(LADDER))
    for f in FMTS:
        for c in CORPORA:
            rid = f"B-F-{f}-{c}-s{seed}"
            if not os.path.exists(f"{RG}/{rid}/DONE"):
                continue
            row = []
            for st in LADDER:
                s = load(rid, f"summary_rule_v1~{st}.json")
                row.append(f"{s['all']['TA']:.1f}" if s and s.get("all") else "-")
            print(f"| {f} x {c} | " + " | ".join(row) + " |")
    print(NL + "Run facts (meta.json):" + NL)
    for f in FMTS:
        for c in CORPORA:
            m = load(f"B-F-{f}-{c}-s{seed}", "meta.json")
            if m:
                ev = load(f"B-F-{f}-{c}-s{seed}", "summary_rule_v1~test_L2.json") or {}
                print(f"- B-F-{f}-{c}-s{seed}: {m['train'].get('steps')} steps, train loss {m['train'].get('train_loss')}, "
                      f"{m['gpu'].split(',')[0]}, GPU util mean {m.get('gpu_util_mean')}%, {m.get('gpu_hours')} GPU-h; "
                      f"test_L2 malformed rate {ev.get('eval', {}).get('malformed_rate', '-')}")


if __name__ == "__main__":
    sys.stdout.reconfigure(newline="\n")          # reports are committed: LF on Windows too
    {"smoke": smoke, "timing": timing, "factorial": factorial}[sys.argv[1]](*sys.argv[2:])
