"""docs/STAGE2_RESULTS.md from result files (no typed numbers). No GPU.   python scripts/stage2_report.py
Section 1 (C1, plan secondary 5): rule-tier controls. For every system: TA, Rev, Hold on rule_v1/test_L2 with the
rule (the stage-1 run), with the rule text removed (@none) and with another group's rule (@wrong); TA by rule source
(hand-written and sampled rules of L2; invented-name rules = rule_v1/test_L3inv). Seeds are averaged; labels are
always those of the generating rule. Writes results_git/C-S2-ctrl/summary.json too."""
import collections, json, os, statistics, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
from selrm import metrics as M

RES, BRES, DATA = f"{REPO}/results_git", f"{REPO}/scratch/bres", f"{REPO}/scratch/rv1"
ACODE = f"{REPO}/scratch/acode_s2/data"
SYSTEMS = [("critic", "Critic (untrained backbone)", ["critic"], [f"{RES}/C-TF-critic"]),
           *[(x, lab, [f"{x}-s{s}" for s in range(5)], [f"{BRES}/B-F-{x}-s{s}" for s in range(5)])
             for x, lab in (("verdict-blocks", "Verdict only, blocks"), ("verdict-triplets", "Verdict only, triplets"),
                            ("ledger2-triplets", "Ledger, triplets"))],
           ("summary2-triplets", "Summary, triplets", ["summary2-triplets-s0"], [f"{BRES}/B-F-summary2-triplets-s0"])]


def load(p):
    with open(p, encoding="utf-8") as f:
        return [json.loads(l) for l in f]


def scores(p):
    return {r["iid"]: r["u"] for r in load(p)} if os.path.exists(p) and os.path.getsize(p) else None


def cell(recs, u, suffix=""):
    """{TA, Rev, Hold, TA_hand, TA_sampled, n} of one run on one set (suffix '@none' / '@wrong' for views)."""
    T = M.decisions(recs, [u[r["iid"] + suffix] for r in recs])
    a = M.summarise(T)["all"]
    src = lambda t: "sampled" if t["rid"].startswith("gs") else "hand"
    by = collections.defaultdict(dict)
    for tid, t in T.items():
        by[src(t)][tid] = t
    return {k: a[k] for k in ("TA", "Rev", "Hold", "n")} | {f"TA_{k}": M.summarise(v)["all"]["TA"] for k, v in by.items()} | {
        f"n_{k}": len(v) for k, v in by.items()}


def changed(recs, ua, ub):
    """% of conclusion verdicts (sign of d on each case of each triplet) that differ between two score files."""
    A, B = (M.decisions(recs, [u[r["iid"]] for r in recs]) for u in (ua, ub))
    v = [(A[t]["d"][k] > 0) != (B[t]["d"][k] > 0) for t in A for k in A[t]["d"]]
    return 100 * sum(v) / len(v)


def mean(cells, k):
    v = [c[k] for c in cells if c and k in c]
    return statistics.mean(v) if v else None


def fmt(x):
    return "-" if x is None else f"{x:.1f}"


def main():
    sets = {s: load(f"{DATA}/rule_v1/{s}/records.jsonl") for s in ("test_L2", "test_L3inv")}
    out, L = {}, ["# Stage 2 results (role C; generated)", "",
                  "Generated by `scripts/stage2_report.py` from result files (no typed numbers).", "",
                  "## 1. Rule-tier controls (C1; analysis plan, secondary 5)", "",
                  "Triplet accuracy and its parts on `rule_v1/test_L2` with the stated rule, with the rule text removed and "
                  "with another group's rule (views built by `scripts/crit_views.py`; labels stay those of the generating "
                  "rule). L2 holds 20 hand-written and 83 sampled rules; invented-name rules are `rule_v1/test_L3inv`. "
                  "Means over the seeds listed; result files: `results_git/C-S2-ctrl-<system>/` and the stage-1 runs.", "",
                  "| System (seeds) | rule text | TA | Rev | Hold | TA hand-written | TA sampled | TA invented names (L3-inv) |",
                  "|---|---|---|---|---|---|---|---|"]
    for name, label, runs, base_dirs in SYSTEMS:
        out[name] = {}
        for cond, suffix in (("stated", ""), ("none", "@none"), ("wrong", "@wrong")):
            cells = {"test_L2": [], "test_L3inv": []}
            for run, bdir in zip(runs, base_dirs):
                for s in cells:
                    p = f"{bdir}/scores_rule_v1~{s}.jsonl" if cond == "stated" else f"{RES}/C-S2-ctrl-{run}/scores_rule_v1~{s}{suffix}.jsonl"
                    u = scores(p)
                    if u:
                        cells[s].append(cell(sets[s], u, suffix))
            l2, inv = cells["test_L2"], cells["test_L3inv"]
            out[name][cond] = {"seeds": len(l2), **{k: mean(l2, k) for k in ("TA", "Rev", "Hold", "TA_hand", "TA_sampled")},
                               "TA_invented": mean(inv, "TA"), "seeds_invented": len(inv),
                               "by_seed_TA": [c["TA"] for c in l2]}
            o = out[name][cond]
            L.append(f"| {label} ({o['seeds']}) | {cond} | " + (" | ".join(fmt(o[k]) for k in ("TA", "Rev", "Hold", "TA_hand", "TA_sampled", "TA_invented"))
                                                                  if o["seeds"] else "not run | | | | |") + " |")
    # ---- 1b. paraphrase tier (xp_v1: program-preserving paraphrases of the rule text, 300 triplets of test_L2)
    xp = load(f"{ACODE}/xp_v1/test/records.jsonl")
    tids = {r["tid"] for r in xp}
    orig = [r for r in sets["test_L2"] if r["tid"] in tids]
    L += ["", "### Paraphrased rule text (`xp_v1/test`)", "",
          f"The same {len(tids)} triplets of L2 with the original rule text and with a program-preserving paraphrase of it.", "",
          "Changed verdicts: % of conclusion verdicts (sign of d on the base, flip, near and pres case of each triplet) that "
          "differ from the stage-1 run on the original text, for the paraphrase and for a second run of the same original "
          "records (`xp_v1/orig_rerun`, runs `C-S2-xp0-<system>`); excess = paraphrase minus rerun.", "",
          "| System (seeds) | TA original | TA paraphrase | Rev paraphrase | Hold paraphrase | changed, paraphrase | changed, rerun | excess |",
          "|---|---|---|---|---|---|---|---|"]
    out_xp = {}
    for name, label, runs, base_dirs in SYSTEMS:
        a, b, ch = [], [], []
        for run, bdir in zip(runs, base_dirs):
            u0, u1 = scores(f"{bdir}/scores_rule_v1~test_L2.jsonl"), scores(f"{RES}/C-S2-xp-{run}/scores_xp_v1~test.jsonl")
            ur = scores(f"{RES}/C-S2-xp0-{run}/scores_xp_v1~orig_rerun.jsonl")
            if u0 and u1:
                a.append(cell(orig, u0)); b.append(cell(xp, u1))
            if u0 and u1 and ur:
                ch.append({"changed_rate_paraphrase": changed(orig, u0, u1), "changed_rate_rerun": changed(orig, u0, ur)})
        out_xp[name] = {"seeds": len(b), "TA_original": mean(a, "TA"), **{f"{k}_paraphrase": mean(b, k) for k in ("TA", "Rev", "Hold")},
                        "seeds_changed": len(ch), **{k: mean(ch, k) for k in ("changed_rate_paraphrase", "changed_rate_rerun")}}
        o = out_xp[name]
        o["excess_changed_rate"] = o["changed_rate_paraphrase"] - o["changed_rate_rerun"] if ch else None
        L.append(f"| {label} ({o['seeds']}) | " + " | ".join(fmt(o[k]) for k in (
            "TA_original", "TA_paraphrase", "Rev_paraphrase", "Hold_paraphrase", "changed_rate_paraphrase", "changed_rate_rerun", "excess_changed_rate")) + " |")
    # ---- 2. kb_v1 triplets (C4): derived criterion stated, removed, exclusive lists exchanged
    kb = load(f"{ACODE}/kb_v1/triplets_test/records.jsonl")
    L += ["", "## 2. Criterion derived from a knowledge base (`kb_v1/triplets_test`; C4)", "",
          "Triplets built from DDXPlus patients; the criterion is the pair of exclusive finding lists and their procedure. "
          "Conditions: criterion stated, removed, and with the two exclusive lists exchanged (labels stay those of the stated criterion).", "",
          "| System (seeds) | criterion | TA | Rev | Hold |", "|---|---|---|---|---|"]
    out_kb = {}
    for name, label, runs, _ in SYSTEMS[:3]:
        out_kb[name] = {}
        for cond, suffix in (("stated", ""), ("none", "@none"), ("wrong", "@wrong")):
            cells = []
            for run in runs:
                u = scores(f"{RES}/C-S2-kb-{run}/scores_kb_v1~triplets_test{suffix}.jsonl")
                if u:
                    T = M.decisions(kb, [u[r["iid"] + suffix] for r in kb])
                    cells.append({k: M.summarise(T)["all"][k] for k in ("TA", "Rev", "Hold")})
            out_kb[name][cond] = {"seeds": len(cells), **{k: mean(cells, k) for k in ("TA", "Rev", "Hold")}}
            o = out_kb[name][cond]
            L.append(f"| {label} ({o['seeds']}) | {cond} | " + " | ".join(fmt(o[k]) for k in ("TA", "Rev", "Hold")) + " |")
    os.makedirs(f"{RES}/C-S2-kb", exist_ok=True)
    json.dump({"run_id": "C-S2-kb", "set": "kb_v1/triplets_test and views", "systems": out_kb, "paraphrase_xp_v1": out_xp},
              open(f"{RES}/C-S2-kb/summary.json", "w", encoding="utf-8", newline="\n"), indent=1)
    os.makedirs(f"{RES}/C-S2-ctrl", exist_ok=True)
    json.dump({"run_id": "C-S2-ctrl", "set": "rule_v1/test_L2 and views", "systems": out},
              open(f"{RES}/C-S2-ctrl/summary.json", "w", encoding="utf-8", newline="\n"), indent=1)
    open(f"{REPO}/docs/STAGE2_RESULTS.md", "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L[-16:]))


if __name__ == "__main__":
    main()
