"""docs/STAGE2_RESULTS.md from result files (no typed numbers). No GPU.   python scripts/stage2_report.py
Section 1 (C1, plan secondary 5): rule-tier controls. For every system: TA, Rev, Hold on rule_v1/test_L2 with the
rule (the stage-1 run), with the rule text removed (@none) and with another group's rule (@wrong); TA by rule source
(hand-written and sampled rules of L2; invented-name rules = rule_v1/test_L3inv). Seeds are averaged; labels are
always those of the generating rule. Writes results_git/C-S2-ctrl/summary.json too."""
import collections, json, os, statistics, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
from selrm import metrics as M

RES, BRES, DATA = f"{REPO}/results_git", f"{REPO}/scratch/bres", f"{REPO}/scratch/rv1"
SYSTEMS = [("critic", "Critic (untrained backbone)", ["critic"], [f"{RES}/C-TF-critic"]),
           *[(x, lab, [f"{x}-s{s}" for s in range(5)], [f"{BRES}/B-F-{x}-s{s}" for s in range(5)])
             for x, lab in (("verdict-blocks", "Verdict only, blocks"), ("verdict-triplets", "Verdict only, triplets"),
                            ("ledger2-triplets", "Ledger, triplets"))],
           ("summary2-triplets", "Summary, triplets", ["summary2-triplets-s0"], [f"{BRES}/B-F-summary2-triplets-s0"])]


def load(p):
    with open(p, encoding="utf-8") as f:
        return [json.loads(l) for l in f]


def scores(p):
    return {r["iid"]: r["u"] for r in load(p)} if os.path.exists(p) and os.path.getsize(p) else None


def cell(recs, u, suffix=""):
    """{TA, Rev, Hold, TA_hand, TA_sampled, n} of one run on one set (suffix '@none' / '@wrong' for views)."""
    T = M.decisions(recs, [u[r["iid"] + suffix] for r in recs])
    a = M.summarise(T)["all"]
    src = lambda t: "sampled" if t["rid"].startswith("gs") else "hand"
    by = collections.defaultdict(dict)
    for tid, t in T.items():
        by[src(t)][tid] = t
    return {k: a[k] for k in ("TA", "Rev", "Hold", "n")} | {f"TA_{k}": M.summarise(v)["all"]["TA"] for k, v in by.items()} | {
        f"n_{k}": len(v) for k, v in by.items()}


def mean(cells, k):
    v = [c[k] for c in cells if c and k in c]
    return statistics.mean(v) if v else None


def fmt(x):
    return "-" if x is None else f"{x:.1f}"


def main():
    sets = {s: load(f"{DATA}/rule_v1/{s}/records.jsonl") for s in ("test_L2", "test_L3inv")}
    out, L = {}, ["# Stage 2 results (role C; generated)", "",
                  "Generated by `scripts/stage2_report.py` from result files (no typed numbers).", "",
                  "## 1. Rule-tier controls (C1; analysis plan, secondary 5)", "",
                  "Triplet accuracy and its parts on `rule_v1/test_L2` with the stated rule, with the rule text removed and "
                  "with another group's rule (views built by `scripts/crit_views.py`; labels stay those of the generating "
                  "rule). L2 holds 20 hand-written and 83 sampled rules; invented-name rules are `rule_v1/test_L3inv`. "
                  "Means over the seeds listed; result files: `results_git/C-S2-ctrl-<system>/` and the stage-1 runs.", "",
                  "| System (seeds) | rule text | TA | Rev | Hold | TA hand-written | TA sampled | TA invented names (L3-inv) |",
                  "|---|---|---|---|---|---|---|---|"]
    for name, label, runs, base_dirs in SYSTEMS:
        out[name] = {}
        for cond, suffix in (("stated", ""), ("none", "@none"), ("wrong", "@wrong")):
            cells = {"test_L2": [], "test_L3inv": []}
            for run, bdir in zip(runs, base_dirs):
                for s in cells:
                    p = f"{bdir}/scores_rule_v1~{s}.jsonl" if cond == "stated" else f"{RES}/C-S2-ctrl-{run}/scores_rule_v1~{s}{suffix}.jsonl"
                    u = scores(p)
                    if u:
                        cells[s].append(cell(sets[s], u, suffix))
            l2, inv = cells["test_L2"], cells["test_L3inv"]
            out[name][cond] = {"seeds": len(l2), **{k: mean(l2, k) for k in ("TA", "Rev", "Hold", "TA_hand", "TA_sampled")},
                               "TA_invented": mean(inv, "TA"), "seeds_invented": len(inv),
                               "by_seed_TA": [c["TA"] for c in l2]}
            o = out[name][cond]
            L.append(f"| {label} ({o['seeds']}) | {cond} | " + (" | ".join(fmt(o[k]) for k in ("TA", "Rev", "Hold", "TA_hand", "TA_sampled", "TA_invented"))
                                                                  if o["seeds"] else "not run | | | | |") + " |")
    os.makedirs(f"{RES}/C-S2-ctrl", exist_ok=True)
    json.dump({"run_id": "C-S2-ctrl", "set": "rule_v1/test_L2 and views", "systems": out},
              open(f"{RES}/C-S2-ctrl/summary.json", "w", encoding="utf-8", newline="\n"), indent=1)
    open(f"{REPO}/docs/STAGE2_RESULTS.md", "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L[-16:]))


if __name__ == "__main__":
    main()
